set -e

df -h

mkdir -p $GITHUB_WORKSPACE/aosp && cd $GITHUB_WORKSPACE/aosp
mkdir -p out/soong/ && echo userdebug.buildbot.20240101.000000 > out/soong/build_number.txt
mkdir -p out/soong/.minibootstrap && ln -sf $GITHUB_WORKSPACE/bpglob out/soong/.minibootstrap/bpglob
ln -sf $GITHUB_WORKSPACE/ndk.ninja .
ln -sf $GITHUB_WORKSPACE/ninja-ndk .
ln -sf $GITHUB_WORKSPACE/ninja .

mkdir -p prebuilts/clang/host/ && ln -sf $GITHUB_WORKSPACE/prebuilts/clang/host/linux-x86 prebuilts/clang/host/linux-x86

clone_depth_platform art
clone_depth_platform external/angle

rsync -a -r $GITHUB_WORKSPACE/artifacts/build/soong/cmd/sbox/sbox^linux_glibc_x86_64/ .

echo "building angle_commit_id^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja angle_commit_id,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/angle_commit_id^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/angle_commit_id^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/angle_commit_id^android_x86_64

echo "building angle_commit_id^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja angle_commit_id,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/angle_commit_id^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/angle_commit_id^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/angle_commit_id^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_enums_unified1^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_core_tables_unified1^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_generators_inc^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_glsl_tables_glsl1-0^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_cldebuginfo100^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_debuginfo^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_language_header_vkdebuginfo100^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_opencl_tables_opencl1-0^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_debuginfo^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.clspvreflection^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_nonsemantic.shader.debuginfo.100^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_opencl.debuginfo.100^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-gcn-shader^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-ballot^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-explicit-vertex-parameter^android_x86_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax,android_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_64

echo "building third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_x86_64"
ninja -d keepdepfile -f $GITHUB_WORKSPACE/steps/build_04.ninja third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax,android_x86_x86_64
mkdir -p $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_x86_64
rsync -a -r --files-from=$GITHUB_WORKSPACE/steps/outputs_04/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_x86_64.output . $GITHUB_WORKSPACE/artifacts/external/angle/third_party_vulkan_deps_spirv_tools_src_spvtools_vendor_tables_spv-amd-shader-trinary-minmax^android_x86_x86_64

rm -rf out

cd $GITHUB_WORKSPACE/
tar -cf external_angle.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/external/angle/ .
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_04 external_angle.tar.zst --clobber

du -ah -d1| sort -h

if [ ! -f "$GITHUB_WORKSPACE/cache/art.tar.zst" ]; then
  echo "Compressing art -> art.tar.zst"
  tar -cf $GITHUB_WORKSPACE/cache/art.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/aosp/art/ .
fi
if [ ! -f "$GITHUB_WORKSPACE/cache/external_angle.tar.zst" ]; then
  echo "Compressing external/angle -> external_angle.tar.zst"
  tar -cf $GITHUB_WORKSPACE/cache/external_angle.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/aosp/external/angle/ .
fi
du -ah -d1 $GITHUB_WORKSPACE/cache| sort -h

rm -rf aosp
