cd $GITHUB_WORKSPACE/

tar -cf art.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ art
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati art.tar.zst --clobber
tar -cf bionic.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ bionic
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati bionic.tar.zst --clobber
tar -cf bootable_recovery.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ bootable/recovery
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati bootable_recovery.tar.zst --clobber
tar -cf build_make.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ build/make
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati build_make.tar.zst --clobber
tar -cf build_soong.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ build/soong
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati build_soong.tar.zst --clobber
tar -cf device_generic_goldfish.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ device/generic/goldfish
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati device_generic_goldfish.tar.zst --clobber
tar -cf device_generic_goldfish-opengl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ device/generic/goldfish-opengl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati device_generic_goldfish-opengl.tar.zst --clobber
tar -cf device_generic_vulkan-cereal.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ device/generic/vulkan-cereal
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati device_generic_vulkan-cereal.tar.zst --clobber
tar -cf device_google_cuttlefish.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ device/google/cuttlefish
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati device_google_cuttlefish.tar.zst --clobber
tar -cf external_android-clat.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/android-clat
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_android-clat.tar.zst --clobber
tar -cf external_angle.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/angle
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_angle.tar.zst --clobber
tar -cf external_apache-http.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/apache-http
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_apache-http.tar.zst --clobber
tar -cf external_auto.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/auto
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_auto.tar.zst --clobber
tar -cf external_avb.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/avb
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_avb.tar.zst --clobber
tar -cf external_bc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/bc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_bc.tar.zst --clobber
tar -cf external_bcc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/bcc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_bcc.tar.zst --clobber
tar -cf external_boringssl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/boringssl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_boringssl.tar.zst --clobber
tar -cf external_brotli.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/brotli
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_brotli.tar.zst --clobber
tar -cf external_bsdiff.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/bsdiff
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_bsdiff.tar.zst --clobber
tar -cf external_bzip2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/bzip2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_bzip2.tar.zst --clobber
tar -cf external_cblas.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/cblas
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_cblas.tar.zst --clobber
tar -cf external_chromium-webview.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/chromium-webview
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_chromium-webview.tar.zst --clobber
tar -cf external_compiler-rt.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/compiler-rt
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_compiler-rt.tar.zst --clobber
tar -cf external_conscrypt.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/conscrypt
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_conscrypt.tar.zst --clobber
tar -cf external_crosvm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/crosvm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_crosvm.tar.zst --clobber
tar -cf external_curl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/curl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_curl.tar.zst --clobber
tar -cf external_dng_sdk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/dng_sdk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_dng_sdk.tar.zst --clobber
tar -cf external_dnsmasq.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/dnsmasq
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_dnsmasq.tar.zst --clobber
tar -cf external_drm_hwcomposer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/drm_hwcomposer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_drm_hwcomposer.tar.zst --clobber
tar -cf external_dtc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/dtc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_dtc.tar.zst --clobber
tar -cf external_dynamic_depth.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/dynamic_depth
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_dynamic_depth.tar.zst --clobber
tar -cf external_e2fsprogs.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/e2fsprogs
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_e2fsprogs.tar.zst --clobber
tar -cf external_erofs-utils.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/erofs-utils
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_erofs-utils.tar.zst --clobber
tar -cf external_expat.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/expat
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_expat.tar.zst --clobber
tar -cf external_f2fs-tools.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/f2fs-tools
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_f2fs-tools.tar.zst --clobber
tar -cf external_fec.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/fec
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_fec.tar.zst --clobber
tar -cf external_flatbuffers.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/flatbuffers
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_flatbuffers.tar.zst --clobber
tar -cf external_freetype.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/freetype
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_freetype.tar.zst --clobber
tar -cf external_fsck_msdos.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/fsck_msdos
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_fsck_msdos.tar.zst --clobber
tar -cf external_fsverity-utils.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/fsverity-utils
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_fsverity-utils.tar.zst --clobber
tar -cf external_glide.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/glide
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_glide.tar.zst --clobber
tar -cf external_google-fonts_carrois-gothic-sc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fonts/carrois-gothic-sc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fonts_carrois-gothic-sc.tar.zst --clobber
tar -cf external_google-fonts_coming-soon.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fonts/coming-soon
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fonts_coming-soon.tar.zst --clobber
tar -cf external_google-fonts_cutive-mono.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fonts/cutive-mono
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fonts_cutive-mono.tar.zst --clobber
tar -cf external_google-fonts_dancing-script.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fonts/dancing-script
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fonts_dancing-script.tar.zst --clobber
tar -cf external_google-fonts_source-sans-pro.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fonts/source-sans-pro
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fonts_source-sans-pro.tar.zst --clobber
tar -cf external_google-fruit.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/google-fruit
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_google-fruit.tar.zst --clobber
tar -cf external_gptfdisk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/gptfdisk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_gptfdisk.tar.zst --clobber
tar -cf external_grpc-grpc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/grpc-grpc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_grpc-grpc.tar.zst --clobber
tar -cf external_guava.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/guava
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_guava.tar.zst --clobber
tar -cf external_harfbuzz_ng.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/harfbuzz_ng
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_harfbuzz_ng.tar.zst --clobber
tar -cf external_hyphenation-patterns.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/hyphenation-patterns
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_hyphenation-patterns.tar.zst --clobber
tar -cf external_icu.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/icu
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_icu.tar.zst --clobber
tar -cf external_image_io.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/image_io
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_image_io.tar.zst --clobber
tar -cf external_iperf3.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/iperf3
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_iperf3.tar.zst --clobber
tar -cf external_iproute2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/iproute2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_iproute2.tar.zst --clobber
tar -cf external_ipsec-tools.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/ipsec-tools
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_ipsec-tools.tar.zst --clobber
tar -cf external_iptables.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/iptables
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_iptables.tar.zst --clobber
tar -cf external_iputils.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/iputils
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_iputils.tar.zst --clobber
tar -cf external_iw.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/iw
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_iw.tar.zst --clobber
tar -cf external_jsoncpp.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/jsoncpp
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_jsoncpp.tar.zst --clobber
tar -cf external_jsr305.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/jsr305
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_jsr305.tar.zst --clobber
tar -cf external_kmod.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/kmod
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_kmod.tar.zst --clobber
tar -cf external_libbackup.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libbackup
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libbackup.tar.zst --clobber
tar -cf external_libbrillo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libbrillo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libbrillo.tar.zst --clobber
tar -cf external_libcap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libcap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libcap.tar.zst --clobber
tar -cf external_libchrome.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libchrome
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libchrome.tar.zst --clobber
tar -cf external_libcppbor.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libcppbor
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libcppbor.tar.zst --clobber
tar -cf external_libcups.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libcups
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libcups.tar.zst --clobber
tar -cf external_libcxx.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libcxx
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libcxx.tar.zst --clobber
tar -cf external_libcxxabi.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libcxxabi
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libcxxabi.tar.zst --clobber
tar -cf external_libdrm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libdrm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libdrm.tar.zst --clobber
tar -cf external_libevent.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libevent
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libevent.tar.zst --clobber
tar -cf external_libexif.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libexif
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libexif.tar.zst --clobber
tar -cf external_libjpeg-turbo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libjpeg-turbo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libjpeg-turbo.tar.zst --clobber
tar -cf external_libldac.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libldac
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libldac.tar.zst --clobber
tar -cf external_libnl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libnl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libnl.tar.zst --clobber
tar -cf external_libopus.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libopus
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libopus.tar.zst --clobber
tar -cf external_libpcap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libpcap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libpcap.tar.zst --clobber
tar -cf external_libphonenumber.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libphonenumber
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libphonenumber.tar.zst --clobber
tar -cf external_libpng.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libpng
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libpng.tar.zst --clobber
tar -cf external_libtextclassifier.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libtextclassifier
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libtextclassifier.tar.zst --clobber
tar -cf external_libvpx.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libvpx
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libvpx.tar.zst --clobber
tar -cf external_libxml2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libxml2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libxml2.tar.zst --clobber
tar -cf external_libyuv.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/libyuv
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_libyuv.tar.zst --clobber
tar -cf external_llvm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/llvm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_llvm.tar.zst --clobber
tar -cf external_lz4.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/lz4
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_lz4.tar.zst --clobber
tar -cf external_lzma.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/lzma
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_lzma.tar.zst --clobber
tar -cf external_mdnsresponder.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/mdnsresponder
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_mdnsresponder.tar.zst --clobber
tar -cf external_mesa3d.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/mesa3d
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_mesa3d.tar.zst --clobber
tar -cf external_minigbm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/minigbm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_minigbm.tar.zst --clobber
tar -cf external_minijail.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/minijail
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_minijail.tar.zst --clobber
tar -cf external_mksh.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/mksh
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_mksh.tar.zst --clobber
tar -cf external_mtpd.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/mtpd
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_mtpd.tar.zst --clobber
tar -cf external_nanopb-c.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/nanopb-c
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_nanopb-c.tar.zst --clobber
tar -cf external_neven.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/neven
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_neven.tar.zst --clobber
tar -cf external_newfs_msdos.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/newfs_msdos
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_newfs_msdos.tar.zst --clobber
tar -cf external_noto-fonts.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/noto-fonts
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_noto-fonts.tar.zst --clobber
tar -cf external_one-true-awk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/one-true-awk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_one-true-awk.tar.zst --clobber
tar -cf external_parameter-framework.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/parameter-framework
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_parameter-framework.tar.zst --clobber
tar -cf external_pcre.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/pcre
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_pcre.tar.zst --clobber
tar -cf external_pdfium.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/pdfium
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_pdfium.tar.zst --clobber
tar -cf external_perfetto.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/perfetto
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_perfetto.tar.zst --clobber
tar -cf external_piex.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/piex
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_piex.tar.zst --clobber
tar -cf external_ppp.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/ppp
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_ppp.tar.zst --clobber
tar -cf external_protobuf.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/protobuf
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_protobuf.tar.zst --clobber
tar -cf external_roboto-fonts.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/roboto-fonts
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_roboto-fonts.tar.zst --clobber
tar -cf external_rust_crates_android_log-sys.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/android_log-sys
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_android_log-sys.tar.zst --clobber
tar -cf external_rust_crates_android_logger.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/android_logger
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_android_logger.tar.zst --clobber
tar -cf external_rust_crates_anyhow.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/anyhow
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_anyhow.tar.zst --clobber
tar -cf external_rust_crates_async-task.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/async-task
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_async-task.tar.zst --clobber
tar -cf external_rust_crates_bitflags.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/bitflags
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_bitflags.tar.zst --clobber
tar -cf external_rust_crates_byteorder.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/byteorder
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_byteorder.tar.zst --clobber
tar -cf external_rust_crates_cfg-if.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/cfg-if
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_cfg-if.tar.zst --clobber
tar -cf external_rust_crates_chrono.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/chrono
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_chrono.tar.zst --clobber
tar -cf external_rust_crates_clap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/clap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_clap.tar.zst --clobber
tar -cf external_rust_crates_crc32fast.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/crc32fast
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_crc32fast.tar.zst --clobber
tar -cf external_rust_crates_env_logger.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/env_logger
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_env_logger.tar.zst --clobber
tar -cf external_rust_crates_flate2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/flate2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_flate2.tar.zst --clobber
tar -cf external_rust_crates_futures.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures.tar.zst --clobber
tar -cf external_rust_crates_futures-channel.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-channel
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-channel.tar.zst --clobber
tar -cf external_rust_crates_futures-core.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-core
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-core.tar.zst --clobber
tar -cf external_rust_crates_futures-executor.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-executor
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-executor.tar.zst --clobber
tar -cf external_rust_crates_futures-io.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-io
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-io.tar.zst --clobber
tar -cf external_rust_crates_futures-sink.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-sink
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-sink.tar.zst --clobber
tar -cf external_rust_crates_futures-task.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-task
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-task.tar.zst --clobber
tar -cf external_rust_crates_futures-util.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/futures-util
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_futures-util.tar.zst --clobber
tar -cf external_rust_crates_getrandom.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/getrandom
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_getrandom.tar.zst --clobber
tar -cf external_rust_crates_grpcio-sys.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/grpcio-sys
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_grpcio-sys.tar.zst --clobber
tar -cf external_rust_crates_intrusive-collections.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/intrusive-collections
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_intrusive-collections.tar.zst --clobber
tar -cf external_rust_crates_itoa.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/itoa
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_itoa.tar.zst --clobber
tar -cf external_rust_crates_lazy_static.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/lazy_static
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_lazy_static.tar.zst --clobber
tar -cf external_rust_crates_libc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/libc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_libc.tar.zst --clobber
tar -cf external_rust_crates_libz-sys.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/libz-sys
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_libz-sys.tar.zst --clobber
tar -cf external_rust_crates_log.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/log
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_log.tar.zst --clobber
tar -cf external_rust_crates_macaddr.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/macaddr
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_macaddr.tar.zst --clobber
tar -cf external_rust_crates_memchr.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/memchr
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_memchr.tar.zst --clobber
tar -cf external_rust_crates_memoffset.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/memoffset
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_memoffset.tar.zst --clobber
tar -cf external_rust_crates_nix.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/nix
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_nix.tar.zst --clobber
tar -cf external_rust_crates_num-integer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/num-integer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_num-integer.tar.zst --clobber
tar -cf external_rust_crates_num-traits.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/num-traits
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_num-traits.tar.zst --clobber
tar -cf external_rust_crates_num_cpus.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/num_cpus
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_num_cpus.tar.zst --clobber
tar -cf external_rust_crates_pin-project-lite.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/pin-project-lite
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_pin-project-lite.tar.zst --clobber
tar -cf external_rust_crates_pin-utils.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/pin-utils
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_pin-utils.tar.zst --clobber
tar -cf external_rust_crates_ppv-lite86.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/ppv-lite86
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_ppv-lite86.tar.zst --clobber
tar -cf external_rust_crates_proc-macro-nested.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/proc-macro-nested
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_proc-macro-nested.tar.zst --clobber
tar -cf external_rust_crates_rand.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/rand
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_rand.tar.zst --clobber
tar -cf external_rust_crates_rand_chacha.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/rand_chacha
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_rand_chacha.tar.zst --clobber
tar -cf external_rust_crates_rand_core.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/rand_core
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_rand_core.tar.zst --clobber
tar -cf external_rust_crates_ryu.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/ryu
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_ryu.tar.zst --clobber
tar -cf external_rust_crates_serde.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/serde
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_serde.tar.zst --clobber
tar -cf external_rust_crates_serde_json.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/serde_json
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_serde_json.tar.zst --clobber
tar -cf external_rust_crates_slab.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/slab
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_slab.tar.zst --clobber
tar -cf external_rust_crates_smallvec.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/smallvec
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_smallvec.tar.zst --clobber
tar -cf external_rust_crates_structopt.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/structopt
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_structopt.tar.zst --clobber
tar -cf external_rust_crates_textwrap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/textwrap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_textwrap.tar.zst --clobber
tar -cf external_rust_crates_thiserror.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/thiserror
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_thiserror.tar.zst --clobber
tar -cf external_rust_crates_uuid.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/uuid
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_uuid.tar.zst --clobber
tar -cf external_rust_crates_zip.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/rust/crates/zip
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_rust_crates_zip.tar.zst --clobber
tar -cf external_selinux.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/selinux
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_selinux.tar.zst --clobber
tar -cf external_sonic.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/sonic
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_sonic.tar.zst --clobber
tar -cf external_sonivox.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/sonivox
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_sonivox.tar.zst --clobber
tar -cf external_speex.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/speex
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_speex.tar.zst --clobber
tar -cf external_sqlite.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/sqlite
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_sqlite.tar.zst --clobber
tar -cf external_strace.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/strace
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_strace.tar.zst --clobber
tar -cf external_swiftshader.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/swiftshader
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_swiftshader.tar.zst --clobber
tar -cf external_tcpdump.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/tcpdump
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_tcpdump.tar.zst --clobber
tar -cf external_tinyalsa.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/tinyalsa
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_tinyalsa.tar.zst --clobber
tar -cf external_tinyxml2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/tinyxml2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_tinyxml2.tar.zst --clobber
tar -cf external_toybox.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/toybox
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_toybox.tar.zst --clobber
tar -cf external_tremolo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/tremolo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_tremolo.tar.zst --clobber
tar -cf external_volley.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/volley
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_volley.tar.zst --clobber
tar -cf external_wpa_supplicant_8.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/wpa_supplicant_8
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_wpa_supplicant_8.tar.zst --clobber
tar -cf external_xmp_toolkit.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/xmp_toolkit
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_xmp_toolkit.tar.zst --clobber
tar -cf external_zlib.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ external/zlib
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati external_zlib.tar.zst --clobber
tar -cf frameworks_av.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/av
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_av.tar.zst --clobber
tar -cf frameworks_base.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/base
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_base.tar.zst --clobber
tar -cf frameworks_compile_libbcc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/compile/libbcc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_compile_libbcc.tar.zst --clobber
tar -cf frameworks_compile_mclinker.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/compile/mclinker
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_compile_mclinker.tar.zst --clobber
tar -cf frameworks_ex.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/ex
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_ex.tar.zst --clobber
tar -cf frameworks_hardware_interfaces.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/hardware/interfaces
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_hardware_interfaces.tar.zst --clobber
tar -cf frameworks_minikin.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/minikin
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_minikin.tar.zst --clobber
tar -cf frameworks_native.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/native
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_native.tar.zst --clobber
tar -cf frameworks_opt_calendar.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/calendar
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_calendar.tar.zst --clobber
tar -cf frameworks_opt_chips.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/chips
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_chips.tar.zst --clobber
tar -cf frameworks_opt_colorpicker.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/colorpicker
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_colorpicker.tar.zst --clobber
tar -cf frameworks_opt_net_ethernet.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/net/ethernet
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_net_ethernet.tar.zst --clobber
tar -cf frameworks_opt_net_ims.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/net/ims
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_net_ims.tar.zst --clobber
tar -cf frameworks_opt_net_voip.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/net/voip
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_net_voip.tar.zst --clobber
tar -cf frameworks_opt_net_wifi.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/net/wifi
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_net_wifi.tar.zst --clobber
tar -cf frameworks_opt_photoviewer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/photoviewer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_photoviewer.tar.zst --clobber
tar -cf frameworks_opt_telephony.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/telephony
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_telephony.tar.zst --clobber
tar -cf frameworks_opt_timezonepicker.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/timezonepicker
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_timezonepicker.tar.zst --clobber
tar -cf frameworks_opt_vcard.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/opt/vcard
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_opt_vcard.tar.zst --clobber
tar -cf frameworks_proto_logging.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/proto_logging
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_proto_logging.tar.zst --clobber
tar -cf frameworks_rs.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/rs
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_rs.tar.zst --clobber
tar -cf frameworks_wilhelm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ frameworks/wilhelm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati frameworks_wilhelm.tar.zst --clobber
tar -cf hardware_google_camera.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ hardware/google/camera
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati hardware_google_camera.tar.zst --clobber
tar -cf hardware_interfaces.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ hardware/interfaces
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati hardware_interfaces.tar.zst --clobber
tar -cf hardware_libhardware.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ hardware/libhardware
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati hardware_libhardware.tar.zst --clobber
tar -cf hardware_libhardware_legacy.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ hardware/libhardware_legacy
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati hardware_libhardware_legacy.tar.zst --clobber
tar -cf hardware_ril.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ hardware/ril
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati hardware_ril.tar.zst --clobber
tar -cf libcore.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ libcore
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati libcore.tar.zst --clobber
tar -cf packages_apps_Bluetooth.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Bluetooth
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Bluetooth.tar.zst --clobber
tar -cf packages_apps_Browser2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Browser2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Browser2.tar.zst --clobber
tar -cf packages_apps_Calendar.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Calendar
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Calendar.tar.zst --clobber
tar -cf packages_apps_Camera2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Camera2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Camera2.tar.zst --clobber
tar -cf packages_apps_CarrierConfig.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/CarrierConfig
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_CarrierConfig.tar.zst --clobber
tar -cf packages_apps_CellBroadcastReceiver.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/CellBroadcastReceiver
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_CellBroadcastReceiver.tar.zst --clobber
tar -cf packages_apps_CertInstaller.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/CertInstaller
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_CertInstaller.tar.zst --clobber
tar -cf packages_apps_Contacts.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Contacts
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Contacts.tar.zst --clobber
tar -cf packages_apps_DeskClock.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/DeskClock
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_DeskClock.tar.zst --clobber
tar -cf packages_apps_Dialer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Dialer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Dialer.tar.zst --clobber
tar -cf packages_apps_DocumentsUI.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/DocumentsUI
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_DocumentsUI.tar.zst --clobber
tar -cf packages_apps_EmergencyInfo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/EmergencyInfo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_EmergencyInfo.tar.zst --clobber
tar -cf packages_apps_Gallery2.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Gallery2
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Gallery2.tar.zst --clobber
tar -cf packages_apps_HTMLViewer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/HTMLViewer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_HTMLViewer.tar.zst --clobber
tar -cf packages_apps_ImsServiceEntitlement.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/ImsServiceEntitlement
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_ImsServiceEntitlement.tar.zst --clobber
tar -cf packages_apps_KeyChain.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/KeyChain
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_KeyChain.tar.zst --clobber
tar -cf packages_apps_Launcher3.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Launcher3
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Launcher3.tar.zst --clobber
tar -cf packages_apps_ManagedProvisioning.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/ManagedProvisioning
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_ManagedProvisioning.tar.zst --clobber
tar -cf packages_apps_Messaging.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Messaging
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Messaging.tar.zst --clobber
tar -cf packages_apps_Music.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Music
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Music.tar.zst --clobber
tar -cf packages_apps_MusicFX.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/MusicFX
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_MusicFX.tar.zst --clobber
tar -cf packages_apps_Nfc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Nfc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Nfc.tar.zst --clobber
tar -cf packages_apps_OneTimeInitializer.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/OneTimeInitializer
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_OneTimeInitializer.tar.zst --clobber
tar -cf packages_apps_Provision.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Provision
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Provision.tar.zst --clobber
tar -cf packages_apps_QuickSearchBox.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/QuickSearchBox
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_QuickSearchBox.tar.zst --clobber
tar -cf packages_apps_RemoteProvisioner.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/RemoteProvisioner
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_RemoteProvisioner.tar.zst --clobber
tar -cf packages_apps_SecureElement.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/SecureElement
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_SecureElement.tar.zst --clobber
tar -cf packages_apps_Settings.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Settings
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Settings.tar.zst --clobber
tar -cf packages_apps_SettingsIntelligence.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/SettingsIntelligence
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_SettingsIntelligence.tar.zst --clobber
tar -cf packages_apps_Stk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Stk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Stk.tar.zst --clobber
tar -cf packages_apps_StorageManager.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/StorageManager
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_StorageManager.tar.zst --clobber
tar -cf packages_apps_Tag.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Tag
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Tag.tar.zst --clobber
tar -cf packages_apps_Traceur.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/Traceur
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_Traceur.tar.zst --clobber
tar -cf packages_apps_WallpaperPicker.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/apps/WallpaperPicker
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_apps_WallpaperPicker.tar.zst --clobber
tar -cf packages_inputmethods_LatinIME.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/inputmethods/LatinIME
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_inputmethods_LatinIME.tar.zst --clobber
tar -cf packages_modules_CaptivePortalLogin.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/CaptivePortalLogin
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_CaptivePortalLogin.tar.zst --clobber
tar -cf packages_modules_Connectivity.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/Connectivity
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_Connectivity.tar.zst --clobber
tar -cf packages_modules_DnsResolver.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/DnsResolver
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_DnsResolver.tar.zst --clobber
tar -cf packages_modules_ExtServices.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/ExtServices
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_ExtServices.tar.zst --clobber
tar -cf packages_modules_IPsec.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/IPsec
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_IPsec.tar.zst --clobber
tar -cf packages_modules_ModuleMetadata.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/ModuleMetadata
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_ModuleMetadata.tar.zst --clobber
tar -cf packages_modules_NetworkPermissionConfig.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/NetworkPermissionConfig
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_NetworkPermissionConfig.tar.zst --clobber
tar -cf packages_modules_NetworkStack.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/NetworkStack
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_NetworkStack.tar.zst --clobber
tar -cf packages_modules_NeuralNetworks.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/NeuralNetworks
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_NeuralNetworks.tar.zst --clobber
tar -cf packages_modules_Permission.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/Permission
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_Permission.tar.zst --clobber
tar -cf packages_modules_RuntimeI18n.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/RuntimeI18n
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_RuntimeI18n.tar.zst --clobber
tar -cf packages_modules_Scheduling.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/Scheduling
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_Scheduling.tar.zst --clobber
tar -cf packages_modules_SdkExtensions.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/SdkExtensions
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_SdkExtensions.tar.zst --clobber
tar -cf packages_modules_StatsD.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/StatsD
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_StatsD.tar.zst --clobber
tar -cf packages_modules_Virtualization.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/Virtualization
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_Virtualization.tar.zst --clobber
tar -cf packages_modules_Wifi.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/Wifi
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_Wifi.tar.zst --clobber
tar -cf packages_modules_adb.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/adb
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_adb.tar.zst --clobber
tar -cf packages_modules_vndk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/modules/vndk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_modules_vndk.tar.zst --clobber
tar -cf packages_providers_BlockedNumberProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/BlockedNumberProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_BlockedNumberProvider.tar.zst --clobber
tar -cf packages_providers_BookmarkProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/BookmarkProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_BookmarkProvider.tar.zst --clobber
tar -cf packages_providers_CalendarProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/CalendarProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_CalendarProvider.tar.zst --clobber
tar -cf packages_providers_CallLogProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/CallLogProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_CallLogProvider.tar.zst --clobber
tar -cf packages_providers_ContactsProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/ContactsProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_ContactsProvider.tar.zst --clobber
tar -cf packages_providers_DownloadProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/DownloadProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_DownloadProvider.tar.zst --clobber
tar -cf packages_providers_MediaProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/MediaProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_MediaProvider.tar.zst --clobber
tar -cf packages_providers_PartnerBookmarksProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/PartnerBookmarksProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_PartnerBookmarksProvider.tar.zst --clobber
tar -cf packages_providers_TelephonyProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/TelephonyProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_TelephonyProvider.tar.zst --clobber
tar -cf packages_providers_UserDictionaryProvider.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/providers/UserDictionaryProvider
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_providers_UserDictionaryProvider.tar.zst --clobber
tar -cf packages_screensavers_Basic.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/screensavers/Basic
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_screensavers_Basic.tar.zst --clobber
tar -cf packages_screensavers_PhotoTable.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/screensavers/PhotoTable
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_screensavers_PhotoTable.tar.zst --clobber
tar -cf packages_services_AlternativeNetworkAccess.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/AlternativeNetworkAccess
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_AlternativeNetworkAccess.tar.zst --clobber
tar -cf packages_services_BuiltInPrintService.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/BuiltInPrintService
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_BuiltInPrintService.tar.zst --clobber
tar -cf packages_services_Mms.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/Mms
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_Mms.tar.zst --clobber
tar -cf packages_services_Mtp.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/Mtp
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_Mtp.tar.zst --clobber
tar -cf packages_services_Telecomm.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/Telecomm
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_Telecomm.tar.zst --clobber
tar -cf packages_services_Telephony.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/services/Telephony
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_services_Telephony.tar.zst --clobber
tar -cf packages_wallpapers_LivePicker.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ packages/wallpapers/LivePicker
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati packages_wallpapers_LivePicker.tar.zst --clobber
tar -cf prebuilts_clang_host_linux-x86.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/clang/host/linux-x86
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_clang_host_linux-x86.tar.zst --clobber
tar -cf prebuilts_misc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/misc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_misc.tar.zst --clobber
tar -cf prebuilts_ndk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/ndk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_ndk.tar.zst --clobber
tar -cf prebuilts_rust.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/rust
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_rust.tar.zst --clobber
tar -cf prebuilts_sdk.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/sdk
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_sdk.tar.zst --clobber
tar -cf prebuilts_tools.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ prebuilts/tools
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati prebuilts_tools.tar.zst --clobber
tar -cf system_apex.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/apex
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_apex.tar.zst --clobber
tar -cf system_bpf.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/bpf
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_bpf.tar.zst --clobber
tar -cf system_bpfprogs.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/bpfprogs
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_bpfprogs.tar.zst --clobber
tar -cf system_bt.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/bt
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_bt.tar.zst --clobber
tar -cf system_ca-certificates.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/ca-certificates
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_ca-certificates.tar.zst --clobber
tar -cf system_connectivity_wificond.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/connectivity/wificond
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_connectivity_wificond.tar.zst --clobber
tar -cf system_core.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/core
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_core.tar.zst --clobber
tar -cf system_extras.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/extras
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_extras.tar.zst --clobber
tar -cf system_gatekeeper.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/gatekeeper
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_gatekeeper.tar.zst --clobber
tar -cf system_gsid.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/gsid
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_gsid.tar.zst --clobber
tar -cf system_hardware_interfaces.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/hardware/interfaces
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_hardware_interfaces.tar.zst --clobber
tar -cf system_hwservicemanager.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/hwservicemanager
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_hwservicemanager.tar.zst --clobber
tar -cf system_incremental_delivery.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/incremental_delivery
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_incremental_delivery.tar.zst --clobber
tar -cf system_iorap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/iorap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_iorap.tar.zst --clobber
tar -cf system_keymaster.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/keymaster
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_keymaster.tar.zst --clobber
tar -cf system_libartpalette.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libartpalette
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libartpalette.tar.zst --clobber
tar -cf system_libbase.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libbase
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libbase.tar.zst --clobber
tar -cf system_libfmq.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libfmq
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libfmq.tar.zst --clobber
tar -cf system_libhidl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libhidl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libhidl.tar.zst --clobber
tar -cf system_libhwbinder.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libhwbinder
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libhwbinder.tar.zst --clobber
tar -cf system_libprocinfo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libprocinfo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libprocinfo.tar.zst --clobber
tar -cf system_libvintf.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libvintf
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libvintf.tar.zst --clobber
tar -cf system_libziparchive.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/libziparchive
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_libziparchive.tar.zst --clobber
tar -cf system_linkerconfig.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/linkerconfig
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_linkerconfig.tar.zst --clobber
tar -cf system_logging.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/logging
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_logging.tar.zst --clobber
tar -cf system_media.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/media
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_media.tar.zst --clobber
tar -cf system_memory_libdmabufheap.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/libdmabufheap
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_libdmabufheap.tar.zst --clobber
tar -cf system_memory_libion.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/libion
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_libion.tar.zst --clobber
tar -cf system_memory_libmeminfo.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/libmeminfo
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_libmeminfo.tar.zst --clobber
tar -cf system_memory_libmemtrack.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/libmemtrack
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_libmemtrack.tar.zst --clobber
tar -cf system_memory_libmemunreachable.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/libmemunreachable
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_libmemunreachable.tar.zst --clobber
tar -cf system_memory_lmkd.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/memory/lmkd
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_memory_lmkd.tar.zst --clobber
tar -cf system_netd.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/netd
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_netd.tar.zst --clobber
tar -cf system_nfc.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/nfc
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_nfc.tar.zst --clobber
tar -cf system_security.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/security
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_security.tar.zst --clobber
tar -cf system_sepolicy.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/sepolicy
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_sepolicy.tar.zst --clobber
tar -cf system_server_configurable_flags.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/server_configurable_flags
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_server_configurable_flags.tar.zst --clobber
tar -cf system_timezone.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/timezone
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_timezone.tar.zst --clobber
tar -cf system_tools_aidl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/tools/aidl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_tools_aidl.tar.zst --clobber
tar -cf system_tools_hidl.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/tools/hidl
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_tools_hidl.tar.zst --clobber
tar -cf system_tools_mkbootimg.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/tools/mkbootimg
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_tools_mkbootimg.tar.zst --clobber
tar -cf system_unwinding.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/unwinding
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_unwinding.tar.zst --clobber
tar -cf system_update_engine.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/update_engine
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_update_engine.tar.zst --clobber
tar -cf system_vold.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ system/vold
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati system_vold.tar.zst --clobber
tar -cf tools_dexter.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ tools/dexter
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati tools_dexter.tar.zst --clobber
tar -cf tools_security.tar.zst --use-compress-program zstdmt -C $GITHUB_WORKSPACE/artifacts/ tools/security
gh release --repo cibuilde/aosp-buildbot upload android12-gsi_kati tools_security.tar.zst --clobber
du -ah -d1 *.tar.zst | sort -h
df -h
