source $GITHUB_WORKSPACE/envsetup.sh
df -h

sed -i 's/libLLVM_android.so"],$/libLLVM_android.so"],}, android_x86_64: { srcs: ["libLLVM_android.so"], }, android_x86: { srcs: ["libLLVM_android.so"],/g' prebuilts/sdk/tools/Android.bp
sed -i 's/name: "libLLVM_android",$/name: "libLLVM_android", device_supported: true, prefer: true,/g' prebuilts/sdk/tools/Android.bp
mv prebuiltlibs/external/llvm/libLLVM_android/android_x86_64_shared/libLLVM_android.so prebuilts/sdk/tools/
GOROOT=$TOP/prebuilts/go/linux-x86 $GITHUB_WORKSPACE/soong_ui --make-mode --skip-ninja --skip-kati --skip-soong-tests --skip-write-modules -j1 TARGET_PRODUCT=aosp_x86_64 TARGET_BUILD_VARIANT=eng ALLOW_MISSING_DEPENDENCIES=true BUILD_BROKEN_DISABLE_BAZEL=1 nothing

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_dylib/libcros_async.dylib.so \
  out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_rlib_rlib-std_apex10000/libcros_async.rlib \
  out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_dylib_apex10000/libcros_async.dylib.so \
  out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_dylib/libbase.dylib.so \
  out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_rlib_rlib-std_apex10000/libbase.rlib \
  out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_dylib_apex10000/libbase.dylib.so \
  out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_rlib_rlib-std_apex10000/libfuse.rlib \
  out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib/libfuse.dylib.so \
  out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib_apex10000/libfuse.dylib.so \
  out/soong/.intermediates/external/crosvm/kvm_sys/libkvm_sys/android_x86_64_rlib_rlib-std_apex10000/libkvm_sys.rlib \
  out/soong/.intermediates/external/crosvm/linux_input_sys/liblinux_input_sys/android_x86_64_rlib_rlib-std_apex10000/liblinux_input_sys.rlib \
  out/soong/.intermediates/external/crosvm/gpu_display/libgpu_display/android_x86_64_rlib_rlib-std_apex10000/libgpu_display.rlib \
  out/soong/.intermediates/external/crosvm/net_sys/libnet_sys/android_x86_64_rlib_rlib-std_apex10000/libnet_sys.rlib \
  out/soong/.intermediates/external/crosvm/net_util/libnet_util/android_x86_64_rlib_rlib-std_apex10000/libnet_util.rlib \
  out/soong/.intermediates/external/crosvm/power_monitor/libpower_monitor/android_x86_64_rlib_rlib-std_apex10000/libpower_monitor.rlib \
  out/soong/.intermediates/external/crosvm/resources/libresources/android_x86_64_rlib_rlib-std_apex10000/libresources.rlib \
  out/soong/.intermediates/external/crosvm/usb_sys/libusb_sys/android_x86_64_rlib_rlib-std_apex10000/libusb_sys.rlib \
  out/soong/.intermediates/external/crosvm/usb_util/libusb_util/android_x86_64_rlib_rlib-std_apex10000/libusb_util.rlib \
  out/soong/.intermediates/external/crosvm/vfio_sys/libvfio_sys/android_x86_64_rlib_rlib-std_apex10000/libvfio_sys.rlib \
  out/soong/.intermediates/external/crosvm/virtio_sys/libvirtio_sys/android_x86_64_rlib_rlib-std_apex10000/libvirtio_sys.rlib \
  out/soong/.intermediates/external/crosvm/vm_memory/libvm_memory/android_x86_64_rlib_rlib-std_apex10000/libvm_memory.rlib \
  out/soong/.intermediates/external/crosvm/disk/libdisk/android_x86_64_rlib_rlib-std_apex10000/libdisk.rlib \
  out/soong/.intermediates/external/crosvm/kernel_loader/libkernel_loader/android_x86_64_rlib_rlib-std_apex10000/libkernel_loader.rlib \
  out/soong/.intermediates/external/crosvm/kvm/libkvm/android_x86_64_rlib_rlib-std_apex10000/libkvm.rlib \
  out/soong/.intermediates/external/crosvm/hypervisor/libhypervisor/android_x86_64_rlib_rlib-std_apex10000/libhypervisor.rlib \
  out/soong/.intermediates/external/crosvm/vhost/libvhost/android_x86_64_rlib_rlib-std_apex10000/libvhost.rlib \
  

mkdir -p prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_dylib/ && mv out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_dylib/libcros_async.dylib.so prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_dylib/libcros_async.dylib.so
mkdir -p prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_rlib_rlib-std_apex10000/libcros_async.rlib prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_rlib_rlib-std_apex10000/libcros_async.rlib
mkdir -p prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_dylib_apex10000/ && mv out/soong/.intermediates/external/crosvm/cros_async/libcros_async/android_x86_64_dylib_apex10000/libcros_async.dylib.so prebuiltlibs/external/crosvm/cros_async/libcros_async/android_x86_64_dylib_apex10000/libcros_async.dylib.so
mkdir -p prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_dylib/ && mv out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_dylib/libbase.dylib.so prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_dylib/libbase_rust.dylib.so
mkdir -p prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_rlib_rlib-std_apex10000/libbase.rlib prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_rlib_rlib-std_apex10000/libbase_rust.rlib
mkdir -p prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_dylib_apex10000/ && mv out/soong/.intermediates/external/crosvm/base/libbase_rust/android_x86_64_dylib_apex10000/libbase.dylib.so prebuiltlibs/external/crosvm/base/libbase_rust/android_x86_64_dylib_apex10000/libbase_rust.dylib.so
mkdir -p prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_rlib_rlib-std_apex10000/libfuse.rlib prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_rlib_rlib-std_apex10000/libfuse_rust.rlib
mkdir -p prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib/ && mv out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib/libfuse.dylib.so prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib/libfuse_rust.dylib.so
mkdir -p prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib_apex10000/ && mv out/soong/.intermediates/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib_apex10000/libfuse.dylib.so prebuiltlibs/external/crosvm/fuse/libfuse_rust/android_x86_64_dylib_apex10000/libfuse_rust.dylib.so
mkdir -p prebuiltlibs/external/crosvm/kvm_sys/libkvm_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/kvm_sys/libkvm_sys/android_x86_64_rlib_rlib-std_apex10000/libkvm_sys.rlib prebuiltlibs/external/crosvm/kvm_sys/libkvm_sys/android_x86_64_rlib_rlib-std_apex10000/libkvm_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/linux_input_sys/liblinux_input_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/linux_input_sys/liblinux_input_sys/android_x86_64_rlib_rlib-std_apex10000/liblinux_input_sys.rlib prebuiltlibs/external/crosvm/linux_input_sys/liblinux_input_sys/android_x86_64_rlib_rlib-std_apex10000/liblinux_input_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/gpu_display/libgpu_display/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/gpu_display/libgpu_display/android_x86_64_rlib_rlib-std_apex10000/libgpu_display.rlib prebuiltlibs/external/crosvm/gpu_display/libgpu_display/android_x86_64_rlib_rlib-std_apex10000/libgpu_display.rlib
mkdir -p prebuiltlibs/external/crosvm/net_sys/libnet_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/net_sys/libnet_sys/android_x86_64_rlib_rlib-std_apex10000/libnet_sys.rlib prebuiltlibs/external/crosvm/net_sys/libnet_sys/android_x86_64_rlib_rlib-std_apex10000/libnet_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/net_util/libnet_util/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/net_util/libnet_util/android_x86_64_rlib_rlib-std_apex10000/libnet_util.rlib prebuiltlibs/external/crosvm/net_util/libnet_util/android_x86_64_rlib_rlib-std_apex10000/libnet_util.rlib
mkdir -p prebuiltlibs/external/crosvm/power_monitor/libpower_monitor/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/power_monitor/libpower_monitor/android_x86_64_rlib_rlib-std_apex10000/libpower_monitor.rlib prebuiltlibs/external/crosvm/power_monitor/libpower_monitor/android_x86_64_rlib_rlib-std_apex10000/libpower_monitor.rlib
mkdir -p prebuiltlibs/external/crosvm/resources/libresources/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/resources/libresources/android_x86_64_rlib_rlib-std_apex10000/libresources.rlib prebuiltlibs/external/crosvm/resources/libresources/android_x86_64_rlib_rlib-std_apex10000/libresources.rlib
mkdir -p prebuiltlibs/external/crosvm/usb_sys/libusb_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/usb_sys/libusb_sys/android_x86_64_rlib_rlib-std_apex10000/libusb_sys.rlib prebuiltlibs/external/crosvm/usb_sys/libusb_sys/android_x86_64_rlib_rlib-std_apex10000/libusb_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/usb_util/libusb_util/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/usb_util/libusb_util/android_x86_64_rlib_rlib-std_apex10000/libusb_util.rlib prebuiltlibs/external/crosvm/usb_util/libusb_util/android_x86_64_rlib_rlib-std_apex10000/libusb_util.rlib
mkdir -p prebuiltlibs/external/crosvm/vfio_sys/libvfio_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/vfio_sys/libvfio_sys/android_x86_64_rlib_rlib-std_apex10000/libvfio_sys.rlib prebuiltlibs/external/crosvm/vfio_sys/libvfio_sys/android_x86_64_rlib_rlib-std_apex10000/libvfio_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/virtio_sys/libvirtio_sys/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/virtio_sys/libvirtio_sys/android_x86_64_rlib_rlib-std_apex10000/libvirtio_sys.rlib prebuiltlibs/external/crosvm/virtio_sys/libvirtio_sys/android_x86_64_rlib_rlib-std_apex10000/libvirtio_sys.rlib
mkdir -p prebuiltlibs/external/crosvm/vm_memory/libvm_memory/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/vm_memory/libvm_memory/android_x86_64_rlib_rlib-std_apex10000/libvm_memory.rlib prebuiltlibs/external/crosvm/vm_memory/libvm_memory/android_x86_64_rlib_rlib-std_apex10000/libvm_memory.rlib
mkdir -p prebuiltlibs/external/crosvm/disk/libdisk/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/disk/libdisk/android_x86_64_rlib_rlib-std_apex10000/libdisk.rlib prebuiltlibs/external/crosvm/disk/libdisk/android_x86_64_rlib_rlib-std_apex10000/libdisk.rlib
mkdir -p prebuiltlibs/external/crosvm/kernel_loader/libkernel_loader/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/kernel_loader/libkernel_loader/android_x86_64_rlib_rlib-std_apex10000/libkernel_loader.rlib prebuiltlibs/external/crosvm/kernel_loader/libkernel_loader/android_x86_64_rlib_rlib-std_apex10000/libkernel_loader.rlib
mkdir -p prebuiltlibs/external/crosvm/kvm/libkvm/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/kvm/libkvm/android_x86_64_rlib_rlib-std_apex10000/libkvm.rlib prebuiltlibs/external/crosvm/kvm/libkvm/android_x86_64_rlib_rlib-std_apex10000/libkvm.rlib
mkdir -p prebuiltlibs/external/crosvm/hypervisor/libhypervisor/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/hypervisor/libhypervisor/android_x86_64_rlib_rlib-std_apex10000/libhypervisor.rlib prebuiltlibs/external/crosvm/hypervisor/libhypervisor/android_x86_64_rlib_rlib-std_apex10000/libhypervisor.rlib
mkdir -p prebuiltlibs/external/crosvm/vhost/libvhost/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/crosvm/vhost/libvhost/android_x86_64_rlib_rlib-std_apex10000/libvhost.rlib prebuiltlibs/external/crosvm/vhost/libvhost/android_x86_64_rlib_rlib-std_apex10000/libvhost.rlib

printf "rust_prebuilt_library {\n  name: \"libcros_async\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"cros_async\",\n  rustlibs: [\"libasync_task\",\"libdata_model\",\"libfutures\",\"libintrusive_collections\",\"libio_uring\",\"liblibc\",\"libpin_utils\",\"libslab\",\"libsync_rust\",\"libsys_util\",\"libsyscall_defines\",\"libthiserror\"],\n  proc_macros: [\"libasync_trait\",\"libpaste\"],\n  multiple_variants: true,\n  rlib: {\n    srcs: [\"libcros_async.rlib\"],\n  },\n  dylib: {\n    srcs: [\"libcros_async.dylib.so\"],\n  },\n}\n" >> prebuiltlibs/external/crosvm/cros_async/Android.bp
printf "rust_prebuilt_library {\n  name: \"libbase_rust\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  stem: \"libbase\",\n  host_supported: true,\n  crate_name: \"base\",\n  rustlibs: [\"libcros_async\",\"libdata_model\",\"liblibc\",\"libserde\",\"libserde_json\",\"libsmallvec\",\"libsync_rust\",\"libsys_util\",\"libthiserror\"],\n  multiple_variants: true,\n  rlib: {\n    srcs: [\"libbase_rust.rlib\"],\n  },\n  dylib: {\n    srcs: [\"libbase_rust.dylib.so\"],\n  },\n}\n" >> prebuiltlibs/external/crosvm/base/Android.bp
printf "rust_prebuilt_library {\n  name: \"libfuse_rust\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  stem: \"libfuse\",\n  host_supported: true,\n  crate_name: \"fuse\",\n  rustlibs: [\"libbase_rust\",\"libbitflags\",\"libdata_model\",\"liblibc\",\"libthiserror\"],\n  proc_macros: [\"libenumn\"],\n  multiple_variants: true,\n  rlib: {\n    srcs: [\"libfuse_rust.rlib\"],\n  },\n  dylib: {\n    srcs: [\"libfuse_rust.dylib.so\"],\n  },\n}\n" >> prebuiltlibs/external/crosvm/fuse/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libkvm_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"kvm_sys\",\n  rustlibs: [\"libbase_rust\",\"libdata_model\",\"liblibc\"],\n  multiple_variants: true,\n  srcs: [\"libkvm_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/kvm_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"liblinux_input_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"linux_input_sys\",\n  rustlibs: [\"libbase_rust\",\"libdata_model\",\"liblibc\"],\n  multiple_variants: true,\n  srcs: [\"liblinux_input_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/linux_input_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libgpu_display\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n    host: {\n      shared_libs: [\"libwayland_client\"],\n    },\n    android: {\n      static_libs: [\"libwayland_client_static\",\"libffi\"],\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"gpu_display\",\n  rustlibs: [\"libbase_rust\",\"libdata_model\",\"liblibc\",\"liblinux_input_sys\"],\n  static_libs: [\"libdisplay_wl\"],\n  multiple_variants: true,\n  srcs: [\"libgpu_display.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/gpu_display/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libnet_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"net_sys\",\n  rustlibs: [\"libbase_rust\"],\n  multiple_variants: true,\n  srcs: [\"libnet_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/net_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libnet_util\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"net_util\",\n  rustlibs: [\"libbase_rust\",\"libdata_model\",\"liblibc\",\"libnet_sys\"],\n  multiple_variants: true,\n  srcs: [\"libnet_util.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/net_util/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libpower_monitor\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"power_monitor\",\n  rustlibs: [\"libbase_rust\"],\n  multiple_variants: true,\n  srcs: [\"libpower_monitor.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/power_monitor/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libresources\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"resources\",\n  rustlibs: [\"libbase_rust\",\"liblibc\",\"libserde\"],\n  multiple_variants: true,\n  srcs: [\"libresources.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/resources/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libusb_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"usb_sys\",\n  rustlibs: [\"libbase_rust\"],\n  multiple_variants: true,\n  srcs: [\"libusb_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/usb_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libusb_util\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"usb_util\",\n  rustlibs: [\"libassertions\",\"libbase_rust\",\"libdata_model\",\"liblibc\",\"libusb_sys\"],\n  proc_macros: [\"libremain\"],\n  multiple_variants: true,\n  srcs: [\"libusb_util.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/usb_util/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libvfio_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"vfio_sys\",\n  rustlibs: [\"libbase_rust\"],\n  multiple_variants: true,\n  srcs: [\"libvfio_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/vfio_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libvirtio_sys\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"virtio_sys\",\n  rustlibs: [\"libbase_rust\"],\n  multiple_variants: true,\n  srcs: [\"libvirtio_sys.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/virtio_sys/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libvm_memory\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"vm_memory\",\n  rustlibs: [\"libbase_rust\",\"libbitflags\",\"libcros_async\",\"libdata_model\",\"liblibc\"],\n  multiple_variants: true,\n  srcs: [\"libvm_memory.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/vm_memory/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libdisk\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"disk\",\n  features: [\"composite-disk\"],\n  rustlibs: [\"libbase_rust\",\"libcros_async\",\"libdata_model\",\"libfutures\",\"liblibc\",\"libprotobuf\",\"libprotos\",\"libtempfile\",\"libvm_memory\"],\n  proc_macros: [\"libasync_trait\",\"libremain\"],\n  multiple_variants: true,\n  srcs: [\"libdisk.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/disk/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libkernel_loader\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"kernel_loader\",\n  rustlibs: [\"libbase_rust\",\"liblibc\",\"libtempfile\",\"libvm_memory\"],\n  multiple_variants: true,\n  srcs: [\"libkernel_loader.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/kernel_loader/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libkvm\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"kvm\",\n  rustlibs: [\"libbase_rust\",\"libdata_model\",\"libkvm_sys\",\"liblibc\",\"libsync_rust\",\"libvm_memory\"],\n  multiple_variants: true,\n  srcs: [\"libkvm.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/kvm/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libhypervisor\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"hypervisor\",\n  rustlibs: [\"libbase_rust\",\"libbit_field\",\"libdata_model\",\"libdowncast_rs\",\"libkvm\",\"libkvm_sys\",\"liblibc\",\"libserde\",\"libsync_rust\",\"libvm_memory\"],\n  proc_macros: [\"libenumn\"],\n  multiple_variants: true,\n  srcs: [\"libhypervisor.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/hypervisor/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libvhost\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"vhost\",\n  rustlibs: [\"libassertions\",\"libbase_rust\",\"liblibc\",\"libnet_util\",\"libvirtio_sys\",\"libvm_memory\"],\n  multiple_variants: true,\n  srcs: [\"libvhost.rlib\"],\n}\n" >> prebuiltlibs/external/crosvm/vhost/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/external/crosvm/ninja && rsync -ar out/soong/ninja/external/crosvm/ prebuiltlibs/external/crosvm/ninja/external_crosvm-10
touch prebuiltlibs/external/crosvm/ninja/.find-ignore
tar cfJ external_crosvm-10.tar.xz -C prebuiltlibs/external/crosvm/ .
ls -l external_crosvm-10.tar.xz
end=`date +%s`
echo $((end-start))

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/external/libchromeos-rs/liblibchromeos/android_x86_64_rlib_rlib-std_apex10000/liblibchromeos.rlib \
  

mkdir -p prebuiltlibs/external/libchromeos-rs/liblibchromeos/android_x86_64_rlib_rlib-std_apex10000/ && mv out/soong/.intermediates/external/libchromeos-rs/liblibchromeos/android_x86_64_rlib_rlib-std_apex10000/liblibchromeos.rlib prebuiltlibs/external/libchromeos-rs/liblibchromeos/android_x86_64_rlib_rlib-std_apex10000/liblibchromeos.rlib

printf "rust_prebuilt_rlib {\n  name: \"liblibchromeos\",\n  edition: \"2018\",\n  target: {\n    linux_glibc_x86_64: {\n      enabled: true,\n      flags: [\"-L device/google/cuttlefish_vmm/x86_64-linux-gnu/bin/\"],\n    },\n    android64: {\n      compile_multilib: \"64\",\n      enabled: true,\n    },\n    linux_bionic_arm64: {\n      enabled: true,\n    },\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"//apex_available:platform\",\"com.android.virt\"],\n  host_supported: true,\n  crate_name: \"libchromeos\",\n  rustlibs: [\"libdata_model\",\"libfutures\",\"libintrusive_collections\",\"liblibc\",\"liblog_rust\",\"libprotobuf\"],\n  multiple_variants: true,\n  srcs: [\"liblibchromeos.rlib\"],\n}\n" >> prebuiltlibs/external/libchromeos-rs/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/external/libchromeos-rs/ninja && rsync -ar out/soong/ninja/external/libchromeos-rs/ prebuiltlibs/external/libchromeos-rs/ninja/external_libchromeos-rs-10
touch prebuiltlibs/external/libchromeos-rs/ninja/.find-ignore
tar cfJ external_libchromeos-rs-10.tar.xz -C prebuiltlibs/external/libchromeos-rs/ .
ls -l external_libchromeos-rs-10.tar.xz
end=`date +%s`
echo $((end-start))

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/external/rust/crates/grpcio/libgrpcio/android_x86_64_rlib_rlib-std/libgrpcio.rlib \
  out/soong/.intermediates/external/rust/crates/grpcio/libgrpcio/android_x86_x86_64_rlib_rlib-std/libgrpcio.rlib \
  

mkdir -p prebuiltlibs/external/rust/crates/grpcio/libgrpcio/android_x86_64_rlib_rlib-std/ && mv out/soong/.intermediates/external/rust/crates/grpcio/libgrpcio/android_x86_64_rlib_rlib-std/libgrpcio.rlib prebuiltlibs/external/rust/crates/grpcio/libgrpcio/android_x86_64_rlib_rlib-std/libgrpcio.rlib
mkdir -p prebuiltlibs/external/rust/crates/grpcio/libgrpcio/android_x86_x86_64_rlib_rlib-std/ && mv out/soong/.intermediates/external/rust/crates/grpcio/libgrpcio/android_x86_x86_64_rlib_rlib-std/libgrpcio.rlib prebuiltlibs/external/rust/crates/grpcio/libgrpcio/android_x86_x86_64_rlib_rlib-std/libgrpcio.rlib

printf "rust_prebuilt_rlib {\n  name: \"libgrpcio\",\n  host_supported: true,\n  crate_name: \"grpcio\",\n  edition: \"2018\",\n  features: [\"protobuf\",\"protobuf-codec\"],\n  rustlibs: [\"libfutures\",\"libgrpcio_sys\",\"liblibc\",\"liblog_rust\",\"libparking_lot\",\"libprotobuf\"],\n  multiple_variants: true,\n  srcs: [\"libgrpcio.rlib\"],\n}\n" >> prebuiltlibs/external/rust/crates/grpcio/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/external/rust/crates/grpcio/ninja && rsync -ar out/soong/ninja/external/rust/crates/grpcio/ prebuiltlibs/external/rust/crates/grpcio/ninja/external_rust_crates_grpcio-10
touch prebuiltlibs/external/rust/crates/grpcio/ninja/.find-ignore
tar cfJ external_rust_crates_grpcio-10.tar.xz -C prebuiltlibs/external/rust/crates/grpcio/ .
ls -l external_rust_crates_grpcio-10.tar.xz
end=`date +%s`
echo $((end-start))

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/external/rust/crates/rusqlite/librusqlite/android_x86_64_rlib_rlib-std/librusqlite.rlib \
  

mkdir -p prebuiltlibs/external/rust/crates/rusqlite/librusqlite/android_x86_64_rlib_rlib-std/ && mv out/soong/.intermediates/external/rust/crates/rusqlite/librusqlite/android_x86_64_rlib_rlib-std/librusqlite.rlib prebuiltlibs/external/rust/crates/rusqlite/librusqlite/android_x86_64_rlib_rlib-std/librusqlite.rlib

printf "rust_prebuilt_rlib {\n  name: \"librusqlite\",\n  host_supported: true,\n  crate_name: \"rusqlite\",\n  edition: \"2018\",\n  features: [\"modern_sqlite\"],\n  rustlibs: [\"libbitflags\",\"libfallible_iterator\",\"libfallible_streaming_iterator\",\"libhashlink\",\"liblibsqlite3_sys\",\"libmemchr\",\"libsmallvec\"],\n  multiple_variants: true,\n  srcs: [\"librusqlite.rlib\"],\n}\n" >> prebuiltlibs/external/rust/crates/rusqlite/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/external/rust/crates/rusqlite/ninja && rsync -ar out/soong/ninja/external/rust/crates/rusqlite/ prebuiltlibs/external/rust/crates/rusqlite/ninja/external_rust_crates_rusqlite-10
touch prebuiltlibs/external/rust/crates/rusqlite/ninja/.find-ignore
tar cfJ external_rust_crates_rusqlite-10.tar.xz -C prebuiltlibs/external/rust/crates/rusqlite/ .
ls -l external_rust_crates_rusqlite-10.tar.xz
end=`date +%s`
echo $((end-start))

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey \
  out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a \
  out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a \
  out/soong/.intermediates/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a \
  out/soong/.intermediates/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a \
  out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so \
  out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a \
  out/soong/.intermediates/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so \
  out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so \
  out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a \
  out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so \
  out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a \
  out/soong/.intermediates/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a \
  

mkdir -p prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/ && mv out/soong/.intermediates/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/services/audiopolicy/engine/config/include/ prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/include
mkdir -p prebuiltlibs/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so prebuiltlibs/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioprocessing/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libaudioprocessing/include/ prebuiltlibs/frameworks/av/media/libaudioprocessing/include
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libdatasource/include/ prebuiltlibs/frameworks/av/media/libdatasource/include
mkdir -p prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libmediaplayerservice/datasource/include/ prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/include
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libmedia/include/ prebuiltlibs/frameworks/av/media/libmedia/include
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a
mkdir -p prebuiltlibs/frameworks/av/media/ndk/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/ndk/include/ prebuiltlibs/frameworks/av/media/ndk/include
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a
mkdir -p prebuiltlibs/frameworks/av/media/utils/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/utils/include/ prebuiltlibs/frameworks/av/media/utils/include
mkdir -p prebuiltlibs/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/ && mv out/soong/.intermediates/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver prebuiltlibs/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libaaudio/src/ prebuiltlibs/frameworks/av/media/libaaudio/src/
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so
mkdir -p prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so
mkdir -p prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/mediametrics/android_x86_64/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics prebuiltlibs/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/bufferpool/2.0/include/ prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/bufferpool/2.0/include/ prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libstagefright/mpeg2ts/ prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libstagefright/mpeg2ts/ prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/

printf "cc_prebuilt_binary {\n  name: \"android.hardware.drm@1.4-service.clearkey\",\n  vendor: true,\n  relative_install_path: \"hw\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"android.hardware.drm@1.3\",\"android.hardware.drm@1.4\",\"libbase\",\"libbinder\",\"libcrypto\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libprotobuf-cpp-lite\",\"libutils\"],\n  sanitize: {\n    integer_overflow: true,\n  },\n  init_rc: [\"android.hardware.drm@1.4-service.clearkey.rc\"],\n  vintf_fragments: [\"manifest_android.hardware.drm@1.4-service.clearkey.xml\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"android.hardware.drm@1.4-service.clearkey\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaudiopolicyengine_config\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libmedia_helper\",\"libxml2\",\"libutils\",\"liblog\",\"libcutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiopolicyengine_config.a\"],\n}\n" >> prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudioprocessing\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libaudioutils\",\"libcutils\",\"liblog\",\"libutils\",\"libaudiohal\",\"libsonic\",\"libvibrator\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  whole_static_libs: [\"libaudioprocessing_base\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudioprocessing.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudioprocessing/Android.bp
printf "cc_prebuilt_library {\n  name: \"libdatasource\",\n  header_libs: [\"libstagefright_headers\",\"media_ndk_headers\"],\n  export_header_lib_headers: [\"libstagefright_headers\",\"media_ndk_headers\"],\n  shared_libs: [\"liblog\",\"libcutils\",\"libutils\",\"libstagefright_foundation\",\"libdl\"],\n  static_libs: [\"libc_malloc_debug_backtrace\",\"libmedia_midiiowrapper\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  prebuilt_aidl: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libdatasource.a\"],\n  },\n  shared: {\n    srcs: [\"libdatasource.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libdatasource/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libplayerservice_datasource\",\n  shared_libs: [\"libdatasource\",\"libdrmframework\",\"liblog\",\"libutils\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libplayerservice_datasource.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_webm\",\n  sanitize: {\n    misc_undefined: [\"signed-integer-overflow\",\"unsigned-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libdatasource\",\"libstagefright_foundation\",\"libutils\",\"liblog\",\"framework-permission-aidl-cpp\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_webm.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/webm/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmedia_codeclist\",\n  shared_libs: [\"android.hardware.media.omx@1.0\",\"libbinder\",\"liblog\",\"libstagefright_foundation\",\"libutils\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmedia_codeclist.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libmedia/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmediadrmmetrics_full\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"libbase\",\"liblog\",\"libmediametrics\",\"libprotobuf-cpp-full\",\"libstagefright_foundation\",\"libutils\"],\n  prebuilt_proto: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmediadrmmetrics_full.so\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/libmediadrm/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmediadrmmetrics_lite\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"liblog\",\"libmediametrics\",\"libprotobuf-cpp-lite\",\"libutils\"],\n  prebuilt_proto: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmediadrmmetrics_lite.so\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/libmediadrm/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediandk_utils\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediandk_utils.a\"],\n  },\n  shared: {\n    srcs: [\"libmediandk_utils.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/ndk/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediautils\",\n  static_libs: [\"libc_malloc_debug_backtrace\",\"libbatterystats_aidl\",\"libprocessinfoservice_aidl\"],\n  shared_libs: [\"libaudioclient_aidl_conversion\",\"libaudioutils\",\"libbinder\",\"libcutils\",\"liblog\",\"libutils\",\"libhidlbase\",\"libpermission\",\"android.hardware.graphics.bufferqueue@1.0\",\"android.hidl.token@1.0-utils\"],\n  export_static_lib_headers: [\"libbatterystats_aidl\"],\n  logtags: [\"EventLogTags.logtags\"],\n  export_shared_lib_headers: [\"libpermission\"],\n  export_include_dirs: [\"include\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediautils.a\"],\n  },\n  shared: {\n    srcs: [\"libmediautils.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/utils/Android.bp
printf "cc_prebuilt_binary {\n  name: \"drmserver\",\n  shared_libs: [\"libmediametrics\",\"libmediautils\",\"libcutils\",\"libutils\",\"liblog\",\"libbinder\",\"libdl\",\"libdrmframeworkcommon\",\"libselinux\",\"libstagefright_foundation\"],\n  compile_multilib: \"prefer32\",\n  init_rc: [\"drmserver.rc\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"drmserver\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/drmserver/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaudioclient\",\n  shared_libs: [\"audioclient-types-aidl-cpp\",\"audioflinger-aidl-cpp\",\"audiopolicy-aidl-cpp\",\"audiopolicy-types-aidl-cpp\",\"av-types-aidl-cpp\",\"capture_state_listener-aidl-cpp\",\"libaudioclient_aidl_conversion\",\"libaudiofoundation\",\"libaudioutils\",\"libaudiopolicy\",\"libaudiomanager\",\"libbinder\",\"libcutils\",\"libdl\",\"liblog\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"libnblog\",\"libprocessgroup\",\"libshmemcompat\",\"libutils\",\"libvibrator\",\"framework-permission-aidl-cpp\"],\n  export_shared_lib_headers: [\"audioflinger-aidl-cpp\",\"audiopolicy-aidl-cpp\",\"framework-permission-aidl-cpp\",\"libbinder\"],\n  header_libs: [\"libaudioclient_headers\"],\n  export_header_lib_headers: [\"libaudioclient_headers\"],\n  export_static_lib_headers: [\"effect-aidl-cpp\",\"shared-file-region-aidl-cpp\"],\n  static_libs: [\"effect-aidl-cpp\",\"libc_malloc_debug_backtrace\",\"shared-file-region-aidl-cpp\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n  },\n  prebuilt_aidl: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaudioclient.a\"],\n  },\n  shared: {\n    srcs: [\"libaudioclient.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaudioclient/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaaudio_internal\",\n  export_include_dirs: [\".\"],\n  header_libs: [\"libaaudio_headers\"],\n  export_header_lib_headers: [\"libaaudio_headers\"],\n  export_shared_lib_headers: [\"framework-permission-aidl-cpp\"],\n  shared_libs: [\"libaudioclient\",\"libaudioutils\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"liblog\",\"libcutils\",\"libutils\",\"libbinder\",\"framework-permission-aidl-cpp\",\"aaudio-aidl-cpp\",\"libaudioclient_aidl_conversion\"],\n  sanitize: {\n    integer_overflow: true,\n    misc_undefined: [\"bounds\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaaudio_internal.a\"],\n  },\n  shared: {\n    srcs: [\"libaaudio_internal.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaaudio/src/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaaudio\",\n  header_libs: [\"libaaudio_headers\"],\n  export_header_lib_headers: [\"libaaudio_headers\"],\n  version_script: \"libaaudio.map.txt\",\n  shared_libs: [\"libaaudio_internal\",\"libaudioclient\",\"libaudioutils\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"liblog\",\"libcutils\",\"libutils\",\"libbinder\",\"libpermission\"],\n  sanitize: {\n    integer_overflow: true,\n    misc_undefined: [\"bounds\"],\n  },\n  stubs: {\n    symbol_file: \"libaaudio.map.txt\",\n    versions: [\"28\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaaudio.a\"],\n  },\n  shared: {\n    srcs: [\"libaaudio.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaaudio/src/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@4.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@4.0\",\"android.hardware.audio.common@4.0-util\",\"android.hardware.audio.effect@4.0\",\"android.hardware.audio.effect@4.0-util\",\"android.hardware.audio@4.0\",\"android.hardware.audio@4.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@4.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@5.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@5.0\",\"android.hardware.audio.common@5.0-util\",\"android.hardware.audio.effect@5.0\",\"android.hardware.audio.effect@5.0-util\",\"android.hardware.audio@5.0\",\"android.hardware.audio@5.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@5.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@6.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@6.0\",\"android.hardware.audio.common@6.0-util\",\"android.hardware.audio.effect@6.0\",\"android.hardware.audio.effect@6.0-util\",\"android.hardware.audio@6.0\",\"android.hardware.audio@6.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@6.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@7.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@7.0\",\"android.hardware.audio.common@7.0-util\",\"android.hardware.audio.effect@7.0\",\"android.hardware.audio.effect@7.0-util\",\"android.hardware.audio@7.0\",\"android.hardware.audio@7.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@7.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmedialogservice\",\n  shared_libs: [\"libaudioutils\",\"libbinder\",\"liblog\",\"libmediautils\",\"libnblog\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmedialogservice.a\"],\n  },\n  shared: {\n    srcs: [\"libmedialogservice.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/services/medialog/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediametricsservice\",\n  shared_libs: [\"mediametricsservice-aidl-cpp\",\"libbase\",\"libbinder\",\"libcutils\",\"liblog\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"libmemunreachable\",\"libprotobuf-cpp-lite\",\"libstagefright_foundation\",\"libstatslog\",\"libstatspull\",\"libstatssocket\",\"libutils\"],\n  export_shared_lib_headers: [\"libstatspull\",\"libstatssocket\"],\n  static_libs: [\"libplatformprotos\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediametricsservice.a\"],\n  },\n  shared: {\n    srcs: [\"libmediametricsservice.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/services/mediametrics/Android.bp
printf "cc_prebuilt_binary {\n  name: \"mediametrics\",\n  shared_libs: [\"libbinder\",\"liblog\",\"libmediametricsservice\",\"libmediautils\",\"libutils\",\"mediametricsservice-aidl-cpp\"],\n  init_rc: [\"mediametrics.rc\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"mediametrics\"],\n}\n" >> prebuiltlibs/frameworks/av/services/mediametrics/Android.bp
printf "cc_prebuilt_library {\n  name: \"libstagefright_bufferpool@2.0\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libcutils\",\"libfmq\",\"libhidlbase\",\"liblog\",\"libutils\",\"android.hardware.media.bufferpool@2.0\"],\n  export_shared_lib_headers: [\"libfmq\",\"android.hardware.media.bufferpool@2.0\"],\n  vendor_available: true,\n  double_loadable: true,\n  vndk: {\n    enabled: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libstagefright_bufferpool@2.0.a\"],\n  },\n  shared: {\n    srcs: [\"libstagefright_bufferpool@2.0.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/bufferpool/2.0/Android.bp
printf "cc_prebuilt_library {\n  name: \"libstagefright_bufferpool@2.0.1\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libcutils\",\"libfmq\",\"libhidlbase\",\"liblog\",\"libutils\",\"android.hardware.media.bufferpool@2.0\"],\n  export_shared_lib_headers: [\"libfmq\",\"android.hardware.media.bufferpool@2.0\"],\n  vendor_available: true,\n  min_sdk_version: \"29\",\n  double_loadable: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libstagefright_bufferpool@2.0.1.a\"],\n  },\n  shared: {\n    srcs: [\"libstagefright_bufferpool@2.0.1.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/bufferpool/2.0/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_mpeg2support\",\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libhidlmemory\",\"android.hardware.cas.native@1.0\",\"android.hidl.memory@1.0\",\"android.hidl.allocator@1.0\",\"libcrypto\"],\n  export_include_dirs: [\".\"],\n  whole_static_libs: [\"libstagefright_metadatautils\"],\n  min_sdk_version: \"29\",\n  host_supported: true,\n  target: {\n    darwin: {\n      enabled: false,\n    },\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_mpeg2support.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_mpeg2support_nocrypto\",\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libhidlmemory\",\"android.hardware.cas.native@1.0\",\"android.hidl.memory@1.0\",\"android.hidl.allocator@1.0\"],\n  export_include_dirs: [\".\"],\n  whole_static_libs: [\"libstagefright_metadatautils\"],\n  min_sdk_version: \"29\",\n  host_supported: true,\n  target: {\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"com.android.media\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_mpeg2support_nocrypto.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/frameworks/av/ninja && rsync -ar out/soong/ninja/frameworks/av/ prebuiltlibs/frameworks/av/ninja/frameworks_av-10
touch prebuiltlibs/frameworks/av/ninja/.find-ignore
tar cfJ frameworks_av-10.tar.xz -C prebuiltlibs/frameworks/av/ .
ls -l frameworks_av-10.tar.xz
end=`date +%s`
echo $((end-start))

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/system/extras/bootctl/bootctl/android_x86_64/bootctl \
  out/soong/.intermediates/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so \
  out/soong/.intermediates/system/extras/partition_tools/lpdump/android_x86_64/lpdump \
  out/soong/.intermediates/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib \
  out/soong/.intermediates/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf \
  out/soong/.intermediates/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/liblibprofcollectd.dylib.so \
  out/soong/.intermediates/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl \
  out/soong/.intermediates/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd \
  

mkdir -p prebuiltlibs/system/extras/bootctl/bootctl/android_x86_64/ && mv out/soong/.intermediates/system/extras/bootctl/bootctl/android_x86_64/bootctl prebuiltlibs/system/extras/bootctl/bootctl/android_x86_64/bootctl
mkdir -p prebuiltlibs/system/extras/partition_tools/liblpdump/android_x86_64_shared/ && mv out/soong/.intermediates/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so prebuiltlibs/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so
mkdir -p prebuiltlibs/system/extras/partition_tools/lpdump/android_x86_64/ && mv out/soong/.intermediates/system/extras/partition_tools/lpdump/android_x86_64/lpdump prebuiltlibs/system/extras/partition_tools/lpdump/android_x86_64/lpdump
mkdir -p prebuiltlibs/system/extras/partition_tools/lpdumpd/android_x86_64/ && mv out/soong/.intermediates/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd prebuiltlibs/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf/android_x86_64_static/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a prebuiltlibs/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib
mkdir -p prebuiltlibs/system/extras/simpleperf/simpleperf/android_x86_64/ && mv out/soong/.intermediates/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf prebuiltlibs/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf
mkdir -p prebuiltlibs/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/ && mv out/soong/.intermediates/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/liblibprofcollectd.dylib.so prebuiltlibs/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/libprofcollectd.dylib.so
mkdir -p prebuiltlibs/system/extras/profcollectd/profcollectctl/android_x86_64/ && mv out/soong/.intermediates/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl prebuiltlibs/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl
mkdir -p prebuiltlibs/system/extras/profcollectd/profcollectd/android_x86_64/ && mv out/soong/.intermediates/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd prebuiltlibs/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd

printf "cc_prebuilt_binary {\n  name: \"bootctl\",\n  shared_libs: [\"android.hardware.boot@1.0\",\"android.hardware.boot@1.1\",\"android.hardware.boot@1.2\",\"libhidlbase\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"bootctl\"],\n}\n" >> prebuiltlibs/system/extras/bootctl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"liblpdump\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n    android: {\n      shared_libs: [\"libcutils\",\"libfs_mgr\"],\n    },\n  },\n  host_supported: true,\n  shared_libs: [\"libbase\",\"liblog\",\"liblp\",\"libprotobuf-cpp-full\"],\n  static_libs: [\"libjsonpbparse\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"liblpdump.so\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_binary {\n  name: \"lpdump\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n    android: {\n      shared_libs: [\"liblpdump_interface-cpp\",\"libbinder\",\"libutils\"],\n      required: [\"lpdumpd\"],\n    },\n    host: {\n      shared_libs: [\"liblpdump\"],\n    },\n  },\n  host_supported: true,\n  shared_libs: [\"libbase\",\"liblog\",\"liblp\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"lpdump\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_binary {\n  name: \"lpdumpd\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n  },\n  init_rc: [\"lpdumpd.rc\"],\n  shared_libs: [\"libbase\",\"libbinder\",\"liblog\",\"liblp\",\"liblpdump\",\"liblpdump_interface-cpp\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"lpdumpd\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libsimpleperf\",\n  target: {\n    linux: {\n      static_libs: [\"libunwindstack\",\"libcutils\",\"libprocinfo\",\"libevent\",\"libc++fs\",\"libdexfile_support\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    host: {\n      stl: \"libc++_static\",\n    },\n    android: {\n      static_libs: [\"libc\"],\n    },\n  },\n  static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\",\"liblzma\",\"libz\",\"libziparchive\",\"libsimpleperf_etm_decoder\",\"libbase\",\"liblog\",\"libutils\",\"libprotobuf-cpp-lite\",\"libopencsd_decoder\",\"libbuildversion\"],\n  host_supported: true,\n  use_version_lib: false,\n  compile_multilib: \"both\",\n  shared_libs: [\"libprotobuf-cpp-lite\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libsimpleperf.a\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "cc_prebuilt_library {\n  name: \"libsimpleperf_profcollect\",\n  target: {\n    host: {\n      static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    linux: {\n      shared_libs: [\"libcutils\",\"libevent\",\"liblog\",\"libprocinfo\",\"libunwindstack\"],\n      static_libs: [\"libc++fs\",\"libdexfile_support\"],\n    },\n  },\n  host_supported: false,\n  shared_libs: [\"libbase\",\"liblzma\",\"libprotobuf-cpp-lite\",\"libziparchive\",\"libLLVM_android\"],\n  static_libs: [\"libsimpleperf_etm_decoder\",\"libopencsd_decoder\",\"libsimpleperf\"],\n  use_version_lib: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libsimpleperf_profcollect.a\"],\n  },\n  shared: {\n    srcs: [\"libsimpleperf_profcollect.so\"],\n  },\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libsimpleperf_profcollect_rust\",\n  crate_name: \"simpleperf_profcollect\",\n  rlibs: [\"libsimpleperf_profcollect_bindgen\"],\n  shared_libs: [\"libsimpleperf_profcollect\"],\n  visibility: [\"//system/extras/profcollectd:__subpackages__\"],\n  multiple_variants: true,\n  srcs: [\"libsimpleperf_profcollect_rust.rlib\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "cc_prebuilt_binary {\n  name: \"simpleperf\",\n  target: {\n    host: {\n      static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    linux: {\n      shared_libs: [\"libcutils\",\"libevent\",\"liblog\",\"libprocinfo\",\"libunwindstack\"],\n      static_libs: [\"libc++fs\",\"libdexfile_support\"],\n    },\n    android: {\n      shared_libs: [\"libLLVM_android\"],\n    },\n  },\n  host_supported: false,\n  shared_libs: [\"libbase\",\"liblzma\",\"libprotobuf-cpp-lite\",\"libziparchive\"],\n  use_version_lib: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"simpleperf\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "rust_prebuilt_library {\n  name: \"libprofcollectd\",\n  stem: \"liblibprofcollectd\",\n  crate_name: \"libprofcollectd\",\n  rustlibs: [\"profcollectd_aidl_interface-rust\",\"libandroid_logger\",\"libanyhow\",\"libbinder_rs\",\"libchrono\",\"liblazy_static\",\"liblog_rust\",\"libmacaddr\",\"librand\",\"libserde\",\"libserde_json\",\"libuuid\",\"libzip\"],\n  rlibs: [\"libprofcollect_libflags_rust\",\"libprofcollect_libbase_rust\",\"libsimpleperf_profcollect_rust\"],\n  shared_libs: [\"libsimpleperf_profcollect\"],\n  multiple_variants: true,\n  srcs: [\"libprofcollectd.dylib.so\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/libprofcollectd/Android.bp
printf "cc_prebuilt_binary {\n  name: \"profcollectctl\",\n  stl: \"none\",\n  prefer: true,\n  multiple_variants: true,\n  srcs: [\"profcollectctl\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/Android.bp
printf "cc_prebuilt_binary {\n  name: \"profcollectd\",\n  stl: \"none\",\n  prefer: true,\n  multiple_variants: true,\n  srcs: [\"profcollectd\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/system/extras/ninja && rsync -ar out/soong/ninja/system/extras/ prebuiltlibs/system/extras/ninja/system_extras-10
touch prebuiltlibs/system/extras/ninja/.find-ignore
tar cfJ system_extras-10.tar.xz -C prebuiltlibs/system/extras/ .
ls -l system_extras-10.tar.xz
end=`date +%s`
echo $((end-start))


du -ah -d1 out/soong |sort -h
