source $GITHUB_WORKSPACE/envsetup.sh
df -h

sed -i 's/name: "libLLVM_android.prebuilt",$/name: "libLLVM_android",/g' prebuiltlibs/external/llvm/Android.bp
GOROOT=$TOP/prebuilts/go/linux-x86 $GITHUB_WORKSPACE/soong_ui --make-mode --skip-ninja --skip-kati --skip-soong-tests --skip-write-modules -j1 TARGET_PRODUCT=aosp_x86_64 TARGET_BUILD_VARIANT=eng ALLOW_MISSING_DEPENDENCIES=true BUILD_BROKEN_DISABLE_BAZEL=1 nothing

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/system/extras/bootctl/bootctl/android_x86_64/bootctl \
  out/soong/.intermediates/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so \
  out/soong/.intermediates/system/extras/partition_tools/lpdump/android_x86_64/lpdump \
  out/soong/.intermediates/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a \
  out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib \
  out/soong/.intermediates/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf \
  out/soong/.intermediates/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/liblibprofcollectd.dylib.so \
  out/soong/.intermediates/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl \
  out/soong/.intermediates/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd \
  

mkdir -p prebuiltlibs/system/extras/bootctl/bootctl/android_x86_64/ && mv out/soong/.intermediates/system/extras/bootctl/bootctl/android_x86_64/bootctl prebuiltlibs/system/extras/bootctl/bootctl/android_x86_64/bootctl
mkdir -p prebuiltlibs/system/extras/partition_tools/liblpdump/android_x86_64_shared/ && mv out/soong/.intermediates/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so prebuiltlibs/system/extras/partition_tools/liblpdump/android_x86_64_shared/liblpdump.so
mkdir -p prebuiltlibs/system/extras/partition_tools/lpdump/android_x86_64/ && mv out/soong/.intermediates/system/extras/partition_tools/lpdump/android_x86_64/lpdump prebuiltlibs/system/extras/partition_tools/lpdump/android_x86_64/lpdump
mkdir -p prebuiltlibs/system/extras/partition_tools/lpdumpd/android_x86_64/ && mv out/soong/.intermediates/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd prebuiltlibs/system/extras/partition_tools/lpdumpd/android_x86_64/lpdumpd
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf/android_x86_64_static/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a prebuiltlibs/system/extras/simpleperf/libsimpleperf/android_x86_64_static/libsimpleperf.a
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_shared/libsimpleperf_profcollect.so
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect/android_x86_64_static/libsimpleperf_profcollect.a
mkdir -p prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/ && mv out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib prebuiltlibs/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_x86_64_rlib_dylib-std/libsimpleperf_profcollect_rust.rlib
mkdir -p prebuiltlibs/system/extras/simpleperf/simpleperf/android_x86_64/ && mv out/soong/.intermediates/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf prebuiltlibs/system/extras/simpleperf/simpleperf/android_x86_64/simpleperf
mkdir -p prebuiltlibs/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/ && mv out/soong/.intermediates/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/liblibprofcollectd.dylib.so prebuiltlibs/system/extras/profcollectd/libprofcollectd/libprofcollectd/android_x86_64_dylib/libprofcollectd.dylib.so
mkdir -p prebuiltlibs/system/extras/profcollectd/profcollectctl/android_x86_64/ && mv out/soong/.intermediates/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl prebuiltlibs/system/extras/profcollectd/profcollectctl/android_x86_64/profcollectctl
mkdir -p prebuiltlibs/system/extras/profcollectd/profcollectd/android_x86_64/ && mv out/soong/.intermediates/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd prebuiltlibs/system/extras/profcollectd/profcollectd/android_x86_64/profcollectd

printf "cc_prebuilt_binary {\n  name: \"bootctl\",\n  shared_libs: [\"android.hardware.boot@1.0\",\"android.hardware.boot@1.1\",\"android.hardware.boot@1.2\",\"libhidlbase\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"bootctl\"],\n}\n" >> prebuiltlibs/system/extras/bootctl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"liblpdump\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n    android: {\n      shared_libs: [\"libcutils\",\"libfs_mgr\"],\n    },\n  },\n  host_supported: true,\n  shared_libs: [\"libbase\",\"liblog\",\"liblp\",\"libprotobuf-cpp-full\"],\n  static_libs: [\"libjsonpbparse\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"liblpdump.so\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_binary {\n  name: \"lpdump\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n    android: {\n      shared_libs: [\"liblpdump_interface-cpp\",\"libbinder\",\"libutils\"],\n      required: [\"lpdumpd\"],\n    },\n    host: {\n      shared_libs: [\"liblpdump\"],\n    },\n  },\n  host_supported: true,\n  shared_libs: [\"libbase\",\"liblog\",\"liblp\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"lpdump\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_binary {\n  name: \"lpdumpd\",\n  target: {\n    linux_bionic: {\n      enabled: true,\n    },\n  },\n  init_rc: [\"lpdumpd.rc\"],\n  shared_libs: [\"libbase\",\"libbinder\",\"liblog\",\"liblp\",\"liblpdump\",\"liblpdump_interface-cpp\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"lpdumpd\"],\n}\n" >> prebuiltlibs/system/extras/partition_tools/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libsimpleperf\",\n  target: {\n    linux: {\n      static_libs: [\"libunwindstack\",\"libcutils\",\"libprocinfo\",\"libevent\",\"libc++fs\",\"libdexfile_support\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    host: {\n      stl: \"libc++_static\",\n    },\n    android: {\n      static_libs: [\"libc\"],\n    },\n  },\n  static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\",\"liblzma\",\"libz\",\"libziparchive\",\"libsimpleperf_etm_decoder\",\"libbase\",\"liblog\",\"libutils\",\"libprotobuf-cpp-lite\",\"libopencsd_decoder\",\"libbuildversion\"],\n  host_supported: true,\n  use_version_lib: false,\n  compile_multilib: \"both\",\n  shared_libs: [\"libprotobuf-cpp-lite\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libsimpleperf.a\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "cc_prebuilt_library {\n  name: \"libsimpleperf_profcollect\",\n  target: {\n    host: {\n      static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    linux: {\n      shared_libs: [\"libcutils\",\"libevent\",\"liblog\",\"libprocinfo\",\"libunwindstack\"],\n      static_libs: [\"libc++fs\",\"libdexfile_support\"],\n    },\n  },\n  host_supported: false,\n  shared_libs: [\"libbase\",\"liblzma\",\"libprotobuf-cpp-lite\",\"libziparchive\",\"libLLVM_android\"],\n  static_libs: [\"libsimpleperf_etm_decoder\",\"libopencsd_decoder\",\"libsimpleperf\"],\n  use_version_lib: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libsimpleperf_profcollect.a\"],\n  },\n  shared: {\n    srcs: [\"libsimpleperf_profcollect.so\"],\n  },\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "rust_prebuilt_rlib {\n  name: \"libsimpleperf_profcollect_rust\",\n  crate_name: \"simpleperf_profcollect\",\n  rlibs: [\"libsimpleperf_profcollect_bindgen\"],\n  shared_libs: [\"libsimpleperf_profcollect\"],\n  visibility: [\"//system/extras/profcollectd:__subpackages__\"],\n  multiple_variants: true,\n  srcs: [\"libsimpleperf_profcollect_rust.rlib\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "cc_prebuilt_binary {\n  name: \"simpleperf\",\n  target: {\n    host: {\n      static_libs: [\"libLLVMObject\",\"libLLVMBitReader\",\"libLLVMMC\",\"libLLVMMCParser\",\"libLLVMCore\",\"libLLVMSupport\"],\n    },\n    darwin: {\n    },\n    windows: {\n      enabled: true,\n    },\n    linux: {\n      shared_libs: [\"libcutils\",\"libevent\",\"liblog\",\"libprocinfo\",\"libunwindstack\"],\n      static_libs: [\"libc++fs\",\"libdexfile_support\"],\n    },\n    android: {\n      shared_libs: [\"libLLVM_android\"],\n    },\n  },\n  host_supported: false,\n  shared_libs: [\"libbase\",\"liblzma\",\"libprotobuf-cpp-lite\",\"libziparchive\"],\n  use_version_lib: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"simpleperf\"],\n}\n" >> prebuiltlibs/system/extras/simpleperf/Android.bp
printf "rust_prebuilt_library {\n  name: \"libprofcollectd\",\n  stem: \"liblibprofcollectd\",\n  crate_name: \"libprofcollectd\",\n  rustlibs: [\"profcollectd_aidl_interface-rust\",\"libandroid_logger\",\"libanyhow\",\"libbinder_rs\",\"libchrono\",\"liblazy_static\",\"liblog_rust\",\"libmacaddr\",\"librand\",\"libserde\",\"libserde_json\",\"libuuid\",\"libzip\"],\n  rlibs: [\"libprofcollect_libflags_rust\",\"libprofcollect_libbase_rust\",\"libsimpleperf_profcollect_rust\"],\n  shared_libs: [\"libsimpleperf_profcollect\"],\n  multiple_variants: true,\n  srcs: [\"libprofcollectd.dylib.so\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/libprofcollectd/Android.bp
printf "cc_prebuilt_binary {\n  name: \"profcollectctl\",\n  stl: \"none\",\n  prefer: true,\n  multiple_variants: true,\n  srcs: [\"profcollectctl\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/Android.bp
printf "cc_prebuilt_binary {\n  name: \"profcollectd\",\n  stl: \"none\",\n  prefer: true,\n  multiple_variants: true,\n  srcs: [\"profcollectd\"],\n}\n" >> prebuiltlibs/system/extras/profcollectd/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/system/extras/ninja && rsync -ar out/soong/ninja/system/extras/ prebuiltlibs/system/extras/ninja/system_extras-10
touch prebuiltlibs/system/extras/ninja/.find-ignore
tar cfJ system_extras-10.tar.xz -C prebuiltlibs/system/extras/ .
ls -l system_extras-10.tar.xz
end=`date +%s`
echo $((end-start))


du -ah -d1 out/soong |sort -h
