source $GITHUB_WORKSPACE/envsetup.sh
df -h


GOROOT=$TOP/prebuilts/go/linux-x86 $GITHUB_WORKSPACE/soong_ui --make-mode --skip-ninja --skip-kati --skip-soong-tests --skip-write-modules -j1 TARGET_PRODUCT=aosp_x86_64 TARGET_BUILD_VARIANT=eng ALLOW_MISSING_DEPENDENCIES=true BUILD_BROKEN_DISABLE_BAZEL=1 nothing

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_64_shared_apex31/libartpalette.so \
  out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_64_static_apex31/libartpalette.a \
  out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_x86_64_shared_apex31/libartpalette.so \
  out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_x86_64_static_apex31/libartpalette.a \
  out/soong/.intermediates/art/libartpalette/libartpalette/linux_glibc_x86_64_static/libartpalette.a \
  out/soong/.intermediates/art/libartbase/libartbase/android_x86_64_shared_apex31/libartbase.so \
  out/soong/.intermediates/art/libartbase/libartbase/android_x86_64_static_apex31/libartbase.a \
  out/soong/.intermediates/art/libartbase/libartbase/android_x86_x86_64_shared_apex31/libartbase.so \
  out/soong/.intermediates/art/libartbase/libartbase/android_x86_x86_64_static_apex31/libartbase.a \
  out/soong/.intermediates/art/libartbase/libartbase/linux_glibc_x86_64_static/libartbase.a \
  out/soong/.intermediates/art/libelffile/libelffile/android_x86_64_static_lto-thin_apex31/libelffile.a \
  out/soong/.intermediates/art/libelffile/libelffile/android_x86_x86_64_static_lto-thin_apex31/libelffile.a \
  out/soong/.intermediates/art/libelffile/libelffile/linux_glibc_x86_64_static/libelffile.a \
  out/soong/.intermediates/art/odrefresh/libodrstatslog/android_x86_64_static_lto-thin_apex31/libodrstatslog.a \
  out/soong/.intermediates/art/odrefresh/libodrstatslog/android_x86_x86_64_static_lto-thin_apex31/libodrstatslog.a \
  out/soong/.intermediates/art/odrefresh/libodrstatslog/linux_glibc_x86_64_static/libodrstatslog.a \
  out/soong/.intermediates/art/libartbase/libartbased/linux_glibc_x86_64_static/libartbased.a \
  out/soong/.intermediates/art/libelffile/libelffiled/linux_glibc_x86_64_static/libelffiled.a \
  out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_64_shared_apex31/libdexfile.so \
  out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_64_static_apex31/libdexfile.a \
  out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_x86_64_shared_apex31/libdexfile.so \
  out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_x86_64_static_apex31/libdexfile.a \
  out/soong/.intermediates/art/libdexfile/libdexfile/linux_glibc_x86_64_static/libdexfile.a \
  out/soong/.intermediates/art/dexdump/dexdump/linux_glibc_x86_64/dexdump \
  out/soong/.intermediates/art/dexdump/dexdump/android_x86_64_apex31/dexdump \
  out/soong/.intermediates/art/dexlist/dexlist/android_x86_64_apex31/dexlist \
  out/soong/.intermediates/art/tools/hiddenapi/hiddenapi/linux_glibc_x86_64/hiddenapi \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static_apex31/libdexfile_support.a \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex31/libdexfile_support.a \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static_apex10000/libdexfile_support.a \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex10000/libdexfile_support.a \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static/libdexfile_support.a \
  out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static/libdexfile_support.a \
  out/soong/.intermediates/art/tools/veridex/veridex/linux_glibc_x86_64/veridex \
  out/soong/.intermediates/art/libdexfile/libdexfiled/linux_glibc_x86_64_static/libdexfiled.a \
  out/soong/.intermediates/art/libprofile/libprofile/android_x86_64_shared_apex31/libprofile.so \
  out/soong/.intermediates/art/libprofile/libprofile/android_x86_64_static_apex31/libprofile.a \
  out/soong/.intermediates/art/libprofile/libprofile/android_x86_x86_64_shared_apex31/libprofile.so \
  out/soong/.intermediates/art/libprofile/libprofile/android_x86_x86_64_static_apex31/libprofile.a \
  out/soong/.intermediates/art/libprofile/libprofile/linux_glibc_x86_64_static/libprofile.a \
  out/soong/.intermediates/art/dexlayout/libart-dexlayout/linux_glibc_x86_64_static/libart-dexlayout.a \
  out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_64_shared_apex31/libart-dexlayout.so \
  out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_64_static_apex31/libart-dexlayout.a \
  out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_x86_64_shared_apex31/libart-dexlayout.so \
  out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_x86_64_static_apex31/libart-dexlayout.a \
  out/soong/.intermediates/art/libprofile/libprofiled/linux_glibc_x86_64_static/libprofiled.a \
  out/soong/.intermediates/art/dexlayout/libartd-dexlayout/linux_glibc_x86_64_static/libartd-dexlayout.a \
  out/soong/.intermediates/art/profman/libprofman_static/linux_glibc_x86_64_static/libprofman_static.a \
  out/soong/.intermediates/art/profman/profman/linux_glibc_x86_64/profman \
  out/soong/.intermediates/art/profman/profman/android_x86_64_apex31/profman \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_shared_apex31/libnativeloader.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_static_apex31/libnativeloader.a \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_apex31/libnativeloader.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_static_apex31/libnativeloader.a \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/linux_glibc_x86_64_static/libnativeloader.a \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_shared_current/libnativeloader.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_current/libnativeloader.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_64_shared/libnativeloader_lazy.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_64_static/libnativeloader_lazy.a \
  out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_shared/libnativeloader_lazy.so \
  out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_static/libnativeloader_lazy.a \
  

mkdir -p prebuiltlibs/art/libartpalette/libartpalette/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_64_shared_apex31/libartpalette.so prebuiltlibs/art/libartpalette/libartpalette/android_x86_64_shared_apex31/libartpalette.so
mkdir -p prebuiltlibs/art/libartpalette/libartpalette/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_64_static_apex31/libartpalette.a prebuiltlibs/art/libartpalette/libartpalette/android_x86_64_static_apex31/libartpalette.a
mkdir -p prebuiltlibs/art/libartpalette/libartpalette/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_x86_64_shared_apex31/libartpalette.so prebuiltlibs/art/libartpalette/libartpalette/android_x86_x86_64_shared_apex31/libartpalette.so
mkdir -p prebuiltlibs/art/libartpalette/libartpalette/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libartpalette/libartpalette/android_x86_x86_64_static_apex31/libartpalette.a prebuiltlibs/art/libartpalette/libartpalette/android_x86_x86_64_static_apex31/libartpalette.a
mkdir -p prebuiltlibs/art/libartpalette/libartpalette/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libartpalette/libartpalette/linux_glibc_x86_64_static/libartpalette.a prebuiltlibs/art/libartpalette/libartpalette/linux_glibc_x86_64_static/libartpalette.a
mkdir -p prebuiltlibs/art/libartpalette/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libartpalette/include/ prebuiltlibs/art/libartpalette/include
mkdir -p prebuiltlibs/art/libartbase/libartbase/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libartbase/libartbase/android_x86_64_shared_apex31/libartbase.so prebuiltlibs/art/libartbase/libartbase/android_x86_64_shared_apex31/libartbase.so
mkdir -p prebuiltlibs/art/libartbase/libartbase/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libartbase/libartbase/android_x86_64_static_apex31/libartbase.a prebuiltlibs/art/libartbase/libartbase/android_x86_64_static_apex31/libartbase.a
mkdir -p prebuiltlibs/art/libartbase/libartbase/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libartbase/libartbase/android_x86_x86_64_shared_apex31/libartbase.so prebuiltlibs/art/libartbase/libartbase/android_x86_x86_64_shared_apex31/libartbase.so
mkdir -p prebuiltlibs/art/libartbase/libartbase/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libartbase/libartbase/android_x86_x86_64_static_apex31/libartbase.a prebuiltlibs/art/libartbase/libartbase/android_x86_x86_64_static_apex31/libartbase.a
mkdir -p prebuiltlibs/art/libartbase/libartbase/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libartbase/libartbase/linux_glibc_x86_64_static/libartbase.a prebuiltlibs/art/libartbase/libartbase/linux_glibc_x86_64_static/libartbase.a
mkdir -p prebuiltlibs/art/libartbase/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libartbase/ prebuiltlibs/art/libartbase/
mkdir -p prebuiltlibs/art/libelffile/libelffile/android_x86_64_static_lto-thin_apex31/ && mv out/soong/.intermediates/art/libelffile/libelffile/android_x86_64_static_lto-thin_apex31/libelffile.a prebuiltlibs/art/libelffile/libelffile/android_x86_64_static_lto-thin_apex31/libelffile.a
mkdir -p prebuiltlibs/art/libelffile/libelffile/android_x86_x86_64_static_lto-thin_apex31/ && mv out/soong/.intermediates/art/libelffile/libelffile/android_x86_x86_64_static_lto-thin_apex31/libelffile.a prebuiltlibs/art/libelffile/libelffile/android_x86_x86_64_static_lto-thin_apex31/libelffile.a
mkdir -p prebuiltlibs/art/libelffile/libelffile/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libelffile/libelffile/linux_glibc_x86_64_static/libelffile.a prebuiltlibs/art/libelffile/libelffile/linux_glibc_x86_64_static/libelffile.a
mkdir -p prebuiltlibs/art/libelffile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libelffile/ prebuiltlibs/art/libelffile/
mkdir -p prebuiltlibs/art/odrefresh/libodrstatslog/android_x86_64_static_lto-thin_apex31/ && mv out/soong/.intermediates/art/odrefresh/libodrstatslog/android_x86_64_static_lto-thin_apex31/libodrstatslog.a prebuiltlibs/art/odrefresh/libodrstatslog/android_x86_64_static_lto-thin_apex31/libodrstatslog.a
mkdir -p prebuiltlibs/art/odrefresh/libodrstatslog/android_x86_x86_64_static_lto-thin_apex31/ && mv out/soong/.intermediates/art/odrefresh/libodrstatslog/android_x86_x86_64_static_lto-thin_apex31/libodrstatslog.a prebuiltlibs/art/odrefresh/libodrstatslog/android_x86_x86_64_static_lto-thin_apex31/libodrstatslog.a
mkdir -p prebuiltlibs/art/odrefresh/libodrstatslog/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/odrefresh/libodrstatslog/linux_glibc_x86_64_static/libodrstatslog.a prebuiltlibs/art/odrefresh/libodrstatslog/linux_glibc_x86_64_static/libodrstatslog.a
mkdir -p prebuiltlibs/art/odrefresh/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/odrefresh/include/ prebuiltlibs/art/odrefresh/include
mkdir -p prebuiltlibs/art/libartbase/libartbased/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libartbase/libartbased/linux_glibc_x86_64_static/libartbased.a prebuiltlibs/art/libartbase/libartbased/linux_glibc_x86_64_static/libartbased.a
mkdir -p prebuiltlibs/art/libartbase/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libartbase/ prebuiltlibs/art/libartbase/
mkdir -p prebuiltlibs/art/libelffile/libelffiled/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libelffile/libelffiled/linux_glibc_x86_64_static/libelffiled.a prebuiltlibs/art/libelffile/libelffiled/linux_glibc_x86_64_static/libelffiled.a
mkdir -p prebuiltlibs/art/libelffile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libelffile/ prebuiltlibs/art/libelffile/
mkdir -p prebuiltlibs/art/libdexfile/libdexfile/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_64_shared_apex31/libdexfile.so prebuiltlibs/art/libdexfile/libdexfile/android_x86_64_shared_apex31/libdexfile.so
mkdir -p prebuiltlibs/art/libdexfile/libdexfile/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_64_static_apex31/libdexfile.a prebuiltlibs/art/libdexfile/libdexfile/android_x86_64_static_apex31/libdexfile.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_x86_64_shared_apex31/libdexfile.so prebuiltlibs/art/libdexfile/libdexfile/android_x86_x86_64_shared_apex31/libdexfile.so
mkdir -p prebuiltlibs/art/libdexfile/libdexfile/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile/android_x86_x86_64_static_apex31/libdexfile.a prebuiltlibs/art/libdexfile/libdexfile/android_x86_x86_64_static_apex31/libdexfile.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libdexfile/libdexfile/linux_glibc_x86_64_static/libdexfile.a prebuiltlibs/art/libdexfile/libdexfile/linux_glibc_x86_64_static/libdexfile.a
mkdir -p prebuiltlibs/art/libdexfile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libdexfile/ prebuiltlibs/art/libdexfile/
mkdir -p prebuiltlibs/art/dexdump/dexdump/linux_glibc_x86_64/ && mv out/soong/.intermediates/art/dexdump/dexdump/linux_glibc_x86_64/dexdump prebuiltlibs/art/dexdump/dexdump/linux_glibc_x86_64/dexdump
mkdir -p prebuiltlibs/art/dexdump/dexdump/android_x86_64_apex31/ && mv out/soong/.intermediates/art/dexdump/dexdump/android_x86_64_apex31/dexdump prebuiltlibs/art/dexdump/dexdump/android_x86_64_apex31/dexdump
mkdir -p prebuiltlibs/art/dexlist/dexlist/android_x86_64_apex31/ && mv out/soong/.intermediates/art/dexlist/dexlist/android_x86_64_apex31/dexlist prebuiltlibs/art/dexlist/dexlist/android_x86_64_apex31/dexlist
mkdir -p prebuiltlibs/art/tools/hiddenapi/hiddenapi/linux_glibc_x86_64/ && mv out/soong/.intermediates/art/tools/hiddenapi/hiddenapi/linux_glibc_x86_64/hiddenapi prebuiltlibs/art/tools/hiddenapi/hiddenapi/linux_glibc_x86_64/hiddenapi
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static_apex31/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static_apex31/libdexfile_support.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex31/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex31/libdexfile_support.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static_apex10000/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static_apex10000/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static_apex10000/libdexfile_support.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex10000/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex10000/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static_apex10000/libdexfile_support.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_64_static/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_64_static/libdexfile_support.a
mkdir -p prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static/ && mv out/soong/.intermediates/art/libdexfile/libdexfile_support/android_x86_x86_64_static/libdexfile_support.a prebuiltlibs/art/libdexfile/libdexfile_support/android_x86_x86_64_static/libdexfile_support.a
mkdir -p prebuiltlibs/art/tools/veridex/veridex/linux_glibc_x86_64/ && mv out/soong/.intermediates/art/tools/veridex/veridex/linux_glibc_x86_64/veridex prebuiltlibs/art/tools/veridex/veridex/linux_glibc_x86_64/veridex
mkdir -p prebuiltlibs/art/libdexfile/libdexfiled/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libdexfile/libdexfiled/linux_glibc_x86_64_static/libdexfiled.a prebuiltlibs/art/libdexfile/libdexfiled/linux_glibc_x86_64_static/libdexfiled.a
mkdir -p prebuiltlibs/art/libdexfile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libdexfile/ prebuiltlibs/art/libdexfile/
mkdir -p prebuiltlibs/art/libprofile/libprofile/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libprofile/libprofile/android_x86_64_shared_apex31/libprofile.so prebuiltlibs/art/libprofile/libprofile/android_x86_64_shared_apex31/libprofile.so
mkdir -p prebuiltlibs/art/libprofile/libprofile/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libprofile/libprofile/android_x86_64_static_apex31/libprofile.a prebuiltlibs/art/libprofile/libprofile/android_x86_64_static_apex31/libprofile.a
mkdir -p prebuiltlibs/art/libprofile/libprofile/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libprofile/libprofile/android_x86_x86_64_shared_apex31/libprofile.so prebuiltlibs/art/libprofile/libprofile/android_x86_x86_64_shared_apex31/libprofile.so
mkdir -p prebuiltlibs/art/libprofile/libprofile/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libprofile/libprofile/android_x86_x86_64_static_apex31/libprofile.a prebuiltlibs/art/libprofile/libprofile/android_x86_x86_64_static_apex31/libprofile.a
mkdir -p prebuiltlibs/art/libprofile/libprofile/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libprofile/libprofile/linux_glibc_x86_64_static/libprofile.a prebuiltlibs/art/libprofile/libprofile/linux_glibc_x86_64_static/libprofile.a
mkdir -p prebuiltlibs/art/libprofile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libprofile/ prebuiltlibs/art/libprofile/
mkdir -p prebuiltlibs/art/dexlayout/libart-dexlayout/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/dexlayout/libart-dexlayout/linux_glibc_x86_64_static/libart-dexlayout.a prebuiltlibs/art/dexlayout/libart-dexlayout/linux_glibc_x86_64_static/libart-dexlayout.a
mkdir -p prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_64_shared_apex31/libart-dexlayout.so prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_64_shared_apex31/libart-dexlayout.so
mkdir -p prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_64_static_apex31/libart-dexlayout.a prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_64_static_apex31/libart-dexlayout.a
mkdir -p prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_x86_64_shared_apex31/libart-dexlayout.so prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_x86_64_shared_apex31/libart-dexlayout.so
mkdir -p prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/dexlayout/libart-dexlayout/android_x86_x86_64_static_apex31/libart-dexlayout.a prebuiltlibs/art/dexlayout/libart-dexlayout/android_x86_x86_64_static_apex31/libart-dexlayout.a
mkdir -p prebuiltlibs/art/dexlayout/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/dexlayout/ prebuiltlibs/art/dexlayout/
mkdir -p prebuiltlibs/art/libprofile/libprofiled/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libprofile/libprofiled/linux_glibc_x86_64_static/libprofiled.a prebuiltlibs/art/libprofile/libprofiled/linux_glibc_x86_64_static/libprofiled.a
mkdir -p prebuiltlibs/art/libprofile/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/libprofile/ prebuiltlibs/art/libprofile/
mkdir -p prebuiltlibs/art/dexlayout/libartd-dexlayout/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/dexlayout/libartd-dexlayout/linux_glibc_x86_64_static/libartd-dexlayout.a prebuiltlibs/art/dexlayout/libartd-dexlayout/linux_glibc_x86_64_static/libartd-dexlayout.a
mkdir -p prebuiltlibs/art/dexlayout/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" art/dexlayout/ prebuiltlibs/art/dexlayout/
mkdir -p prebuiltlibs/art/profman/libprofman_static/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/profman/libprofman_static/linux_glibc_x86_64_static/libprofman_static.a prebuiltlibs/art/profman/libprofman_static/linux_glibc_x86_64_static/libprofman_static.a
mkdir -p prebuiltlibs/art/profman/profman/linux_glibc_x86_64/ && mv out/soong/.intermediates/art/profman/profman/linux_glibc_x86_64/profman prebuiltlibs/art/profman/profman/linux_glibc_x86_64/profman
mkdir -p prebuiltlibs/art/profman/profman/android_x86_64_apex31/ && mv out/soong/.intermediates/art/profman/profman/android_x86_64_apex31/profman prebuiltlibs/art/profman/profman/android_x86_64_apex31/profman
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_shared_apex31/libnativeloader.so prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_shared_apex31/libnativeloader.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_static_apex31/libnativeloader.a prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_static_apex31/libnativeloader.a
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_apex31/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_apex31/libnativeloader.so prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_apex31/libnativeloader.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_static_apex31/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_static_apex31/libnativeloader.a prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_static_apex31/libnativeloader.a
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/linux_glibc_x86_64_static/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/linux_glibc_x86_64_static/libnativeloader.a prebuiltlibs/art/libnativeloader/libnativeloader/linux_glibc_x86_64_static/libnativeloader.a
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_shared_current/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_64_shared_current/libnativeloader.so prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_64_shared_current/libnativeloader.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_current/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_current/libnativeloader.so prebuiltlibs/art/libnativeloader/libnativeloader/android_x86_x86_64_shared_current/libnativeloader.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_64_shared/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_64_shared/libnativeloader_lazy.so prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_64_shared/libnativeloader_lazy.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_64_static/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_64_static/libnativeloader_lazy.a prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_64_static/libnativeloader_lazy.a
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_shared/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_shared/libnativeloader_lazy.so prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_shared/libnativeloader_lazy.so
mkdir -p prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_static/ && mv out/soong/.intermediates/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_static/libnativeloader_lazy.a prebuiltlibs/art/libnativeloader/libnativeloader_lazy/android_x86_x86_64_static/libnativeloader_lazy.a

printf "cc_prebuilt_library {\n  name: \"libartpalette\",\n  visibility: [\"//prebuilts/module_sdk/art/current/host-exports\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      runtime_libs: [\"libartpalette-system\"],\n      shared_libs: [\"liblog\"],\n      version_script: \"libartpalette.map.txt\",\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\",\"libbase_headers\"],\n      shared: {\n        shared_libs: [\"libbase\",\"liblog\"],\n      },\n      version_script: \"libartpalette.map.txt\",\n    },\n    darwin: {\n      enabled: true,\n      header_libs: [\"libbase_headers\"],\n      static_libs: [\"libbase\",\"liblog\"],\n    },\n    windows: {\n      enabled: true,\n      header_libs: [\"libbase_headers\"],\n      static_libs: [\"libbase\",\"liblog\"],\n    },\n    host: {\n    },\n    linux_glibc: {\n      header_libs: [\"libbase_headers\"],\n      shared: {\n        shared_libs: [\"libbase\",\"liblog\"],\n      },\n      version_script: \"libartpalette.map.txt\",\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\"include\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\",\"com.android.runtime\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libartpalette.a\"],\n  },\n  shared: {\n    srcs: [\"libartpalette.so\"],\n  },\n}\n" >> prebuiltlibs/art/libartpalette/Android.bp
printf "cc_prebuilt_library {\n  name: \"libartbase\",\n  visibility: [\"//prebuilts/module_sdk/art/current/host-exports\",\"//packages/modules/NetworkStack/tests:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      static_libs: [\"libziparchive\"],\n      shared_libs: [\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libziparchive\",\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_static_lib_headers: [\"libbase\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    host: {\n    },\n    not_windows: {\n      static: {\n      },\n      shared_libs: [\"libziparchive\",\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    android_arm: {\n      strip: {\n        keep_symbols_and_debug_frame: true,\n      },\n      pgo: {\n        profile_file: \"art/art_arm_arm64.profdata\",\n      },\n    },\n    android_arm64: {\n      strip: {\n        keep_symbols: true,\n      },\n      pgo: {\n        profile_file: \"art/art_arm_arm64.profdata\",\n      },\n    },\n    android_x86: {\n      strip: {\n        keep_symbols: true,\n      },\n      pgo: {\n        profile_file: \"art/art_x86_x86_64.profdata\",\n      },\n    },\n    android_x86_64: {\n      strip: {\n        keep_symbols: true,\n      },\n      pgo: {\n        profile_file: \"art/art_x86_x86_64.profdata\",\n      },\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  pgo: {\n    sampling: true,\n  },\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  shared_libs: [\"libbase\",\"libziparchive\"],\n  export_shared_lib_headers: [\"libbase\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libartbase.a\"],\n  },\n  shared: {\n    srcs: [\"libartbase.so\"],\n  },\n}\n" >> prebuiltlibs/art/libartbase/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libelffile\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libbase\",\"liblzma\",\"libartbase\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libelffile.a\"],\n}\n" >> prebuiltlibs/art/libelffile/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libodrstatslog\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libstatssocket\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libartbase\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libodrstatslog.a\"],\n}\n" >> prebuiltlibs/art/odrefresh/Android.bp
printf "cc_prebuilt_library {\n  name: \"libartbased\",\n  visibility: [\"//art:__subpackages__\"],\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      static_libs: [\"libziparchive\"],\n      shared_libs: [\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    host: {\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libziparchive\",\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_static_lib_headers: [\"libbase\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    not_windows: {\n      static: {\n      },\n      shared_libs: [\"libziparchive\",\"libz\",\"liblog\",\"libartpalette\",\"libbase\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n  },\n  min_sdk_version: \"S\",\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  apex_available: [\"com.android.art.debug\"],\n  shared_libs: [\"libbase\",\"libziparchive\"],\n  export_shared_lib_headers: [\"libbase\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libartbased.a\"],\n}\n" >> prebuiltlibs/art/libartbase/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libelffiled\",\n  visibility: [\"//art:__subpackages__\"],\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    host: {\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n  },\n  min_sdk_version: \"S\",\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libbase\",\"liblzma\",\"libartbased\"],\n  apex_available: [\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libelffiled.a\"],\n}\n" >> prebuiltlibs/art/libelffile/Android.bp
printf "cc_prebuilt_library {\n  name: \"libdexfile\",\n  visibility: [\"//external/perfetto\",\"//system/core/debuggerd\",\"//system/extras/simpleperf\",\"//system/unwinding/libunwindstack\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      static_libs: [\"libziparchive\"],\n      shared_libs: [\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbase\"],\n      export_shared_lib_headers: [\"libbase\",\"libartbase\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libziparchive\",\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbase\"],\n      export_static_lib_headers: [\"libbase\",\"libartbase\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    host: {\n    },\n    not_windows: {\n      shared_libs: [\"libziparchive\",\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbase\"],\n      export_shared_lib_headers: [\"libbase\",\"libartbase\"],\n    },\n    android_arm: {\n      strip: {\n        keep_symbols_and_debug_frame: true,\n      },\n    },\n    android_arm64: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n    android_x86: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n    android_x86_64: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  header_libs: [\"jni_headers\",\"libdexfile_external_headers\"],\n  export_header_lib_headers: [\"jni_headers\",\"libdexfile_external_headers\"],\n  export_include_dirs: [\".\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  stubs: {\n    symbol_file: \"libdexfile.map.txt\",\n    versions: [\"1\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libdexfile.a\"],\n  },\n  shared: {\n    srcs: [\"libdexfile.so\"],\n  },\n}\n" >> prebuiltlibs/art/libdexfile/Android.bp
printf "cc_prebuilt_binary {\n  name: \"dexdump\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libdexfile\",\"libartbase\",\"libbase\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n    },\n    host: {\n      stl: \"libc++_static\",\n      static_libs: [\"libdexfile\",\"libartbase\",\"libbase\",\"libartpalette\",\"liblog\",\"libz\",\"libziparchive\"],\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"dexdump\"],\n}\n" >> prebuiltlibs/art/dexdump/Android.bp
printf "cc_prebuilt_binary {\n  name: \"dexlist\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  shared_libs: [\"libdexfile\",\"libartbase\",\"libbase\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"dexlist\"],\n}\n" >> prebuiltlibs/art/dexlist/Android.bp
printf "cc_prebuilt_binary {\n  name: \"hiddenapi\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n      compile_multilib: \"64\",\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  device_supported: false,\n  stl: \"c++_static\",\n  static_libs: [\"libbase\"],\n  whole_static_libs: [\"libbase\",\"libartpalette\",\"liblog\",\"libz\",\"libziparchive\",\"libartbase\",\"libdexfile\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"hiddenapi\"],\n}\n" >> prebuiltlibs/art/tools/hiddenapi/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libdexfile_support\",\n  visibility: [\"//visibility:public\"],\n  host_supported: true,\n  runtime_libs: [\"libdexfile\"],\n  shared_libs: [\"liblog\",\"libbase\"],\n  header_libs: [\"libdexfile_external_headers\"],\n  export_header_lib_headers: [\"libdexfile_external_headers\"],\n  apex_available: [\"//apex_available:platform\",\"com.android.art\",\"com.android.art.debug\",\"com.android.media\",\"com.android.media.swcodec\",\"com.android.runtime\"],\n  min_sdk_version: \"S\",\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libdexfile_support.a\"],\n}\n" >> prebuiltlibs/art/libdexfile/Android.bp
printf "cc_prebuilt_binary {\n  name: \"veridex\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  stl: \"libc++_static\",\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"veridex\"],\n}\n" >> prebuiltlibs/art/tools/veridex/Android.bp
printf "cc_prebuilt_library {\n  name: \"libdexfiled\",\n  visibility: [\"//art:__subpackages__\"],\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      static_libs: [\"libziparchive\"],\n      shared_libs: [\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbased\"],\n      export_shared_lib_headers: [\"libbase\",\"libartbased\"],\n    },\n    host: {\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libziparchive\",\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbased\"],\n      export_static_lib_headers: [\"libbase\",\"libartbased\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    not_windows: {\n      shared_libs: [\"libziparchive\",\"libz\",\"libartpalette\",\"liblog\",\"libbase\",\"libartbased\"],\n      export_shared_lib_headers: [\"libbase\",\"libartbased\"],\n    },\n  },\n  min_sdk_version: \"S\",\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  host_supported: true,\n  header_libs: [\"jni_headers\",\"libdexfile_external_headers\"],\n  export_header_lib_headers: [\"jni_headers\",\"libdexfile_external_headers\"],\n  export_include_dirs: [\".\"],\n  apex_available: [\"com.android.art.debug\",\"com.android.art\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libdexfiled.a\"],\n}\n" >> prebuiltlibs/art/libdexfile/Android.bp
printf "cc_prebuilt_library {\n  name: \"libprofile\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libartpalette\",\"libbase\",\"libz\",\"libartbase\",\"libdexfile\"],\n      static_libs: [\"libziparchive\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libartpalette\",\"libziparchive\",\"libz\",\"libbase\",\"libartbase\",\"libdexfile\"],\n      export_static_lib_headers: [\"libbase\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    host: {\n    },\n    not_windows: {\n      shared_libs: [\"libartpalette\",\"libziparchive\",\"libz\",\"libbase\",\"libartbase\",\"libdexfile\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    android_arm: {\n      strip: {\n        keep_symbols_and_debug_frame: true,\n      },\n    },\n    android_arm64: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n    android_x86: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n    android_x86_64: {\n      strip: {\n        keep_symbols: true,\n      },\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libbase\",\"libziparchive\"],\n  export_shared_lib_headers: [\"libbase\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libprofile.a\"],\n  },\n  shared: {\n    srcs: [\"libprofile.so\"],\n  },\n}\n" >> prebuiltlibs/art/libprofile/Android.bp
printf "cc_prebuilt_library {\n  name: \"libart-dexlayout\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libartpalette\",\"libbase\",\"libartbase\",\"libdexfile\",\"libprofile\"],\n      lto: {\n        thin: true,\n      },\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: true,\n      static_libs: [\"libartpalette\",\"libbase\",\"libartbase\",\"libdexfile\",\"libprofile\"],\n      shared: {\n        enabled: false,\n      },\n    },\n    host: {\n    },\n    not_windows: {\n      shared_libs: [\"libartpalette\",\"libbase\",\"libartbase\",\"libdexfile\",\"libprofile\"],\n    },\n    android_arm64: {\n      pgo: {\n        profile_file: \"art/dex2oat_arm_arm64.profdata\",\n      },\n    },\n    android_arm: {\n      pgo: {\n        profile_file: \"art/dex2oat_arm_arm64.profdata\",\n      },\n    },\n    android_x86_64: {\n      pgo: {\n        profile_file: \"art/dex2oat_x86_x86_64.profdata\",\n      },\n    },\n    android_x86: {\n      pgo: {\n        profile_file: \"art/dex2oat_x86_x86_64.profdata\",\n      },\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libz\"],\n  pgo: {\n    instrumentation: true,\n    benchmarks: [\"dex2oat\"],\n  },\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libart-dexlayout.a\"],\n  },\n  shared: {\n    srcs: [\"libart-dexlayout.so\"],\n  },\n}\n" >> prebuiltlibs/art/dexlayout/Android.bp
printf "cc_prebuilt_library {\n  name: \"libprofiled\",\n  visibility: [\"//art:__subpackages__\"],\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libartpalette\",\"libbase\",\"libz\",\"libartbased\",\"libdexfiled\"],\n      static_libs: [\"libziparchive\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n    host: {\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: false,\n      static_libs: [\"libartpalette\",\"libziparchive\",\"libz\",\"libbase\",\"libartbased\",\"libdexfiled\"],\n      export_static_lib_headers: [\"libbase\"],\n    },\n    not_windows: {\n      shared_libs: [\"libartpalette\",\"libziparchive\",\"libz\",\"libbase\",\"libartbased\",\"libdexfiled\"],\n      export_shared_lib_headers: [\"libbase\"],\n    },\n  },\n  min_sdk_version: \"S\",\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libbase\",\"libziparchive\"],\n  export_shared_lib_headers: [\"libbase\"],\n  apex_available: [\"com.android.art.debug\",\"com.android.art\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libprofiled.a\"],\n}\n" >> prebuiltlibs/art/libprofile/Android.bp
printf "cc_prebuilt_library {\n  name: \"libartd-dexlayout\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libartpalette\",\"libbase\",\"libartbased\",\"libdexfiled\",\"libprofiled\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n      static_libs: [\"libartpalette\",\"libbase\",\"libartbased\",\"libdexfiled\",\"libprofiled\"],\n    },\n    host: {\n    },\n    not_windows: {\n      shared_libs: [\"libartpalette\",\"libbase\",\"libartbased\",\"libdexfiled\",\"libprofiled\"],\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  export_include_dirs: [\".\"],\n  shared_libs: [\"libz\"],\n  apex_available: [\"com.android.art.debug\",\"com.android.art\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libartd-dexlayout.a\"],\n}\n" >> prebuiltlibs/art/dexlayout/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libprofman_static\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  whole_static_libs: [\"libbase\",\"libartpalette\",\"liblog\",\"libz\",\"libziparchive\",\"libartbase\",\"libdexfile\",\"libprofile\"],\n  device_supported: false,\n  host_supported: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libprofman_static.a\"],\n}\n" >> prebuiltlibs/art/profman/Android.bp
printf "cc_prebuilt_binary {\n  name: \"profman\",\n  visibility: [\"//art:__subpackages__\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      compile_multilib: \"first\",\n      shared_libs: [\"libbase\",\"libartbase\",\"libdexfile\",\"libprofile\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: true,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n      whole_static_libs: [\"libbase\"],\n      static_libs: [\"libprofman_static\"],\n      stl: \"c++_static\",\n    },\n  },\n  min_sdk_version: \"S\",\n  host_supported: true,\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"profman\"],\n}\n" >> prebuiltlibs/art/profman/Android.bp
printf "cc_prebuilt_library {\n  name: \"libnativeloader\",\n  visibility: [\"//frameworks/base/cmds/app_process\",\"//frameworks/base/native/webview/loader\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n      shared_libs: [\"libdl_android\"],\n      static_libs: [\"PlatformProperties\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n    linux_glibc_x86: {\n    },\n    linux_glibc_x86_64: {\n    },\n  },\n  min_sdk_version: \"S\",\n  header_libs: [\"libnativeloader-headers\"],\n  export_header_lib_headers: [\"libnativeloader-headers\"],\n  apex_available: [\"com.android.art\",\"com.android.art.debug\"],\n  host_supported: true,\n  shared_libs: [\"liblog\",\"libnativebridge\",\"libbase\"],\n  stubs: {\n    symbol_file: \"libnativeloader.map.txt\",\n    versions: [\"1\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libnativeloader.a\"],\n  },\n  shared: {\n    srcs: [\"libnativeloader.so\"],\n  },\n}\n" >> prebuiltlibs/art/libnativeloader/Android.bp
printf "cc_prebuilt_library {\n  name: \"libnativeloader_lazy\",\n  visibility: [\"//frameworks/base/core/jni\",\"//frameworks/native/opengl/libs\",\"//frameworks/native/vulkan/libvulkan\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  target: {\n    android: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    linux: {\n    },\n    linux_bionic: {\n      header_libs: [\"bionic_libc_platform_headers\"],\n    },\n    darwin: {\n      enabled: false,\n    },\n    windows: {\n      enabled: false,\n    },\n    host: {\n    },\n  },\n  min_sdk_version: \"S\",\n  header_libs: [\"libnativeloader-headers\"],\n  export_header_lib_headers: [\"libnativeloader-headers\"],\n  apex_available: [\"//apex_available:platform\",\"com.android.media\",\"com.android.media.swcodec\"],\n  host_supported: false,\n  runtime_libs: [\"libnativeloader\"],\n  shared_libs: [\"liblog\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libnativeloader_lazy.a\"],\n  },\n  shared: {\n    srcs: [\"libnativeloader_lazy.so\"],\n  },\n}\n" >> prebuiltlibs/art/libnativeloader/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/art/ninja && rsync -ar out/soong/ninja/art/ prebuiltlibs/art/ninja/art-8
touch prebuiltlibs/art/ninja/.find-ignore
tar cfJ art-8.tar.xz -C prebuiltlibs/art/ .
ls -l art-8.tar.xz
end=`date +%s`
echo $((end-start))


du -ah -d1 out/soong |sort -h
