source $GITHUB_WORKSPACE/envsetup.sh
df -h


sed -i 's/"libstagefright_metadatautils",$/"libstagefright_metadatautils",use_apex_name_macro: true,/g' prebuiltlibs/frameworks/av/media/libstagefright/Android.bp

GOROOT=$TOP/prebuilts/go/linux-x86 $GITHUB_WORKSPACE/soong_ui --make-mode --skip-ninja --skip-kati --skip-soong-tests --skip-write-modules -j1 TARGET_PRODUCT=aosp_x86_64 TARGET_BUILD_VARIANT=eng ALLOW_MISSING_DEPENDENCIES=true BUILD_BROKEN_DISABLE_BAZEL=1 nothing

start=`date +%s`
./prebuilts/build-tools/linux-x86/bin/ninja -f out/soong/build.ninja \
  out/soong/.intermediates/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey \
  out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a \
  out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a \
  out/soong/.intermediates/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so \
  out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a \
  out/soong/.intermediates/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a \
  out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so \
  out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so \
  out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so \
  out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so \
  out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a \
  out/soong/.intermediates/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so \
  out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so \
  out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so \
  out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so \
  out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so \
  out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a \
  out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so \
  out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a \
  out/soong/.intermediates/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so \
  out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a \
  out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a \
  

mkdir -p prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/ && mv out/soong/.intermediates/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/android.hardware.drm@1.4-service.clearkey/android_vendor.31_x86_64/android.hardware.drm@1.4-service.clearkey
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_64_static/libaudiopolicyengine_config.a
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/libaudiopolicyengine_config/android_x86_x86_64_static/libaudiopolicyengine_config.a
mkdir -p prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/services/audiopolicy/engine/config/include/ prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/include
mkdir -p prebuiltlibs/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so prebuiltlibs/frameworks/av/media/libaudioprocessing/libaudioprocessing/android_x86_64_shared/libaudioprocessing.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioprocessing/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libaudioprocessing/include/ prebuiltlibs/frameworks/av/media/libaudioprocessing/include
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_shared_cfi/libdatasource.so
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_64_static_cfi/libdatasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_shared_cfi/libdatasource.so
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a prebuiltlibs/frameworks/av/media/libdatasource/libdatasource/android_x86_x86_64_static_cfi/libdatasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libdatasource/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libdatasource/include/ prebuiltlibs/frameworks/av/media/libdatasource/include
mkdir -p prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/libplayerservice_datasource/android_x86_x86_64_static_cfi/libplayerservice_datasource.a
mkdir -p prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libmediaplayerservice/datasource/include/ prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/include
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_64_static_cfi/libstagefright_webm.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a prebuiltlibs/frameworks/av/media/libstagefright/webm/libstagefright_webm/android_x86_x86_64_static_cfi/libstagefright_webm.a
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_64_shared_cfi/libmedia_codeclist.so
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so prebuiltlibs/frameworks/av/media/libmedia/libmedia_codeclist/android_x86_x86_64_shared_cfi/libmedia_codeclist.so
mkdir -p prebuiltlibs/frameworks/av/media/libmedia/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libmedia/include/ prebuiltlibs/frameworks/av/media/libmedia/include
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/libmediadrmmetrics_full.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/libmediadrmmetrics_full.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_full/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/libmediadrmmetrics_lite.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/libmediadrmmetrics_lite.so
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/gen/proto prebuiltlibs/frameworks/av/drm/libmediadrm/libmediadrmmetrics_lite/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_shared_cfi/libmediandk_utils.so
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_64_static_cfi/libmediandk_utils.a
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_shared_cfi/libmediandk_utils.so
mkdir -p prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a prebuiltlibs/frameworks/av/media/ndk/libmediandk_utils/android_x86_x86_64_static_cfi/libmediandk_utils.a
mkdir -p prebuiltlibs/frameworks/av/media/ndk/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/ndk/include/ prebuiltlibs/frameworks/av/media/ndk/include
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_shared/libmediautils.so
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_64_static/libmediautils.a
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_shared/libmediautils.so
mkdir -p prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a prebuiltlibs/frameworks/av/media/utils/libmediautils/android_x86_x86_64_static/libmediautils.a
mkdir -p prebuiltlibs/frameworks/av/media/utils/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/utils/include/ prebuiltlibs/frameworks/av/media/utils/include
mkdir -p prebuiltlibs/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/ && mv out/soong/.intermediates/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver prebuiltlibs/frameworks/av/drm/drmserver/drmserver/android_x86_x86_64/drmserver
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/libaudioclient.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/libaudioclient.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/libaudioclient.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/libaudioclient.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_64_static/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_shared/
mkdir -p prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/ && rsync -ar out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/gen/aidl prebuiltlibs/frameworks/av/media/libaudioclient/libaudioclient/android_x86_x86_64_static/
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_shared/libaaudio_internal.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_64_static/libaaudio_internal.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_shared/libaaudio_internal.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio_internal/android_x86_x86_64_static/libaaudio_internal.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libaaudio/src/ prebuiltlibs/frameworks/av/media/libaaudio/src/
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_shared/libaaudio.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_64_static/libaaudio.a
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_shared/libaaudio.so
mkdir -p prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a prebuiltlibs/frameworks/av/media/libaaudio/src/libaaudio/android_x86_x86_64_static/libaaudio.a
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_64_shared/libaudiohal@4.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@4.0/android_x86_x86_64_shared/libaudiohal@4.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_64_shared/libaudiohal@5.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@5.0/android_x86_x86_64_shared/libaudiohal@5.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_64_shared/libaudiohal@6.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@6.0/android_x86_x86_64_shared/libaudiohal@6.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_64_shared/libaudiohal@7.0.so
mkdir -p prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so prebuiltlibs/frameworks/av/media/libaudiohal/impl/libaudiohal@7.0/android_x86_x86_64_shared/libaudiohal@7.0.so
mkdir -p prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_shared/libmedialogservice.so
mkdir -p prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a prebuiltlibs/frameworks/av/services/medialog/libmedialogservice/android_x86_64_static/libmedialogservice.a
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_shared/libmediametricsservice.so
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a prebuiltlibs/frameworks/av/services/mediametrics/libmediametricsservice/android_x86_64_static/libmediametricsservice.a
mkdir -p prebuiltlibs/frameworks/av/services/mediametrics/mediametrics/android_x86_64/ && mv out/soong/.intermediates/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics prebuiltlibs/frameworks/av/services/mediametrics/mediametrics/android_x86_64/mediametrics
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_shared/libstagefright_bufferpool@2.0.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_64_static/libstagefright_bufferpool@2.0.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_shared/libstagefright_bufferpool@2.0.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0/android_vendor.31_x86_x86_64_static/libstagefright_bufferpool@2.0.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/bufferpool/2.0/include/ prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_shared/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_x86_64_static/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_shared_apex29/libstagefright_bufferpool@2.0.1.so
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/ && mv out/soong/.intermediates/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a prebuiltlibs/frameworks/av/media/bufferpool/2.0/libstagefright_bufferpool@2.0.1/android_x86_64_static_apex29/libstagefright_bufferpool@2.0.1.a
mkdir -p prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/bufferpool/2.0/include/ prebuiltlibs/frameworks/av/media/bufferpool/2.0/include
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support/android_x86_x86_64_static_cfi/libstagefright_mpeg2support.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libstagefright/mpeg2ts/ prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/ && mv out/soong/.intermediates/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/libstagefright_mpeg2support_nocrypto/android_x86_64_static_cfi_com.android.media/libstagefright_mpeg2support_nocrypto.a
mkdir -p prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/
rsync -ar --exclude=".git" --exclude="Android.bp" --exclude="Android.mk" frameworks/av/media/libstagefright/mpeg2ts/ prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/

printf "cc_prebuilt_binary {\n  name: \"android.hardware.drm@1.4-service.clearkey\",\n  vendor: true,\n  relative_install_path: \"hw\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"android.hardware.drm@1.3\",\"android.hardware.drm@1.4\",\"libbase\",\"libbinder\",\"libcrypto\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libprotobuf-cpp-lite\",\"libutils\"],\n  sanitize: {\n    integer_overflow: true,\n  },\n  init_rc: [\"android.hardware.drm@1.4-service.clearkey.rc\"],\n  vintf_fragments: [\"manifest_android.hardware.drm@1.4-service.clearkey.xml\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"android.hardware.drm@1.4-service.clearkey\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/mediadrm/plugins/clearkey/hidl/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaudiopolicyengine_config\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libmedia_helper\",\"libxml2\",\"libutils\",\"liblog\",\"libcutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiopolicyengine_config.a\"],\n}\n" >> prebuiltlibs/frameworks/av/services/audiopolicy/engine/config/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudioprocessing\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libaudioutils\",\"libcutils\",\"liblog\",\"libutils\",\"libaudiohal\",\"libsonic\",\"libvibrator\"],\n  arch: {\n    x86: {\n      avx2: {\n      },\n    },\n    x86_64: {\n      avx2: {\n      },\n    },\n  },\n  whole_static_libs: [\"libaudioprocessing_base\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudioprocessing.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudioprocessing/Android.bp
printf "cc_prebuilt_library {\n  name: \"libdatasource\",\n  header_libs: [\"libstagefright_headers\",\"media_ndk_headers\"],\n  export_header_lib_headers: [\"libstagefright_headers\",\"media_ndk_headers\"],\n  shared_libs: [\"liblog\",\"libcutils\",\"libutils\",\"libstagefright_foundation\",\"libdl\"],\n  static_libs: [\"libc_malloc_debug_backtrace\",\"libmedia_midiiowrapper\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  prebuilt_aidl: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libdatasource.a\"],\n  },\n  shared: {\n    srcs: [\"libdatasource.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libdatasource/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libplayerservice_datasource\",\n  shared_libs: [\"libdatasource\",\"libdrmframework\",\"liblog\",\"libutils\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libplayerservice_datasource.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libmediaplayerservice/datasource/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_webm\",\n  sanitize: {\n    misc_undefined: [\"signed-integer-overflow\",\"unsigned-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libdatasource\",\"libstagefright_foundation\",\"libutils\",\"liblog\",\"framework-permission-aidl-cpp\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_webm.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/webm/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmedia_codeclist\",\n  shared_libs: [\"android.hardware.media.omx@1.0\",\"libbinder\",\"liblog\",\"libstagefright_foundation\",\"libutils\"],\n  export_include_dirs: [\"include\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmedia_codeclist.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libmedia/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmediadrmmetrics_full\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"libbase\",\"liblog\",\"libmediametrics\",\"libprotobuf-cpp-full\",\"libstagefright_foundation\",\"libutils\"],\n  prebuilt_proto: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmediadrmmetrics_full.so\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/libmediadrm/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libmediadrmmetrics_lite\",\n  shared_libs: [\"android.hardware.drm@1.0\",\"android.hardware.drm@1.1\",\"android.hardware.drm@1.2\",\"liblog\",\"libmediametrics\",\"libprotobuf-cpp-lite\",\"libutils\"],\n  prebuilt_proto: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libmediadrmmetrics_lite.so\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/libmediadrm/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediandk_utils\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediandk_utils.a\"],\n  },\n  shared: {\n    srcs: [\"libmediandk_utils.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/ndk/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediautils\",\n  static_libs: [\"libc_malloc_debug_backtrace\",\"libbatterystats_aidl\",\"libprocessinfoservice_aidl\"],\n  shared_libs: [\"libaudioclient_aidl_conversion\",\"libaudioutils\",\"libbinder\",\"libcutils\",\"liblog\",\"libutils\",\"libhidlbase\",\"libpermission\",\"android.hardware.graphics.bufferqueue@1.0\",\"android.hidl.token@1.0-utils\"],\n  export_static_lib_headers: [\"libbatterystats_aidl\"],\n  logtags: [\"EventLogTags.logtags\"],\n  export_shared_lib_headers: [\"libpermission\"],\n  export_include_dirs: [\"include\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediautils.a\"],\n  },\n  shared: {\n    srcs: [\"libmediautils.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/utils/Android.bp
printf "cc_prebuilt_binary {\n  name: \"drmserver\",\n  shared_libs: [\"libmediametrics\",\"libmediautils\",\"libcutils\",\"libutils\",\"liblog\",\"libbinder\",\"libdl\",\"libdrmframeworkcommon\",\"libselinux\",\"libstagefright_foundation\"],\n  compile_multilib: \"prefer32\",\n  init_rc: [\"drmserver.rc\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"drmserver\"],\n}\n" >> prebuiltlibs/frameworks/av/drm/drmserver/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaudioclient\",\n  shared_libs: [\"audioclient-types-aidl-cpp\",\"audioflinger-aidl-cpp\",\"audiopolicy-aidl-cpp\",\"audiopolicy-types-aidl-cpp\",\"av-types-aidl-cpp\",\"capture_state_listener-aidl-cpp\",\"libaudioclient_aidl_conversion\",\"libaudiofoundation\",\"libaudioutils\",\"libaudiopolicy\",\"libaudiomanager\",\"libbinder\",\"libcutils\",\"libdl\",\"liblog\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"libnblog\",\"libprocessgroup\",\"libshmemcompat\",\"libutils\",\"libvibrator\",\"framework-permission-aidl-cpp\"],\n  export_shared_lib_headers: [\"audioflinger-aidl-cpp\",\"audiopolicy-aidl-cpp\",\"framework-permission-aidl-cpp\",\"libbinder\"],\n  header_libs: [\"libaudioclient_headers\"],\n  export_header_lib_headers: [\"libaudioclient_headers\"],\n  export_static_lib_headers: [\"effect-aidl-cpp\",\"shared-file-region-aidl-cpp\"],\n  static_libs: [\"effect-aidl-cpp\",\"libc_malloc_debug_backtrace\",\"shared-file-region-aidl-cpp\"],\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n  },\n  prebuilt_aidl: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaudioclient.a\"],\n  },\n  shared: {\n    srcs: [\"libaudioclient.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaudioclient/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaaudio_internal\",\n  export_include_dirs: [\".\"],\n  header_libs: [\"libaaudio_headers\"],\n  export_header_lib_headers: [\"libaaudio_headers\"],\n  export_shared_lib_headers: [\"framework-permission-aidl-cpp\"],\n  shared_libs: [\"libaudioclient\",\"libaudioutils\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"liblog\",\"libcutils\",\"libutils\",\"libbinder\",\"framework-permission-aidl-cpp\",\"aaudio-aidl-cpp\",\"libaudioclient_aidl_conversion\"],\n  sanitize: {\n    integer_overflow: true,\n    misc_undefined: [\"bounds\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaaudio_internal.a\"],\n  },\n  shared: {\n    srcs: [\"libaaudio_internal.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaaudio/src/Android.bp
printf "cc_prebuilt_library {\n  name: \"libaaudio\",\n  header_libs: [\"libaaudio_headers\"],\n  export_header_lib_headers: [\"libaaudio_headers\"],\n  version_script: \"libaaudio.map.txt\",\n  shared_libs: [\"libaaudio_internal\",\"libaudioclient\",\"libaudioutils\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"liblog\",\"libcutils\",\"libutils\",\"libbinder\",\"libpermission\"],\n  sanitize: {\n    integer_overflow: true,\n    misc_undefined: [\"bounds\"],\n  },\n  stubs: {\n    symbol_file: \"libaaudio.map.txt\",\n    versions: [\"28\"],\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libaaudio.a\"],\n  },\n  shared: {\n    srcs: [\"libaaudio.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/libaaudio/src/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@4.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@4.0\",\"android.hardware.audio.common@4.0-util\",\"android.hardware.audio.effect@4.0\",\"android.hardware.audio.effect@4.0-util\",\"android.hardware.audio@4.0\",\"android.hardware.audio@4.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@4.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@5.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@5.0\",\"android.hardware.audio.common@5.0-util\",\"android.hardware.audio.effect@5.0\",\"android.hardware.audio.effect@5.0-util\",\"android.hardware.audio@5.0\",\"android.hardware.audio@5.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@5.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@6.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@6.0\",\"android.hardware.audio.common@6.0-util\",\"android.hardware.audio.effect@6.0\",\"android.hardware.audio.effect@6.0-util\",\"android.hardware.audio@6.0\",\"android.hardware.audio@6.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@6.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library_shared {\n  name: \"libaudiohal@7.0\",\n  shared_libs: [\"android.hardware.audio.common-util\",\"android.hidl.allocator@1.0\",\"android.hidl.memory@1.0\",\"av-types-aidl-cpp\",\"libaudiofoundation\",\"libaudiohal_deathhandler\",\"libaudioutils\",\"libbase\",\"libbinder\",\"libcutils\",\"libfmq\",\"libhardware\",\"libhidlbase\",\"libhidlmemory\",\"liblog\",\"libmedia_helper\",\"libmediautils\",\"libutils\",\"android.hardware.audio.common@7.0\",\"android.hardware.audio.common@7.0-util\",\"android.hardware.audio.effect@7.0\",\"android.hardware.audio.effect@7.0-util\",\"android.hardware.audio@7.0\",\"android.hardware.audio@7.0-util\"],\n  export_shared_lib_headers: [\"libfmq\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libaudiohal@7.0.so\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libaudiohal/impl/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmedialogservice\",\n  shared_libs: [\"libaudioutils\",\"libbinder\",\"liblog\",\"libmediautils\",\"libnblog\",\"libutils\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmedialogservice.a\"],\n  },\n  shared: {\n    srcs: [\"libmedialogservice.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/services/medialog/Android.bp
printf "cc_prebuilt_library {\n  name: \"libmediametricsservice\",\n  shared_libs: [\"mediametricsservice-aidl-cpp\",\"libbase\",\"libbinder\",\"libcutils\",\"liblog\",\"libmedia_helper\",\"libmediametrics\",\"libmediautils\",\"libmemunreachable\",\"libprotobuf-cpp-lite\",\"libstagefright_foundation\",\"libstatslog\",\"libstatspull\",\"libstatssocket\",\"libutils\"],\n  export_shared_lib_headers: [\"libstatspull\",\"libstatssocket\"],\n  static_libs: [\"libplatformprotos\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libmediametricsservice.a\"],\n  },\n  shared: {\n    srcs: [\"libmediametricsservice.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/services/mediametrics/Android.bp
printf "cc_prebuilt_binary {\n  name: \"mediametrics\",\n  shared_libs: [\"libbinder\",\"liblog\",\"libmediametricsservice\",\"libmediautils\",\"libutils\",\"mediametricsservice-aidl-cpp\"],\n  init_rc: [\"mediametrics.rc\"],\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"mediametrics\"],\n}\n" >> prebuiltlibs/frameworks/av/services/mediametrics/Android.bp
printf "cc_prebuilt_library {\n  name: \"libstagefright_bufferpool@2.0\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libcutils\",\"libfmq\",\"libhidlbase\",\"liblog\",\"libutils\",\"android.hardware.media.bufferpool@2.0\"],\n  export_shared_lib_headers: [\"libfmq\",\"android.hardware.media.bufferpool@2.0\"],\n  vendor_available: true,\n  double_loadable: true,\n  vndk: {\n    enabled: true,\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libstagefright_bufferpool@2.0.a\"],\n  },\n  shared: {\n    srcs: [\"libstagefright_bufferpool@2.0.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/bufferpool/2.0/Android.bp
printf "cc_prebuilt_library {\n  name: \"libstagefright_bufferpool@2.0.1\",\n  export_include_dirs: [\"include\"],\n  shared_libs: [\"libcutils\",\"libfmq\",\"libhidlbase\",\"liblog\",\"libutils\",\"android.hardware.media.bufferpool@2.0\"],\n  export_shared_lib_headers: [\"libfmq\",\"android.hardware.media.bufferpool@2.0\"],\n  vendor_available: true,\n  min_sdk_version: \"29\",\n  double_loadable: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  static: {\n    srcs: [\"libstagefright_bufferpool@2.0.1.a\"],\n  },\n  shared: {\n    srcs: [\"libstagefright_bufferpool@2.0.1.so\"],\n  },\n}\n" >> prebuiltlibs/frameworks/av/media/bufferpool/2.0/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_mpeg2support\",\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libhidlmemory\",\"android.hardware.cas.native@1.0\",\"android.hidl.memory@1.0\",\"android.hidl.allocator@1.0\",\"libcrypto\"],\n  export_include_dirs: [\".\"],\n  whole_static_libs: [\"libstagefright_metadatautils\"],\n  min_sdk_version: \"29\",\n  host_supported: true,\n  target: {\n    darwin: {\n      enabled: false,\n    },\n  },\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_mpeg2support.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/Android.bp
printf "cc_prebuilt_library_static {\n  name: \"libstagefright_mpeg2support_nocrypto\",\n  sanitize: {\n    misc_undefined: [\"unsigned-integer-overflow\",\"signed-integer-overflow\"],\n    cfi: true,\n  },\n  shared_libs: [\"libhidlmemory\",\"android.hardware.cas.native@1.0\",\"android.hidl.memory@1.0\",\"android.hidl.allocator@1.0\"],\n  export_include_dirs: [\".\"],\n  whole_static_libs: [\"libstagefright_metadatautils\"],\n  min_sdk_version: \"29\",\n  host_supported: true,\n  target: {\n    darwin: {\n      enabled: false,\n    },\n  },\n  apex_available: [\"com.android.media\"],\n  use_apex_name_macro: true,\n  strip: {\n    none: true,\n  },\n  multiple_variants: true,\n  prefer: true,\n  srcs: [\"libstagefright_mpeg2support_nocrypto.a\"],\n}\n" >> prebuiltlibs/frameworks/av/media/libstagefright/mpeg2ts/Android.bp

df -h
clean_out_intermediates
mkdir -p prebuiltlibs/frameworks/av/ninja && rsync -ar out/soong/ninja/frameworks/av/ prebuiltlibs/frameworks/av/ninja/frameworks_av-10
touch prebuiltlibs/frameworks/av/ninja/.find-ignore
tar cfJ frameworks_av-10.tar.xz -C prebuiltlibs/frameworks/av/ .
ls -l frameworks_av-10.tar.xz
end=`date +%s`
echo $((end-start))


du -ah -d1 out/soong |sort -h
