
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_28:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_apache-xml.tar.zst
        key: external_apache-xml@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_bouncycastle.tar.zst
        key: external_bouncycastle@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_conscrypt.tar.zst
        key: external_conscrypt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_exoplayer.tar.zst
        key: external_exoplayer@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libphonenumber.tar.zst
        key: external_libphonenumber@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_okhttp.tar.zst
        key: external_okhttp@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rappor.tar.zst
        key: external_rappor@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_tagsoup.tar.zst
        key: external_tagsoup@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_ims.tar.zst
        key: frameworks_opt_net_ims@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_voip.tar.zst
        key: frameworks_opt_net_voip@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_telephony.tar.zst
        key: frameworks_opt_telephony@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_proto_logging.tar.zst
        key: frameworks_proto_logging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Connectivity.tar.zst
        key: packages_modules_Connectivity@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_IPsec.tar.zst
        key: packages_modules_IPsec@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Permission.tar.zst
        key: packages_modules_Permission@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_RuntimeI18n.tar.zst
        key: packages_modules_RuntimeI18n@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Scheduling.tar.zst
        key: packages_modules_Scheduling@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_SdkExtensions.tar.zst
        key: packages_modules_SdkExtensions@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_StatsD.tar.zst
        key: packages_modules_StatsD@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Wifi.tar.zst
        key: packages_modules_Wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_common.tar.zst
        key: packages_modules_common@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_providers_MediaProvider.tar.zst
        key: packages_providers_MediaProvider@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_connectivity_wificond.tar.zst
        key: system_connectivity_wificond@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_gsid.tar.zst
        key: system_gsid@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_security.tar.zst
        key: system_security@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_update_engine.tar.zst
        key: system_update_engine@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_vold.tar.zst
        key: system_vold@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_apifinder.tar.zst
        key: tools_apifinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
    - run: bash steps/build_28.sh