
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_19:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_bouncycastle.tar.zst
        key: external_bouncycastle@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_net.tar.zst
        key: frameworks_libs_net@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_proto_logging.tar.zst
        key: frameworks_proto_logging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Connectivity.tar.zst
        key: packages_modules_Connectivity@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_IPsec.tar.zst
        key: packages_modules_IPsec@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Permission.tar.zst
        key: packages_modules_Permission@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Scheduling.tar.zst
        key: packages_modules_Scheduling@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_SdkExtensions.tar.zst
        key: packages_modules_SdkExtensions@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_StatsD.tar.zst
        key: packages_modules_StatsD@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Wifi.tar.zst
        key: packages_modules_Wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_common.tar.zst
        key: packages_modules_common@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_apex.tar.zst
        key: system_apex@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_hardware_interfaces.tar.zst
        key: system_hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libsysprop.tar.zst
        key: system_libsysprop@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_apifinder.tar.zst
        key: tools_apifinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_metalava.tar.zst
        key: tools_metalava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
    - run: bash steps/build_19.sh