
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_16:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2
    - uses: actions/cache@v4
      with:
        path: cache/bionic.tar.zst
        key: bionic@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_fmtlib.tar.zst
        key: external_fmtlib@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxx.tar.zst
        key: external_libcxx@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxxabi.tar.zst
        key: external_libcxxabi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_wilhelm.tar.zst
        key: frameworks_wilhelm@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware.tar.zst
        key: hardware_libhardware@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware_legacy.tar.zst
        key: hardware_libhardware_legacy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libnativehelper.tar.zst
        key: libnativehelper@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_clang_host_linux-x86.tar.zst
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libbase.tar.zst
        key: system_libbase@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libfmq.tar.zst
        key: system_libfmq@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhwbinder.tar.zst
        key: system_libhwbinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_logging.tar.zst
        key: system_logging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_media.tar.zst
        key: system_media@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_unwinding.tar.zst
        key: system_unwinding@${{ env.branch }}
    - run: bash steps/build_16.sh