set -e

source steps/build_01/build_make.sh
source steps/build_01/art.sh
source steps/build_01/bionic.sh
source steps/build_01/bootable_recovery.sh
source steps/build_01/build_blueprint.sh
source steps/build_01/build_soong.sh
source steps/build_01/device_generic_vulkan-cereal.sh
source steps/build_01/device_google_cuttlefish.sh
source steps/build_01/device_google_cuttlefish_prebuilts.sh
source steps/build_01/external_OpenCSD.sh
source steps/build_01/external_aac.sh
source steps/build_01/external_angle.sh
source steps/build_01/external_apache-http.sh
source steps/build_01/external_arm-optimized-routines.sh
source steps/build_01/external_avb.sh
source steps/build_01/external_bcc.sh
source steps/build_01/external_boringssl.sh
source steps/build_01/external_brotli.sh
source steps/build_01/external_bsdiff.sh
source steps/build_01/external_bzip2.sh
source steps/build_01/external_compiler-rt.sh
source steps/build_01/external_conscrypt.sh
source steps/build_01/external_cpu_features.sh
source steps/build_01/external_curl.sh
source steps/build_01/external_dng_sdk.sh
source steps/build_01/external_dtc.sh
source steps/build_01/external_dynamic_depth.sh
source steps/build_01/external_e2fsprogs.sh
source steps/build_01/external_eigen.sh
source steps/build_01/external_expat.sh
source steps/build_01/external_f2fs-tools.sh
source steps/build_01/external_fdlibm.sh
source steps/build_01/external_fec.sh
source steps/build_01/external_flac.sh
source steps/build_01/external_flatbuffers.sh
source steps/build_01/external_fmtlib.sh
source steps/build_01/external_freetype.sh
source steps/build_01/external_fsverity-utils.sh
source steps/build_01/external_gemmlowp.sh
source steps/build_01/external_gflags.sh
source steps/build_01/external_giflib.sh
source steps/build_01/external_golang-protobuf.sh
source steps/build_01/external_google-fonts_carrois-gothic-sc.sh
source steps/build_01/external_google-fonts_coming-soon.sh
source steps/build_01/external_google-fonts_cutive-mono.sh
source steps/build_01/external_google-fonts_dancing-script.sh
source steps/build_01/external_google-fonts_source-sans-pro.sh
source steps/build_01/external_google-fruit.sh
source steps/build_01/external_googletest.sh
source steps/build_01/external_gptfdisk.sh
source steps/build_01/external_grpc-grpc.sh
source steps/build_01/external_gwp_asan.sh
source steps/build_01/external_harfbuzz_ng.sh
source steps/build_01/external_icu.sh
source steps/build_01/external_image_io.sh
source steps/build_01/external_ipsec-tools.sh
source steps/build_01/external_iptables.sh
source steps/build_01/external_jsoncpp.sh
source steps/build_01/external_kmod.sh
source steps/build_01/external_libavc.sh
source steps/build_01/external_libcppbor.sh
source steps/build_01/external_libcxx.sh
source steps/build_01/external_libcxxabi.sh
source steps/build_01/external_libdrm.sh
source steps/build_01/external_libepoxy.sh
source steps/build_01/external_libevent.sh
source steps/build_01/external_libgav1.sh
source steps/build_01/external_libgsm.sh
source steps/build_01/external_libhevc.sh
source steps/build_01/external_libjpeg-turbo.sh
source steps/build_01/external_libmpeg2.sh
source steps/build_01/external_libnl.sh
source steps/build_01/external_libogg.sh
source steps/build_01/external_libopus.sh
source steps/build_01/external_libpcap.sh
source steps/build_01/external_libpng.sh
source steps/build_01/external_libtextclassifier.sh
source steps/build_01/external_libutf.sh
source steps/build_01/external_libvpx.sh
source steps/build_01/external_libxml2.sh
source steps/build_01/external_libyuv.sh
source steps/build_01/external_llvm.sh
source steps/build_01/external_lz4.sh
source steps/build_01/external_lzma.sh
source steps/build_01/external_mdnsresponder.sh
source steps/build_01/external_minigbm.sh
source steps/build_01/external_minijail.sh
source steps/build_01/external_mksh.sh
source steps/build_01/external_modp_b64.sh
source steps/build_01/external_nanopb-c.sh
source steps/build_01/external_neven.sh
source steps/build_01/external_noto-fonts.sh
source steps/build_01/external_oj-libjdwp.sh
source steps/build_01/external_parameter-framework.sh
source steps/build_01/external_pcre.sh
source steps/build_01/external_pdfium.sh
source steps/build_01/external_perfetto.sh
source steps/build_01/external_piex.sh
source steps/build_01/external_protobuf.sh
source steps/build_01/external_python_cpython2.sh
source steps/build_01/external_roboto-fonts.sh
source steps/build_01/external_rust_crates_bitflags.sh
source steps/build_01/external_rust_crates_bytes.sh
source steps/build_01/external_rust_crates_cfg-if.sh
source steps/build_01/external_rust_crates_either.sh
source steps/build_01/external_rust_crates_glob.sh
source steps/build_01/external_rust_crates_grpcio-sys.sh
source steps/build_01/external_rust_crates_lazy_static.sh
source steps/build_01/external_rust_crates_lazycell.sh
source steps/build_01/external_rust_crates_libc.sh
source steps/build_01/external_rust_crates_memchr.sh
source steps/build_01/external_rust_crates_paste.sh
source steps/build_01/external_rust_crates_peeking_take_while.sh
source steps/build_01/external_rust_crates_proc-macro-hack.sh
source steps/build_01/external_rust_crates_regex-syntax.sh
source steps/build_01/external_rust_crates_rustc-hash.sh
source steps/build_01/external_rust_crates_shlex.sh
source steps/build_01/external_rust_crates_termcolor.sh
source steps/build_01/external_rust_crates_textwrap.sh
source steps/build_01/external_rust_crates_unicode-segmentation.sh
source steps/build_01/external_rust_crates_unicode-width.sh
source steps/build_01/external_rust_crates_unicode-xid.sh
source steps/build_01/external_rust_cxx.sh
source steps/build_01/external_scrypt.sh
source steps/build_01/external_scudo.sh
source steps/build_01/external_selinux.sh
source steps/build_01/external_sfntly.sh
source steps/build_01/external_skia.sh
source steps/build_01/external_sonivox.sh
source steps/build_01/external_sqlite.sh
source steps/build_01/external_tensorflow.sh
source steps/build_01/external_tinyalsa.sh
source steps/build_01/external_tinyxml2.sh
source steps/build_01/external_tremolo.sh
source steps/build_01/external_virglrenderer.sh
source steps/build_01/external_vixl.sh
source steps/build_01/external_vulkan-headers.sh
source steps/build_01/external_webp.sh
source steps/build_01/external_xz-embedded.sh
source steps/build_01/external_zlib.sh
source steps/build_01/external_zopfli.sh
source steps/build_01/external_zstd.sh
source steps/build_01/frameworks_av.sh
source steps/build_01/frameworks_base.sh
source steps/build_01/frameworks_compile_libbcc.sh
source steps/build_01/frameworks_ex.sh
source steps/build_01/frameworks_libs_modules-utils.sh
source steps/build_01/frameworks_minikin.sh
source steps/build_01/frameworks_native.sh
source steps/build_01/frameworks_opt_net_wifi.sh
source steps/build_01/frameworks_rs.sh
source steps/build_01/frameworks_wilhelm.sh
source steps/build_01/hardware_interfaces.sh
source steps/build_01/libnativehelper.sh
source steps/build_01/packages_inputmethods_LatinIME.sh
source steps/build_01/packages_modules_Connectivity.sh
source steps/build_01/packages_modules_Gki.sh
source steps/build_01/packages_modules_IPsec.sh
source steps/build_01/packages_modules_NeuralNetworks.sh
source steps/build_01/packages_modules_SdkExtensions.sh
source steps/build_01/packages_modules_StatsD.sh
source steps/build_01/packages_modules_Virtualization.sh
source steps/build_01/packages_modules_Wifi.sh
source steps/build_01/packages_modules_adb.sh
source steps/build_01/packages_providers_MediaProvider.sh
source steps/build_01/packages_wallpapers_LivePicker.sh
source steps/build_01/prebuilts_build-tools.sh
source steps/build_01/prebuilts_clang_host_linux-x86.sh
source steps/build_01/prebuilts_misc.sh
source steps/build_01/prebuilts_ndk.sh
source steps/build_01/prebuilts_rust.sh
source steps/build_01/prebuilts_vndk_v28.sh
source steps/build_01/prebuilts_vndk_v29.sh
source steps/build_01/prebuilts_vndk_v30.sh
source steps/build_01/singletons.sh
source steps/build_01/system_apex.sh
source steps/build_01/system_bpf.sh
source steps/build_01/system_bpfprogs.sh
source steps/build_01/system_bt.sh
source steps/build_01/system_ca-certificates.sh
source steps/build_01/system_connectivity_wificond.sh
source steps/build_01/system_core.sh
source steps/build_01/system_extras.sh
source steps/build_01/system_gsid.sh
source steps/build_01/system_incremental_delivery.sh
source steps/build_01/system_keymaster.sh
source steps/build_01/system_libfmq.sh
source steps/build_01/system_libhwbinder.sh
source steps/build_01/system_libprocinfo.sh
source steps/build_01/system_libvintf.sh
source steps/build_01/system_libziparchive.sh
source steps/build_01/system_logging.sh
source steps/build_01/system_media.sh
source steps/build_01/system_memory_libdmabufheap.sh
source steps/build_01/system_memory_libion.sh
source steps/build_01/system_memory_libmeminfo.sh
source steps/build_01/system_memory_libmemunreachable.sh
source steps/build_01/system_memory_lmkd.sh
source steps/build_01/system_netd.sh
source steps/build_01/system_nfc.sh
source steps/build_01/system_security.sh
source steps/build_01/system_sepolicy.sh
source steps/build_01/system_server_configurable_flags.sh
source steps/build_01/system_timezone.sh
source steps/build_01/system_tools_hidl.sh
source steps/build_01/system_unwinding.sh
source steps/build_01/test_vts-testcase_hal.sh
source steps/build_01/tools_dexter.sh
