
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_2:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/bionic.tar.zst
        key: bionic@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/bootable_recovery.tar.zst
        key: bootable_recovery@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_google_cuttlefish.tar.zst
        key: device_google_cuttlefish@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_google_cuttlefish_prebuilts.tar.zst
        key: device_google_cuttlefish_prebuilts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_avb.tar.zst
        key: external_avb@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_boringssl.tar.zst
        key: external_boringssl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_compiler-rt.tar.zst
        key: external_compiler-rt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_crosvm.tar.zst
        key: external_crosvm@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_e2fsprogs.tar.zst
        key: external_e2fsprogs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_fmtlib.tar.zst
        key: external_fmtlib@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_googletest.tar.zst
        key: external_googletest@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_grpc-grpc.tar.zst
        key: external_grpc-grpc@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_gwp_asan.tar.zst
        key: external_gwp_asan@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxx.tar.zst
        key: external_libcxx@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxxabi.tar.zst
        key: external_libcxxabi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libdrm.tar.zst
        key: external_libdrm@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libpng.tar.zst
        key: external_libpng@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_nanopb-c.tar.zst
        key: external_nanopb-c@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_pcre.tar.zst
        key: external_pcre@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_aho-corasick.tar.zst
        key: external_rust_crates_aho-corasick@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_android_log-sys.tar.zst
        key: external_rust_crates_android_log-sys@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_anyhow.tar.zst
        key: external_rust_crates_anyhow@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_async-task.tar.zst
        key: external_rust_crates_async-task@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_bitflags.tar.zst
        key: external_rust_crates_bitflags@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_bytes.tar.zst
        key: external_rust_crates_bytes@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_cfg-if.tar.zst
        key: external_rust_crates_cfg-if@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_clap.tar.zst
        key: external_rust_crates_clap@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_codespan-reporting.tar.zst
        key: external_rust_crates_codespan-reporting@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_downcast-rs.tar.zst
        key: external_rust_crates_downcast-rs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_either.tar.zst
        key: external_rust_crates_either@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_fallible-iterator.tar.zst
        key: external_rust_crates_fallible-iterator@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_fallible-streaming-iterator.tar.zst
        key: external_rust_crates_fallible-streaming-iterator@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_futures.tar.zst
        key: external_rust_crates_futures@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_futures-core.tar.zst
        key: external_rust_crates_futures-core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_futures-io.tar.zst
        key: external_rust_crates_futures-io@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_futures-sink.tar.zst
        key: external_rust_crates_futures-sink@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_futures-task.tar.zst
        key: external_rust_crates_futures-task@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_heck.tar.zst
        key: external_rust_crates_heck@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_itoa.tar.zst
        key: external_rust_crates_itoa@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_lazy_static.tar.zst
        key: external_rust_crates_lazy_static@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_libc.tar.zst
        key: external_rust_crates_libc@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_libloading.tar.zst
        key: external_rust_crates_libloading@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_log.tar.zst
        key: external_rust_crates_log@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_memchr.tar.zst
        key: external_rust_crates_memchr@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_memoffset.tar.zst
        key: external_rust_crates_memoffset@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_nom.tar.zst
        key: external_rust_crates_nom@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_num-traits.tar.zst
        key: external_rust_crates_num-traits@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_pin-project.tar.zst
        key: external_rust_crates_pin-project@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_pin-project-lite.tar.zst
        key: external_rust_crates_pin-project-lite@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_pin-utils.tar.zst
        key: external_rust_crates_pin-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_ppv-lite86.tar.zst
        key: external_rust_crates_ppv-lite86@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_proc-macro2.tar.zst
        key: external_rust_crates_proc-macro2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_ryu.tar.zst
        key: external_rust_crates_ryu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_scopeguard.tar.zst
        key: external_rust_crates_scopeguard@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_slab.tar.zst
        key: external_rust_crates_slab@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_smallvec.tar.zst
        key: external_rust_crates_smallvec@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_termcolor.tar.zst
        key: external_rust_crates_termcolor@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_textwrap.tar.zst
        key: external_rust_crates_textwrap@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_unicode-segmentation.tar.zst
        key: external_rust_crates_unicode-segmentation@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_unicode-width.tar.zst
        key: external_rust_crates_unicode-width@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_unicode-xid.tar.zst
        key: external_rust_crates_unicode-xid@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_which.tar.zst
        key: external_rust_crates_which@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_selinux.tar.zst
        key: external_selinux@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_tinyxml2.tar.zst
        key: external_tinyxml2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_zlib.tar.zst
        key: external_zlib@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware.tar.zst
        key: hardware_libhardware@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware_legacy.tar.zst
        key: hardware_libhardware_legacy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Gki.tar.zst
        key: packages_modules_Gki@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Virtualization.tar.zst
        key: packages_modules_Virtualization@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_adb.tar.zst
        key: packages_modules_adb@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_clang_host_linux-x86.tar.zst
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8.tar.zst
        key: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_go_linux-x86.tar.zst
        key: prebuilts_go_linux-x86@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_rust.tar.zst
        key: prebuilts_rust@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_extras.tar.zst
        key: system_extras@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_gsid.tar.zst
        key: system_gsid@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_incremental_delivery.tar.zst
        key: system_incremental_delivery@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libbase.tar.zst
        key: system_libbase@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libprocinfo.tar.zst
        key: system_libprocinfo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libvintf.tar.zst
        key: system_libvintf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libziparchive.tar.zst
        key: system_libziparchive@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_logging.tar.zst
        key: system_logging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_media.tar.zst
        key: system_media@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_tools_aidl.tar.zst
        key: system_tools_aidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_tools_hidl.tar.zst
        key: system_tools_hidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_unwinding.tar.zst
        key: system_unwinding@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_vold.tar.zst
        key: system_vold@${{ env.branch }}
    - run: bash steps/build_02.sh