
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_34:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_apache-http.tar.zst
        key: external_apache-http@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_guava.tar.zst
        key: external_guava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_ethernet.tar.zst
        key: frameworks_opt_net_ethernet@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_vcard.tar.zst
        key: frameworks_opt_vcard@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Bluetooth.tar.zst
        key: packages_apps_Bluetooth@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
    - run: bash steps/build_34.sh