
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_25:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
        restore-keys: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
        restore-keys: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
        restore-keys: build_soong@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
        restore-keys: cts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_apache-http.tar.zst
        key: external_apache-http@${{ env.branch }}
        restore-keys: external_apache-http@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_guava.tar.zst
        key: external_guava@${{ env.branch }}
        restore-keys: external_guava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
        restore-keys: external_icu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_ims.tar.zst
        key: external_ims@${{ env.branch }}
        restore-keys: external_ims@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libtextclassifier.tar.zst
        key: external_libtextclassifier@${{ env.branch }}
        restore-keys: external_libtextclassifier@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_lottie.tar.zst
        key: external_lottie@${{ env.branch }}
        restore-keys: external_lottie@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
        restore-keys: external_protobuf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_setupcompat.tar.zst
        key: external_setupcompat@${{ env.branch }}
        restore-keys: external_setupcompat@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_setupdesign.tar.zst
        key: external_setupdesign@${{ env.branch }}
        restore-keys: external_setupdesign@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
        restore-keys: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
        restore-keys: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
        restore-keys: frameworks_libs_modules-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_net.tar.zst
        key: frameworks_libs_net@${{ env.branch }}
        restore-keys: frameworks_libs_net@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_wifi.tar.zst
        key: frameworks_opt_net_wifi@${{ env.branch }}
        restore-keys: frameworks_opt_net_wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
        restore-keys: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
        restore-keys: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Bluetooth.tar.zst
        key: packages_apps_Bluetooth@${{ env.branch }}
        restore-keys: packages_apps_Bluetooth@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_CellBroadcastReceiver.tar.zst
        key: packages_apps_CellBroadcastReceiver@${{ env.branch }}
        restore-keys: packages_apps_CellBroadcastReceiver@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_EmergencyInfo.tar.zst
        key: packages_apps_EmergencyInfo@${{ env.branch }}
        restore-keys: packages_apps_EmergencyInfo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_ManagedProvisioning.tar.zst
        key: packages_apps_ManagedProvisioning@${{ env.branch }}
        restore-keys: packages_apps_ManagedProvisioning@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Settings.tar.zst
        key: packages_apps_Settings@${{ env.branch }}
        restore-keys: packages_apps_Settings@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_CellBroadcastService.tar.zst
        key: packages_modules_CellBroadcastService@${{ env.branch }}
        restore-keys: packages_modules_CellBroadcastService@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Connectivity.tar.zst
        key: packages_modules_Connectivity@${{ env.branch }}
        restore-keys: packages_modules_Connectivity@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_ExtServices.tar.zst
        key: packages_modules_ExtServices@${{ env.branch }}
        restore-keys: packages_modules_ExtServices@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_NetworkStack.tar.zst
        key: packages_modules_NetworkStack@${{ env.branch }}
        restore-keys: packages_modules_NetworkStack@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Permission.tar.zst
        key: packages_modules_Permission@${{ env.branch }}
        restore-keys: packages_modules_Permission@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_StatsD.tar.zst
        key: packages_modules_StatsD@${{ env.branch }}
        restore-keys: packages_modules_StatsD@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Wifi.tar.zst
        key: packages_modules_Wifi@${{ env.branch }}
        restore-keys: packages_modules_Wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_services_Car.tar.zst
        key: packages_services_Car@${{ env.branch }}
        restore-keys: packages_services_Car@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
        restore-keys: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
        restore-keys: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
        restore-keys: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
        restore-keys: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
        restore-keys: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_netd.tar.zst
        key: system_netd@${{ env.branch }}
        restore-keys: system_netd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
        restore-keys: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_timezone.tar.zst
        key: system_timezone@${{ env.branch }}
        restore-keys: system_timezone@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_apifinder.tar.zst
        key: tools_apifinder@${{ env.branch }}
        restore-keys: tools_apifinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
        restore-keys: tools_platform-compat@${{ env.branch }}
    - run: bash steps/build_25.sh