
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_03:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install ninja
      run: sudo apt update && sudo apt install -y ninja-build
    - name: Restore Cache art.tar.zst
      id: art
      uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
        restore-keys: art@${{ env.branch }}
    - name: Restore Cache bionic.tar.zst
      id: bionic
      uses: actions/cache@v4
      with:
        path: cache/bionic.tar.zst
        key: bionic@${{ env.branch }}
        restore-keys: bionic@${{ env.branch }}
    - name: Restore Cache build_blueprint.tar.zst
      id: build_blueprint
      uses: actions/cache@v4
      with:
        path: cache/build_blueprint.tar.zst
        key: build_blueprint@${{ env.branch }}
        restore-keys: build_blueprint@${{ env.branch }}
    - name: Restore Cache build_make.tar.zst
      id: build_make
      uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
        restore-keys: build_make@${{ env.branch }}
    - name: Restore Cache build_soong.tar.zst
      id: build_soong
      uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
        restore-keys: build_soong@${{ env.branch }}
    - name: Restore Cache device_generic_vulkan-cereal.tar.zst
      id: device_generic_vulkan-cereal
      uses: actions/cache@v4
      with:
        path: cache/device_generic_vulkan-cereal.tar.zst
        key: device_generic_vulkan-cereal@${{ env.branch }}
        restore-keys: device_generic_vulkan-cereal@${{ env.branch }}
    - name: Restore Cache external_boringssl.tar.zst
      id: external_boringssl
      uses: actions/cache@v4
      with:
        path: cache/external_boringssl.tar.zst
        key: external_boringssl@${{ env.branch }}
        restore-keys: external_boringssl@${{ env.branch }}
    - name: Restore Cache external_conscrypt.tar.zst
      id: external_conscrypt
      uses: actions/cache@v4
      with:
        path: cache/external_conscrypt.tar.zst
        key: external_conscrypt@${{ env.branch }}
        restore-keys: external_conscrypt@${{ env.branch }}
    - name: Restore Cache external_e2fsprogs.tar.zst
      id: external_e2fsprogs
      uses: actions/cache@v4
      with:
        path: cache/external_e2fsprogs.tar.zst
        key: external_e2fsprogs@${{ env.branch }}
        restore-keys: external_e2fsprogs@${{ env.branch }}
    - name: Restore Cache external_f2fs-tools.tar.zst
      id: external_f2fs-tools
      uses: actions/cache@v4
      with:
        path: cache/external_f2fs-tools.tar.zst
        key: external_f2fs-tools@${{ env.branch }}
        restore-keys: external_f2fs-tools@${{ env.branch }}
    - name: Restore Cache external_fmtlib.tar.zst
      id: external_fmtlib
      uses: actions/cache@v4
      with:
        path: cache/external_fmtlib.tar.zst
        key: external_fmtlib@${{ env.branch }}
        restore-keys: external_fmtlib@${{ env.branch }}
    - name: Restore Cache external_googletest.tar.zst
      id: external_googletest
      uses: actions/cache@v4
      with:
        path: cache/external_googletest.tar.zst
        key: external_googletest@${{ env.branch }}
        restore-keys: external_googletest@${{ env.branch }}
    - name: Restore Cache external_grpc-grpc.tar.zst
      id: external_grpc-grpc
      uses: actions/cache@v4
      with:
        path: cache/external_grpc-grpc.tar.zst
        key: external_grpc-grpc@${{ env.branch }}
        restore-keys: external_grpc-grpc@${{ env.branch }}
    - name: Restore Cache external_libcxx.tar.zst
      id: external_libcxx
      uses: actions/cache@v4
      with:
        path: cache/external_libcxx.tar.zst
        key: external_libcxx@${{ env.branch }}
        restore-keys: external_libcxx@${{ env.branch }}
    - name: Restore Cache external_libcxxabi.tar.zst
      id: external_libcxxabi
      uses: actions/cache@v4
      with:
        path: cache/external_libcxxabi.tar.zst
        key: external_libcxxabi@${{ env.branch }}
        restore-keys: external_libcxxabi@${{ env.branch }}
    - name: Restore Cache external_lz4.tar.zst
      id: external_lz4
      uses: actions/cache@v4
      with:
        path: cache/external_lz4.tar.zst
        key: external_lz4@${{ env.branch }}
        restore-keys: external_lz4@${{ env.branch }}
    - name: Restore Cache external_pcre.tar.zst
      id: external_pcre
      uses: actions/cache@v4
      with:
        path: cache/external_pcre.tar.zst
        key: external_pcre@${{ env.branch }}
        restore-keys: external_pcre@${{ env.branch }}
    - name: Restore Cache external_protobuf.tar.zst
      id: external_protobuf
      uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
        restore-keys: external_protobuf@${{ env.branch }}
    - name: Restore Cache external_rust_crates_aho-corasick.tar.zst
      id: external_rust_crates_aho-corasick
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_aho-corasick.tar.zst
        key: external_rust_crates_aho-corasick@${{ env.branch }}
        restore-keys: external_rust_crates_aho-corasick@${{ env.branch }}
    - name: Restore Cache external_rust_crates_cexpr.tar.zst
      id: external_rust_crates_cexpr
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_cexpr.tar.zst
        key: external_rust_crates_cexpr@${{ env.branch }}
        restore-keys: external_rust_crates_cexpr@${{ env.branch }}
    - name: Restore Cache external_rust_crates_cfg-if.tar.zst
      id: external_rust_crates_cfg-if
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_cfg-if.tar.zst
        key: external_rust_crates_cfg-if@${{ env.branch }}
        restore-keys: external_rust_crates_cfg-if@${{ env.branch }}
    - name: Restore Cache external_rust_crates_env_logger.tar.zst
      id: external_rust_crates_env_logger
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_env_logger.tar.zst
        key: external_rust_crates_env_logger@${{ env.branch }}
        restore-keys: external_rust_crates_env_logger@${{ env.branch }}
    - name: Restore Cache external_rust_crates_log.tar.zst
      id: external_rust_crates_log
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_log.tar.zst
        key: external_rust_crates_log@${{ env.branch }}
        restore-keys: external_rust_crates_log@${{ env.branch }}
    - name: Restore Cache external_rust_crates_memchr.tar.zst
      id: external_rust_crates_memchr
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_memchr.tar.zst
        key: external_rust_crates_memchr@${{ env.branch }}
        restore-keys: external_rust_crates_memchr@${{ env.branch }}
    - name: Restore Cache external_rust_crates_nom.tar.zst
      id: external_rust_crates_nom
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_nom.tar.zst
        key: external_rust_crates_nom@${{ env.branch }}
        restore-keys: external_rust_crates_nom@${{ env.branch }}
    - name: Restore Cache external_rust_crates_proc-macro2.tar.zst
      id: external_rust_crates_proc-macro2
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_proc-macro2.tar.zst
        key: external_rust_crates_proc-macro2@${{ env.branch }}
        restore-keys: external_rust_crates_proc-macro2@${{ env.branch }}
    - name: Restore Cache external_rust_crates_quote.tar.zst
      id: external_rust_crates_quote
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_quote.tar.zst
        key: external_rust_crates_quote@${{ env.branch }}
        restore-keys: external_rust_crates_quote@${{ env.branch }}
    - name: Restore Cache external_rust_crates_regex.tar.zst
      id: external_rust_crates_regex
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_regex.tar.zst
        key: external_rust_crates_regex@${{ env.branch }}
        restore-keys: external_rust_crates_regex@${{ env.branch }}
    - name: Restore Cache external_rust_crates_regex-syntax.tar.zst
      id: external_rust_crates_regex-syntax
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_regex-syntax.tar.zst
        key: external_rust_crates_regex-syntax@${{ env.branch }}
        restore-keys: external_rust_crates_regex-syntax@${{ env.branch }}
    - name: Restore Cache external_rust_crates_unicode-xid.tar.zst
      id: external_rust_crates_unicode-xid
      uses: actions/cache@v4
      with:
        path: cache/external_rust_crates_unicode-xid.tar.zst
        key: external_rust_crates_unicode-xid@${{ env.branch }}
        restore-keys: external_rust_crates_unicode-xid@${{ env.branch }}
    - name: Restore Cache external_selinux.tar.zst
      id: external_selinux
      uses: actions/cache@v4
      with:
        path: cache/external_selinux.tar.zst
        key: external_selinux@${{ env.branch }}
        restore-keys: external_selinux@${{ env.branch }}
    - name: Restore Cache external_zlib.tar.zst
      id: external_zlib
      uses: actions/cache@v4
      with:
        path: cache/external_zlib.tar.zst
        key: external_zlib@${{ env.branch }}
        restore-keys: external_zlib@${{ env.branch }}
    - name: Restore Cache external_zopfli.tar.zst
      id: external_zopfli
      uses: actions/cache@v4
      with:
        path: cache/external_zopfli.tar.zst
        key: external_zopfli@${{ env.branch }}
        restore-keys: external_zopfli@${{ env.branch }}
    - name: Restore Cache frameworks_av.tar.zst
      id: frameworks_av
      uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
        restore-keys: frameworks_av@${{ env.branch }}
    - name: Restore Cache frameworks_native.tar.zst
      id: frameworks_native
      uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
        restore-keys: frameworks_native@${{ env.branch }}
    - name: Restore Cache hardware_libhardware.tar.zst
      id: hardware_libhardware
      uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware.tar.zst
        key: hardware_libhardware@${{ env.branch }}
        restore-keys: hardware_libhardware@${{ env.branch }}
    - name: Restore Cache hardware_libhardware_legacy.tar.zst
      id: hardware_libhardware_legacy
      uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware_legacy.tar.zst
        key: hardware_libhardware_legacy@${{ env.branch }}
        restore-keys: hardware_libhardware_legacy@${{ env.branch }}
    - name: Restore Cache hardware_ril.tar.zst
      id: hardware_ril
      uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
        restore-keys: hardware_ril@${{ env.branch }}
    - name: Restore Cache libcore.tar.zst
      id: libcore
      uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
        restore-keys: libcore@${{ env.branch }}
    - name: Restore Cache libnativehelper.tar.zst
      id: libnativehelper
      uses: actions/cache@v4
      with:
        path: cache/libnativehelper.tar.zst
        key: libnativehelper@${{ env.branch }}
        restore-keys: libnativehelper@${{ env.branch }}
    - name: Restore Cache packages_modules_adb.tar.zst
      id: packages_modules_adb
      uses: actions/cache@v4
      with:
        path: cache/packages_modules_adb.tar.zst
        key: packages_modules_adb@${{ env.branch }}
        restore-keys: packages_modules_adb@${{ env.branch }}
    - name: Restore Cache prebuilts_build-tools.tar.zst
      id: prebuilts_build-tools
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
        restore-keys: prebuilts_build-tools@${{ env.branch }}
    - name: Restore Cache prebuilts_clang_host_linux-x86.tar.zst
      id: prebuilts_clang_host_linux-x86
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_clang_host_linux-x86.tar.zst
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
        restore-keys: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - name: Restore Cache prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8.tar.zst
      id: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2-17-4-8
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8.tar.zst
        key: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8@${{ env.branch }}
        restore-keys: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2.17-4.8@${{ env.branch }}
    - name: Restore Cache prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
      id: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4-9
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
        restore-keys: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
    - name: Restore Cache prebuilts_go_linux-x86.tar.zst
      id: prebuilts_go_linux-x86
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_go_linux-x86.tar.zst
        key: prebuilts_go_linux-x86@${{ env.branch }}
        restore-keys: prebuilts_go_linux-x86@${{ env.branch }}
    - name: Restore Cache prebuilts_rust.tar.zst
      id: prebuilts_rust
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_rust.tar.zst
        key: prebuilts_rust@${{ env.branch }}
        restore-keys: prebuilts_rust@${{ env.branch }}
    - name: Restore Cache system_connectivity_wificond.tar.zst
      id: system_connectivity_wificond
      uses: actions/cache@v4
      with:
        path: cache/system_connectivity_wificond.tar.zst
        key: system_connectivity_wificond@${{ env.branch }}
        restore-keys: system_connectivity_wificond@${{ env.branch }}
    - name: Restore Cache system_core.tar.zst
      id: system_core
      uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
        restore-keys: system_core@${{ env.branch }}
    - name: Restore Cache system_libbase.tar.zst
      id: system_libbase
      uses: actions/cache@v4
      with:
        path: cache/system_libbase.tar.zst
        key: system_libbase@${{ env.branch }}
        restore-keys: system_libbase@${{ env.branch }}
    - name: Restore Cache system_libziparchive.tar.zst
      id: system_libziparchive
      uses: actions/cache@v4
      with:
        path: cache/system_libziparchive.tar.zst
        key: system_libziparchive@${{ env.branch }}
        restore-keys: system_libziparchive@${{ env.branch }}
    - name: Restore Cache system_logging.tar.zst
      id: system_logging
      uses: actions/cache@v4
      with:
        path: cache/system_logging.tar.zst
        key: system_logging@${{ env.branch }}
        restore-keys: system_logging@${{ env.branch }}
    - name: Restore Cache system_media.tar.zst
      id: system_media
      uses: actions/cache@v4
      with:
        path: cache/system_media.tar.zst
        key: system_media@${{ env.branch }}
        restore-keys: system_media@${{ env.branch }}
    - name: Restore Cache system_sepolicy.tar.zst
      id: system_sepolicy
      uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
        restore-keys: system_sepolicy@${{ env.branch }}
    - name: Restore Cache system_unwinding.tar.zst
      id: system_unwinding
      uses: actions/cache@v4
      with:
        path: cache/system_unwinding.tar.zst
        key: system_unwinding@${{ env.branch }}
        restore-keys: system_unwinding@${{ env.branch }}
    - name: Start Soong
      run: bash steps/build_03.sh
    - uses: actions/upload-artifact@v4
      with:
        name: bionic
        overwrite: true
        path: bionic.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: build_blueprint
        overwrite: true
        path: build_blueprint.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: build_make
        overwrite: true
        path: build_make.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: build_soong
        overwrite: true
        path: build_soong.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: device_generic_vulkan-cereal
        overwrite: true
        path: device_generic_vulkan-cereal.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_conscrypt
        overwrite: true
        path: external_conscrypt.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_e2fsprogs
        overwrite: true
        path: external_e2fsprogs.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_f2fs-tools
        overwrite: true
        path: external_f2fs-tools.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_grpc-grpc
        overwrite: true
        path: external_grpc-grpc.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_libcxx
        overwrite: true
        path: external_libcxx.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_lz4
        overwrite: true
        path: external_lz4.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_protobuf
        overwrite: true
        path: external_protobuf.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_rust_crates_cexpr
        overwrite: true
        path: external_rust_crates_cexpr.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_rust_crates_env_logger
        overwrite: true
        path: external_rust_crates_env_logger.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_rust_crates_quote
        overwrite: true
        path: external_rust_crates_quote.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_rust_crates_regex
        overwrite: true
        path: external_rust_crates_regex.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: external_selinux
        overwrite: true
        path: external_selinux.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: packages_modules_adb
        overwrite: true
        path: packages_modules_adb.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: prebuilts_rust
        overwrite: true
        path: prebuilts_rust.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: system_connectivity_wificond
        overwrite: true
        path: system_connectivity_wificond.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: system_core
        overwrite: true
        path: system_core.tar.zst
    - uses: actions/upload-artifact@v4
      with:
        name: system_sepolicy
        overwrite: true
        path: system_sepolicy.tar.zst