
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_31:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install ninja
      run: sudo apt update && sudo apt install -y ninja-build python2
    - name: Restore Cache art.tar.zst
      id: art
      uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
        restore-keys: art@${{ env.branch }}
    - name: Restore Cache bionic.tar.zst
      id: bionic
      uses: actions/cache@v4
      with:
        path: cache/bionic.tar.zst
        key: bionic@${{ env.branch }}
        restore-keys: bionic@${{ env.branch }}
    - name: Restore Cache build_soong.tar.zst
      id: build_soong
      uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
        restore-keys: build_soong@${{ env.branch }}
    - name: Restore Cache cts.tar.zst
      id: cts
      uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
        restore-keys: cts@${{ env.branch }}
    - name: Restore Cache external_apache-xml.tar.zst
      id: external_apache-xml
      uses: actions/cache@v4
      with:
        path: cache/external_apache-xml.tar.zst
        key: external_apache-xml@${{ env.branch }}
        restore-keys: external_apache-xml@${{ env.branch }}
    - name: Restore Cache external_bouncycastle.tar.zst
      id: external_bouncycastle
      uses: actions/cache@v4
      with:
        path: cache/external_bouncycastle.tar.zst
        key: external_bouncycastle@${{ env.branch }}
        restore-keys: external_bouncycastle@${{ env.branch }}
    - name: Restore Cache external_compiler-rt.tar.zst
      id: external_compiler-rt
      uses: actions/cache@v4
      with:
        path: cache/external_compiler-rt.tar.zst
        key: external_compiler-rt@${{ env.branch }}
        restore-keys: external_compiler-rt@${{ env.branch }}
    - name: Restore Cache external_conscrypt.tar.zst
      id: external_conscrypt
      uses: actions/cache@v4
      with:
        path: cache/external_conscrypt.tar.zst
        key: external_conscrypt@${{ env.branch }}
        restore-keys: external_conscrypt@${{ env.branch }}
    - name: Restore Cache external_exoplayer.tar.zst
      id: external_exoplayer
      uses: actions/cache@v4
      with:
        path: cache/external_exoplayer.tar.zst
        key: external_exoplayer@${{ env.branch }}
        restore-keys: external_exoplayer@${{ env.branch }}
    - name: Restore Cache external_fmtlib.tar.zst
      id: external_fmtlib
      uses: actions/cache@v4
      with:
        path: cache/external_fmtlib.tar.zst
        key: external_fmtlib@${{ env.branch }}
        restore-keys: external_fmtlib@${{ env.branch }}
    - name: Restore Cache external_icing.tar.zst
      id: external_icing
      uses: actions/cache@v4
      with:
        path: cache/external_icing.tar.zst
        key: external_icing@${{ env.branch }}
        restore-keys: external_icing@${{ env.branch }}
    - name: Restore Cache external_icu.tar.zst
      id: external_icu
      uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
        restore-keys: external_icu@${{ env.branch }}
    - name: Restore Cache external_jsr305.tar.zst
      id: external_jsr305
      uses: actions/cache@v4
      with:
        path: cache/external_jsr305.tar.zst
        key: external_jsr305@${{ env.branch }}
        restore-keys: external_jsr305@${{ env.branch }}
    - name: Restore Cache external_libcxx.tar.zst
      id: external_libcxx
      uses: actions/cache@v4
      with:
        path: cache/external_libcxx.tar.zst
        key: external_libcxx@${{ env.branch }}
        restore-keys: external_libcxx@${{ env.branch }}
    - name: Restore Cache external_libcxxabi.tar.zst
      id: external_libcxxabi
      uses: actions/cache@v4
      with:
        path: cache/external_libcxxabi.tar.zst
        key: external_libcxxabi@${{ env.branch }}
        restore-keys: external_libcxxabi@${{ env.branch }}
    - name: Restore Cache external_okhttp.tar.zst
      id: external_okhttp
      uses: actions/cache@v4
      with:
        path: cache/external_okhttp.tar.zst
        key: external_okhttp@${{ env.branch }}
        restore-keys: external_okhttp@${{ env.branch }}
    - name: Restore Cache external_protobuf.tar.zst
      id: external_protobuf
      uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
        restore-keys: external_protobuf@${{ env.branch }}
    - name: Restore Cache frameworks_av.tar.zst
      id: frameworks_av
      uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
        restore-keys: frameworks_av@${{ env.branch }}
    - name: Restore Cache frameworks_base.tar.zst
      id: frameworks_base
      uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
        restore-keys: frameworks_base@${{ env.branch }}
    - name: Restore Cache frameworks_libs_modules-utils.tar.zst
      id: frameworks_libs_modules-utils
      uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
        restore-keys: frameworks_libs_modules-utils@${{ env.branch }}
    - name: Restore Cache frameworks_native.tar.zst
      id: frameworks_native
      uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
        restore-keys: frameworks_native@${{ env.branch }}
    - name: Restore Cache frameworks_proto_logging.tar.zst
      id: frameworks_proto_logging
      uses: actions/cache@v4
      with:
        path: cache/frameworks_proto_logging.tar.zst
        key: frameworks_proto_logging@${{ env.branch }}
        restore-keys: frameworks_proto_logging@${{ env.branch }}
    - name: Restore Cache hardware_interfaces.tar.zst
      id: hardware_interfaces
      uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
        restore-keys: hardware_interfaces@${{ env.branch }}
    - name: Restore Cache hardware_libhardware.tar.zst
      id: hardware_libhardware
      uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware.tar.zst
        key: hardware_libhardware@${{ env.branch }}
        restore-keys: hardware_libhardware@${{ env.branch }}
    - name: Restore Cache hardware_libhardware_legacy.tar.zst
      id: hardware_libhardware_legacy
      uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware_legacy.tar.zst
        key: hardware_libhardware_legacy@${{ env.branch }}
        restore-keys: hardware_libhardware_legacy@${{ env.branch }}
    - name: Restore Cache hardware_ril.tar.zst
      id: hardware_ril
      uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
        restore-keys: hardware_ril@${{ env.branch }}
    - name: Restore Cache libcore.tar.zst
      id: libcore
      uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
        restore-keys: libcore@${{ env.branch }}
    - name: Restore Cache libnativehelper.tar.zst
      id: libnativehelper
      uses: actions/cache@v4
      with:
        path: cache/libnativehelper.tar.zst
        key: libnativehelper@${{ env.branch }}
        restore-keys: libnativehelper@${{ env.branch }}
    - name: Restore Cache prebuilts_build-tools.tar.zst
      id: prebuilts_build-tools
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
        restore-keys: prebuilts_build-tools@${{ env.branch }}
    - name: Restore Cache prebuilts_clang_host_linux-x86.tar.zst
      id: prebuilts_clang_host_linux-x86
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_clang_host_linux-x86.tar.zst
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
        restore-keys: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - name: Restore Cache prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
      id: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4-9
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
        restore-keys: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
    - name: Restore Cache prebuilts_jdk_jdk11.tar.zst
      id: prebuilts_jdk_jdk11
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
        restore-keys: prebuilts_jdk_jdk11@${{ env.branch }}
    - name: Restore Cache prebuilts_sdk.tar.zst
      id: prebuilts_sdk
      uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
        restore-keys: prebuilts_sdk@${{ env.branch }}
    - name: Restore Cache system_bt.tar.zst
      id: system_bt
      uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
        restore-keys: system_bt@${{ env.branch }}
    - name: Restore Cache system_core.tar.zst
      id: system_core
      uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
        restore-keys: system_core@${{ env.branch }}
    - name: Restore Cache system_libbase.tar.zst
      id: system_libbase
      uses: actions/cache@v4
      with:
        path: cache/system_libbase.tar.zst
        key: system_libbase@${{ env.branch }}
        restore-keys: system_libbase@${{ env.branch }}
    - name: Restore Cache system_libfmq.tar.zst
      id: system_libfmq
      uses: actions/cache@v4
      with:
        path: cache/system_libfmq.tar.zst
        key: system_libfmq@${{ env.branch }}
        restore-keys: system_libfmq@${{ env.branch }}
    - name: Restore Cache system_libhidl.tar.zst
      id: system_libhidl
      uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
        restore-keys: system_libhidl@${{ env.branch }}
    - name: Restore Cache system_libhwbinder.tar.zst
      id: system_libhwbinder
      uses: actions/cache@v4
      with:
        path: cache/system_libhwbinder.tar.zst
        key: system_libhwbinder@${{ env.branch }}
        restore-keys: system_libhwbinder@${{ env.branch }}
    - name: Restore Cache system_logging.tar.zst
      id: system_logging
      uses: actions/cache@v4
      with:
        path: cache/system_logging.tar.zst
        key: system_logging@${{ env.branch }}
        restore-keys: system_logging@${{ env.branch }}
    - name: Restore Cache system_media.tar.zst
      id: system_media
      uses: actions/cache@v4
      with:
        path: cache/system_media.tar.zst
        key: system_media@${{ env.branch }}
        restore-keys: system_media@${{ env.branch }}
    - name: Restore Cache system_unwinding.tar.zst
      id: system_unwinding
      uses: actions/cache@v4
      with:
        path: cache/system_unwinding.tar.zst
        key: system_unwinding@${{ env.branch }}
        restore-keys: system_unwinding@${{ env.branch }}
    - name: Restore Cache tools_platform-compat.tar.zst
      id: tools_platform-compat
      uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
        restore-keys: tools_platform-compat@${{ env.branch }}
    - name: Start Ninja Build
      run: bash steps/build_31.sh
