
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions: write-all
jobs:
  build_25:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/cts.tar.zst
        key: cts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_apache-http.tar.zst
        key: external_apache-http@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_guava.tar.zst
        key: external_guava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_ims.tar.zst
        key: external_ims@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libtextclassifier.tar.zst
        key: external_libtextclassifier@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_lottie.tar.zst
        key: external_lottie@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_nist-sip.tar.zst
        key: external_nist-sip@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_setupcompat.tar.zst
        key: external_setupcompat@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_setupdesign.tar.zst
        key: external_setupdesign@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_net.tar.zst
        key: frameworks_libs_net@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_voip.tar.zst
        key: frameworks_opt_net_voip@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_wifi.tar.zst
        key: frameworks_opt_net_wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Bluetooth.tar.zst
        key: packages_apps_Bluetooth@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_CellBroadcastReceiver.tar.zst
        key: packages_apps_CellBroadcastReceiver@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_EmergencyInfo.tar.zst
        key: packages_apps_EmergencyInfo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_ManagedProvisioning.tar.zst
        key: packages_apps_ManagedProvisioning@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Settings.tar.zst
        key: packages_apps_Settings@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_CellBroadcastService.tar.zst
        key: packages_modules_CellBroadcastService@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Connectivity.tar.zst
        key: packages_modules_Connectivity@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_DnsResolver.tar.zst
        key: packages_modules_DnsResolver@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_ExtServices.tar.zst
        key: packages_modules_ExtServices@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_NetworkStack.tar.zst
        key: packages_modules_NetworkStack@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Permission.tar.zst
        key: packages_modules_Permission@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Scheduling.tar.zst
        key: packages_modules_Scheduling@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_StatsD.tar.zst
        key: packages_modules_StatsD@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Wifi.tar.zst
        key: packages_modules_Wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_common.tar.zst
        key: packages_modules_common@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_providers_MediaProvider.tar.zst
        key: packages_providers_MediaProvider@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_services_Car.tar.zst
        key: packages_services_Car@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libsysprop.tar.zst
        key: system_libsysprop@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_netd.tar.zst
        key: system_netd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_timezone.tar.zst
        key: system_timezone@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_apifinder.tar.zst
        key: tools_apifinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_metalava.tar.zst
        key: tools_metalava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
    - run: bash steps/build_25.sh