
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_26:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2
    - uses: actions/cache@v4
      with:
        path: cache/art.tar.zst
        key: art@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_auto.tar.zst
        key: external_auto@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_bouncycastle.tar.zst
        key: external_bouncycastle@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_dagger2.tar.zst
        key: external_dagger2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_error_prone.tar.zst
        key: external_error_prone@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_firebase-messaging.tar.zst
        key: external_firebase-messaging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_guava.tar.zst
        key: external_guava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_ims.tar.zst
        key: external_ims@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_jsr305.tar.zst
        key: external_jsr305@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_jsr330.tar.zst
        key: external_jsr330@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_kotlinc.tar.zst
        key: external_kotlinc@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_kotlinx.coroutines.tar.zst
        key: external_kotlinx.coroutines@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_ksoap2.tar.zst
        key: external_ksoap2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_lottie.tar.zst
        key: external_lottie@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_nanohttpd.tar.zst
        key: external_nanohttpd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_setupdesign.tar.zst
        key: external_setupdesign@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_modules-utils.tar.zst
        key: frameworks_libs_modules-utils@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_net.tar.zst
        key: frameworks_libs_net@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_service_entitlement.tar.zst
        key: frameworks_libs_service_entitlement@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_libs_systemui.tar.zst
        key: frameworks_libs_systemui@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_ims.tar.zst
        key: frameworks_opt_net_ims@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_net_wifi.tar.zst
        key: frameworks_opt_net_wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libcore.tar.zst
        key: libcore@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Car_libs.tar.zst
        key: packages_apps_Car_libs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_CellBroadcastReceiver.tar.zst
        key: packages_apps_CellBroadcastReceiver@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_ImsServiceEntitlement.tar.zst
        key: packages_apps_ImsServiceEntitlement@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Connectivity.tar.zst
        key: packages_modules_Connectivity@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_StatsD.tar.zst
        key: packages_modules_StatsD@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_Wifi.tar.zst
        key: packages_modules_Wifi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_services_Car.tar.zst
        key: packages_services_Car@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_apifinder.tar.zst
        key: tools_apifinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_metalava.tar.zst
        key: tools_metalava@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/tools_platform-compat.tar.zst
        key: tools_platform-compat@${{ env.branch }}
    - run: bash steps/build_26.sh