
name: AOSP Build
on:
  push:
    branches:
    - main
env:
  branch: 'android-12.0.0_r1'
jobs:
  build_step1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-python@v4
      with:
        python-version: "2.7"
    - name: Download get_clang_version.py
      run: |
        curl "https://android.googlesource.com/platform/build/soong/+/refs/heads/master/scripts/get_clang_version.py?format=TEXT" | base64 -d > $GITHUB_WORKSPACE/get_clang_version.py
        mkdir -p aosp

    - name: Restore Cache build/make
      id: build_make
      uses: actions/cache@v3
      with:
        path: aosp/build/make
        key: build_make@${{ env.branch }}
        restore-keys: build_make@${{ env.branch }}
    - name: Clone project build/make
      if: steps.build_make.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build
        mv build make && mkdir build && mv make build/
        sed -i 's/^PRODUCT_EXTRA_VNDK_VERSIONS/#PRODUCT_EXTRA_VNDK_VERSIONS/g' build/make/target/product/gsi_release.mk
    - name: Restore Cache bionic
      id: bionic
      uses: actions/cache@v3
      with:
        path: aosp/bionic
        key: bionic@${{ env.branch }}
        restore-keys: bionic@${{ env.branch }}
    - name: Clone project bionic
      if: steps.bionic.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform bionic
    - name: Restore Cache build/blueprint
      id: build_blueprint
      uses: actions/cache@v3
      with:
        path: aosp/build/blueprint
        key: build_blueprint@${{ env.branch }}
        restore-keys: build_blueprint@${{ env.branch }}
    - name: Clone project build/blueprint
      if: steps.build_blueprint.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build/blueprint
    - name: Restore Cache build/soong
      id: build_soong
      uses: actions/cache@v3
      with:
        path: aosp/build/soong
        key: build_soong@${{ env.branch }}
        restore-keys: build_soong@${{ env.branch }}
    - name: Clone project build/soong
      if: steps.build_soong.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build/soong
    - name: Restore Cache external/compiler-rt
      id: external_compiler-rt
      uses: actions/cache@v3
      with:
        path: aosp/external/compiler-rt
        key: external_compiler-rt@${{ env.branch }}
        restore-keys: external_compiler-rt@${{ env.branch }}
    - name: Clone project external/compiler-rt
      if: steps.external_compiler-rt.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/compiler-rt
    - name: Restore Cache external/golang-protobuf
      id: external_golang-protobuf
      uses: actions/cache@v3
      with:
        path: aosp/external/golang-protobuf
        key: external_golang-protobuf@${{ env.branch }}
        restore-keys: external_golang-protobuf@${{ env.branch }}
    - name: Clone project external/golang-protobuf
      if: steps.external_golang-protobuf.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/golang-protobuf
    - name: Restore Cache external/jemalloc_new
      id: external_jemalloc_new
      uses: actions/cache@v3
      with:
        path: aosp/external/jemalloc_new
        key: external_jemalloc_new@${{ env.branch }}
        restore-keys: external_jemalloc_new@${{ env.branch }}
    - name: Clone project external/jemalloc_new
      if: steps.external_jemalloc_new.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/jemalloc_new
    - name: Restore Cache external/rust/crates/codespan-reporting
      id: external_rust_crates_codespan-reporting
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/codespan-reporting
        key: external_rust_crates_codespan-reporting@${{ env.branch }}
        restore-keys: external_rust_crates_codespan-reporting@${{ env.branch }}
    - name: Clone project external/rust/crates/codespan-reporting
      if: steps.external_rust_crates_codespan-reporting.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/codespan-reporting
    - name: Restore Cache external/rust/crates/heck
      id: external_rust_crates_heck
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/heck
        key: external_rust_crates_heck@${{ env.branch }}
        restore-keys: external_rust_crates_heck@${{ env.branch }}
    - name: Clone project external/rust/crates/heck
      if: steps.external_rust_crates_heck.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/heck
    - name: Restore Cache external/rust/crates/lock_api
      id: external_rust_crates_lock_api
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/lock_api
        key: external_rust_crates_lock_api@${{ env.branch }}
        restore-keys: external_rust_crates_lock_api@${{ env.branch }}
    - name: Clone project external/rust/crates/lock_api
      if: steps.external_rust_crates_lock_api.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/lock_api
    - name: Restore Cache external/rust/crates/proc-macro2
      id: external_rust_crates_proc-macro2
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/proc-macro2
        key: external_rust_crates_proc-macro2@${{ env.branch }}
        restore-keys: external_rust_crates_proc-macro2@${{ env.branch }}
    - name: Clone project external/rust/crates/proc-macro2
      if: steps.external_rust_crates_proc-macro2.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/proc-macro2
    - name: Restore Cache external/rust/crates/protobuf
      id: external_rust_crates_protobuf
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/protobuf
        key: external_rust_crates_protobuf@${{ env.branch }}
        restore-keys: external_rust_crates_protobuf@${{ env.branch }}
    - name: Clone project external/rust/crates/protobuf
      if: steps.external_rust_crates_protobuf.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/protobuf
    - name: Restore Cache external/starlark-go
      id: external_starlark-go
      uses: actions/cache@v3
      with:
        path: aosp/external/starlark-go
        key: external_starlark-go@${{ env.branch }}
        restore-keys: external_starlark-go@${{ env.branch }}
    - name: Clone project external/starlark-go
      if: steps.external_starlark-go.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/starlark-go
    - name: Restore Cache prebuilts/build-tools
      id: prebuilts_build-tools
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/build-tools
        key: prebuilts_build-tools@${{ env.branch }}
        restore-keys: prebuilts_build-tools@${{ env.branch }}
    - name: Clone project prebuilts/build-tools
      if: steps.prebuilts_build-tools.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/build-tools linux-x86/bin linux-x86/lib64 path common
    - name: Restore Cache prebuilts/clang-tools
      id: prebuilts_clang-tools
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/clang-tools
        key: prebuilts_clang-tools@${{ env.branch }}
        restore-keys: prebuilts_clang-tools@${{ env.branch }}
    - name: Clone project prebuilts/clang-tools
      if: steps.prebuilts_clang-tools.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/clang-tools linux-x86/bin linux-x86/lib64/clang
    - name: Restore Cache prebuilts/clang/host/linux-x86
      id: prebuilts_clang_host_linux-x86
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/clang/host/linux-x86
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
        restore-keys: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - name: Clone project prebuilts/clang/host/linux-x86
      if: steps.prebuilts_clang_host_linux-x86.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/clang/host/linux-x86 $(python ${GITHUB_WORKSPACE}/get_clang_version.py) clang-r416183b soong
    - name: Restore Cache prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
      id: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
        key: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8@${{ env.branch }}
        restore-keys: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8@${{ env.branch }}
    - name: Clone project prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
      if: steps.prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 sysroot lib/gcc/x86_64-linux/4.8.3 x86_64-linux/lib64 x86_64-linux/lib32
    - name: Restore Cache prebuilts/rust
      id: prebuilts_rust
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/rust
        key: prebuilts_rust@${{ env.branch }}
        restore-keys: prebuilts_rust@${{ env.branch }}
    - name: Clone project prebuilts/rust
      if: steps.prebuilts_rust.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/rust bootstrap linux-x86/1.51.0
    - name: Restore Cache system/core
      id: system_core
      uses: actions/cache@v3
      with:
        path: aosp/system/core
        key: system_core@${{ env.branch }}
        restore-keys: system_core@${{ env.branch }}
    - name: Clone project system/core
      if: steps.system_core.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/core
    - name: Restore Cache system/logging
      id: system_logging
      uses: actions/cache@v3
      with:
        path: aosp/system/logging
        key: system_logging@${{ env.branch }}
        restore-keys: system_logging@${{ env.branch }}
    - name: Clone project system/logging
      if: steps.system_logging.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/logging
    - name: Restore Cache system/sepolicy
      id: system_sepolicy
      uses: actions/cache@v3
      with:
        path: aosp/system/sepolicy
        key: system_sepolicy@${{ env.branch }}
        restore-keys: system_sepolicy@${{ env.branch }}
    - name: Clone project system/sepolicy
      if: steps.system_sepolicy.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/sepolicy

    - name: Download Release
      run: |
        source $GITHUB_WORKSPACE/envsetup.sh
        download_release bionic-0 bionic/ android-12.0.0_r1-0
        download_release external_arm-optimized-routines-0 external/arm-optimized-routines/ android-12.0.0_r1-0
        download_release external_crosvm-0 external/crosvm/ android-12.0.0_r1-0
        download_release external_gwp_asan-0 external/gwp_asan/ android-12.0.0_r1-0
        download_release external_rust_crates_bytes-0 external/rust/crates/bytes/ android-12.0.0_r1-0
        download_release external_rust_crates_downcast-rs-0 external/rust/crates/downcast-rs/ android-12.0.0_r1-0
        download_release external_rust_crates_either-0 external/rust/crates/either/ android-12.0.0_r1-0
        download_release external_rust_crates_fallible-iterator-0 external/rust/crates/fallible-iterator/ android-12.0.0_r1-0
        download_release external_rust_crates_fallible-streaming-iterator-0 external/rust/crates/fallible-streaming-iterator/ android-12.0.0_r1-0
        download_release external_rust_crates_glob-0 external/rust/crates/glob/ android-12.0.0_r1-0
        download_release external_rust_crates_lazycell-0 external/rust/crates/lazycell/ android-12.0.0_r1-0
        download_release external_rust_crates_paste-0 external/rust/crates/paste/ android-12.0.0_r1-0
        download_release external_rust_crates_peeking_take_while-0 external/rust/crates/peeking_take_while/ android-12.0.0_r1-0
        download_release external_rust_crates_proc-macro-hack-0 external/rust/crates/proc-macro-hack/ android-12.0.0_r1-0
        download_release external_rust_crates_regex-syntax-0 external/rust/crates/regex-syntax/ android-12.0.0_r1-0
        download_release external_rust_crates_rustc-hash-0 external/rust/crates/rustc-hash/ android-12.0.0_r1-0
        download_release external_rust_crates_scopeguard-0 external/rust/crates/scopeguard/ android-12.0.0_r1-0
        download_release external_rust_crates_shlex-0 external/rust/crates/shlex/ android-12.0.0_r1-0
        download_release external_rust_crates_termcolor-0 external/rust/crates/termcolor/ android-12.0.0_r1-0
        download_release external_rust_crates_unicode-segmentation-0 external/rust/crates/unicode-segmentation/ android-12.0.0_r1-0
        download_release external_rust_crates_unicode-width-0 external/rust/crates/unicode-width/ android-12.0.0_r1-0
        download_release external_rust_crates_unicode-xid-0 external/rust/crates/unicode-xid/ android-12.0.0_r1-0
        download_release external_scudo-0 external/scudo/ android-12.0.0_r1-0
        download_release system_bt-0 system/bt/ android-12.0.0_r1-0
        download_release system_core-0 system/core/ android-12.0.0_r1-0
    - name: Start Soong
      run: |
        pushd aosp
        export TOP=$(pwd)
        cp build/make/core/root.mk Makefile
        ln -sf make/CleanSpec.mk build/ && ln -sf make/core build/
        ln -sf make/target build/ && ln -sf make/tools build/
        ln -sf build/soong/root.bp Android.bp
        mkdir -p prebuilts/go && touch prebuilts/go/.out-dir
        ln -sf $GOROOT_1_19_X64 prebuilts/go/linux-x86
        mkdir -p out/soong/.minibootstrap out/soong/.bootstrap/bin
        ln -sf $GITHUB_WORKSPACE/soong_build out/soong/.bootstrap/bin
        ln -sf $GITHUB_WORKSPACE/bpglob out/soong/.minibootstrap
        cp $GITHUB_WORKSPACE/ckati prebuilts/build-tools/linux-x86/bin
        mkdir -p prebuiltlibs && cp $GITHUB_WORKSPACE/Android.bp prebuiltlibs/
        mkdir -p prebuiltlibs && cp $GITHUB_WORKSPACE/rust_prebuilt.list prebuiltlibs/
        echo "eng.buildbot.$(date '+%Y%m%d.%H%M%S')" > out/soong/build_number.txt
        GOROOT=$TOP/prebuilts/go/linux-x86 $GITHUB_WORKSPACE/soong_ui --make-mode --skip-ninja --skip-kati --skip-soong-tests --skip-write-modules -j1 TARGET_PRODUCT=aosp_x86_64 TARGET_BUILD_VARIANT=eng ALLOW_MISSING_DEPENDENCIES=true BUILD_BROKEN_DISABLE_BAZEL=1 nothing
        $GITHUB_WORKSPACE/build.sh
        du -ah -d1 out/soong |sort -h
        du -ah -d1 . |sort -h

    - name: Archive bionic-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: bionic-1.tar.xz
        path: aosp/bionic-1.tar.xz
    - name: Archive external_rust_crates_codespan-reporting-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_rust_crates_codespan-reporting-1.tar.xz
        path: aosp/external_rust_crates_codespan-reporting-1.tar.xz
    - name: Archive external_rust_crates_heck-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_rust_crates_heck-1.tar.xz
        path: aosp/external_rust_crates_heck-1.tar.xz
    - name: Archive external_rust_crates_lock_api-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_rust_crates_lock_api-1.tar.xz
        path: aosp/external_rust_crates_lock_api-1.tar.xz
    - name: Archive external_rust_crates_proc-macro2-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_rust_crates_proc-macro2-1.tar.xz
        path: aosp/external_rust_crates_proc-macro2-1.tar.xz
    - name: Archive external_rust_crates_protobuf-1.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_rust_crates_protobuf-1.tar.xz
        path: aosp/external_rust_crates_protobuf-1.tar.xz

    - uses: softprops/action-gh-release@master
      with:
        name: ${{ env.branch }}-1
        tag_name: ${{ env.branch }}-1
        files: |
          aosp/bionic-1.tar.xz
          aosp/external_rust_crates_codespan-reporting-1.tar.xz
          aosp/external_rust_crates_heck-1.tar.xz
          aosp/external_rust_crates_lock_api-1.tar.xz
          aosp/external_rust_crates_proc-macro2-1.tar.xz
          aosp/external_rust_crates_protobuf-1.tar.xz
