
name: AOSP Build
on:
  push:
    branches:
    - main
env:
  branch: 'android-12.0.0_r1'
jobs:
  build_step5:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-python@v4
      with:
        python-version: "2.7"
    - name: Download get_clang_version.py
      run: |
        curl 'https://android.googlesource.com/platform/build/soong/+/refs/heads/master/scripts/get_clang_version.py?format=TEXT' | base64 -d > $GITHUB_WORKSPACE/get_clang_version.py
        mkdir -p aosp

    - name: Restore Cache build/make
      id: build_make
      uses: actions/cache@v3
      with:
        path: aosp/build/make
        key: build_make@${{ env.branch }}
        restore-keys: build_make@${{ env.branch }}
    - name: Clone project build/make
      if: steps.build_make.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build
        mv build make && mkdir build && mv make build/
        sed -i 's/^PRODUCT_EXTRA_VNDK_VERSIONS/#PRODUCT_EXTRA_VNDK_VERSIONS/g' build/make/target/product/gsi_release.mk

    - name: Restore Cache bionic
      id: bionic
      uses: actions/cache@v3
      with:
        path: aosp/bionic
        key: bionic@${{ env.branch }}
        restore-keys: bionic@${{ env.branch }}
    - name: Clone project bionic
      if: steps.bionic.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform bionic

    - name: Restore Cache build/blueprint
      id: build_blueprint
      uses: actions/cache@v3
      with:
        path: aosp/build/blueprint
        key: build_blueprint@${{ env.branch }}
        restore-keys: build_blueprint@${{ env.branch }}
    - name: Clone project build/blueprint
      if: steps.build_blueprint.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build/blueprint

    - name: Restore Cache build/soong
      id: build_soong
      uses: actions/cache@v3
      with:
        path: aosp/build/soong
        key: build_soong@${{ env.branch }}
        restore-keys: build_soong@${{ env.branch }}
    - name: Clone project build/soong
      if: steps.build_soong.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform build/soong

    - name: Restore Cache external/golang-protobuf
      id: external_golang-protobuf
      uses: actions/cache@v3
      with:
        path: aosp/external/golang-protobuf
        key: external_golang-protobuf@${{ env.branch }}
        restore-keys: external_golang-protobuf@${{ env.branch }}
    - name: Clone project external/golang-protobuf
      if: steps.external_golang-protobuf.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/golang-protobuf

    - name: Restore Cache external/libcxx
      id: external_libcxx
      uses: actions/cache@v3
      with:
        path: aosp/external/libcxx
        key: external_libcxx@${{ env.branch }}
        restore-keys: external_libcxx@${{ env.branch }}
    - name: Clone project external/libcxx
      if: steps.external_libcxx.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/libcxx

    - name: Restore Cache external/libcxxabi
      id: external_libcxxabi
      uses: actions/cache@v3
      with:
        path: aosp/external/libcxxabi
        key: external_libcxxabi@${{ env.branch }}
        restore-keys: external_libcxxabi@${{ env.branch }}
    - name: Clone project external/libcxxabi
      if: steps.external_libcxxabi.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/libcxxabi

    - name: Restore Cache external/perfetto
      id: external_perfetto
      uses: actions/cache@v3
      with:
        path: aosp/external/perfetto
        key: external_perfetto@${{ env.branch }}
        restore-keys: external_perfetto@${{ env.branch }}
    - name: Clone project external/perfetto
      if: steps.external_perfetto.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/perfetto

    - name: Restore Cache external/starlark-go
      id: external_starlark-go
      uses: actions/cache@v3
      with:
        path: aosp/external/starlark-go
        key: external_starlark-go@${{ env.branch }}
        restore-keys: external_starlark-go@${{ env.branch }}
    - name: Clone project external/starlark-go
      if: steps.external_starlark-go.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/starlark-go

    - name: Restore Cache external/wayland
      id: external_wayland
      uses: actions/cache@v3
      with:
        path: aosp/external/wayland
        key: external_wayland@${{ env.branch }}
        restore-keys: external_wayland@${{ env.branch }}
    - name: Clone project external/wayland
      if: steps.external_wayland.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/wayland

    - name: Restore Cache prebuilts/build-tools
      id: prebuilts_build-tools
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/build-tools
        key: prebuilts_build-tools@${{ env.branch }}
        restore-keys: prebuilts_build-tools@${{ env.branch }}
    - name: Clone project prebuilts/build-tools
      if: steps.prebuilts_build-tools.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/build-tools linux-x86/bin linux-x86/lib64 path common

    - name: Restore Cache prebuilts/clang-tools
      id: prebuilts_clang-tools
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/clang-tools
        key: prebuilts_clang-tools@${{ env.branch }}
        restore-keys: prebuilts_clang-tools@${{ env.branch }}
    - name: Clone project prebuilts/clang-tools
      if: steps.prebuilts_clang-tools.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/clang-tools linux-x86/bin linux-x86/lib64/clang

    - name: Restore Cache prebuilts/clang/host/linux-x86
      id: prebuilts_clang_host_linux-x86
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/clang/host/linux-x86
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
        restore-keys: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - name: Clone project prebuilts/clang/host/linux-x86
      if: steps.prebuilts_clang_host_linux-x86.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/clang/host/linux-x86 $(python ${GITHUB_WORKSPACE}/get_clang_version.py) clang-r416183b soong

    - name: Restore Cache prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
      id: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
        key: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8@${{ env.branch }}
        restore-keys: prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8@${{ env.branch }}
    - name: Clone project prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
      if: steps.prebuilts_gcc_linux-x86_host_x86_64-linux-glibc2_17-4_8.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 sysroot lib/gcc/x86_64-linux/4.8.3 x86_64-linux/lib64 x86_64-linux/lib32

    - name: Restore Cache prebuilts/misc
      id: prebuilts_misc
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/misc
        key: prebuilts_misc@${{ env.branch }}
        restore-keys: prebuilts_misc@${{ env.branch }}
    - name: Clone project prebuilts/misc
      if: steps.prebuilts_misc.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse_exclude prebuilts/misc "!/common/robolectric" "!/darwin-x86" "!/darwin-x86_64" "!/gdbserver"

    - name: Restore Cache prebuilts/ndk
      id: prebuilts_ndk
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/ndk
        key: prebuilts_ndk@${{ env.branch }}
        restore-keys: prebuilts_ndk@${{ env.branch }}
    - name: Clone project prebuilts/ndk
      if: steps.prebuilts_ndk.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/ndk current

    - name: Restore Cache prebuilts/rust
      id: prebuilts_rust
      uses: actions/cache@v3
      with:
        path: aosp/prebuilts/rust
        key: prebuilts_rust@${{ env.branch }}
        restore-keys: prebuilts_rust@${{ env.branch }}
    - name: Clone project prebuilts/rust
      if: steps.prebuilts_rust.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_sparse prebuilts/rust bootstrap linux-x86/1.51.0

    - name: Restore Cache system/core
      id: system_core
      uses: actions/cache@v3
      with:
        path: aosp/system/core
        key: system_core@${{ env.branch }}
        restore-keys: system_core@${{ env.branch }}
    - name: Clone project system/core
      if: steps.system_core.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/core

    - name: Restore Cache system/logging
      id: system_logging
      uses: actions/cache@v3
      with:
        path: aosp/system/logging
        key: system_logging@${{ env.branch }}
        restore-keys: system_logging@${{ env.branch }}
    - name: Clone project system/logging
      if: steps.system_logging.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/logging

    - name: Restore Cache system/sepolicy
      id: system_sepolicy
      uses: actions/cache@v3
      with:
        path: aosp/system/sepolicy
        key: system_sepolicy@${{ env.branch }}
        restore-keys: system_sepolicy@${{ env.branch }}
    - name: Clone project system/sepolicy
      if: steps.system_sepolicy.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform system/sepolicy

    - name: Restore Cache bionic-4.tar.xz
      id: bionic-4
      uses: actions/cache@v3
      with:
        path: aosp/bionic-4.tar.xz
        key: bionic-4
        restore-keys: bionic-4
    - name: Clone project bionic-4.tar.xz
      if: steps.bionic-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release bionic-4.tar.xz android-12.0.0_r1-4

    - name: Restore Cache external_arm-optimized-routines-0.tar.xz
      id: external_arm-optimized-routines-0
      uses: actions/cache@v3
      with:
        path: aosp/external_arm-optimized-routines-0.tar.xz
        key: external_arm-optimized-routines-0
        restore-keys: external_arm-optimized-routines-0
    - name: Clone project external_arm-optimized-routines-0.tar.xz
      if: steps.external_arm-optimized-routines-0.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_arm-optimized-routines-0.tar.xz android-12.0.0_r1-0

    - name: Restore Cache external_gwp_asan-4.tar.xz
      id: external_gwp_asan-4
      uses: actions/cache@v3
      with:
        path: aosp/external_gwp_asan-4.tar.xz
        key: external_gwp_asan-4
        restore-keys: external_gwp_asan-4
    - name: Clone project external_gwp_asan-4.tar.xz
      if: steps.external_gwp_asan-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_gwp_asan-4.tar.xz android-12.0.0_r1-4

    - name: Restore Cache external_libcxx-3.tar.xz
      id: external_libcxx-3
      uses: actions/cache@v3
      with:
        path: aosp/external_libcxx-3.tar.xz
        key: external_libcxx-3
        restore-keys: external_libcxx-3
    - name: Clone project external_libcxx-3.tar.xz
      if: steps.external_libcxx-3.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_libcxx-3.tar.xz android-12.0.0_r1-3

    - name: Restore Cache external_libcxxabi-2.tar.xz
      id: external_libcxxabi-2
      uses: actions/cache@v3
      with:
        path: aosp/external_libcxxabi-2.tar.xz
        key: external_libcxxabi-2
        restore-keys: external_libcxxabi-2
    - name: Clone project external_libcxxabi-2.tar.xz
      if: steps.external_libcxxabi-2.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_libcxxabi-2.tar.xz android-12.0.0_r1-2

    - name: Restore Cache external_libffi-4.tar.xz
      id: external_libffi-4
      uses: actions/cache@v3
      with:
        path: aosp/external_libffi-4.tar.xz
        key: external_libffi-4
        restore-keys: external_libffi-4
    - name: Clone project external_libffi-4.tar.xz
      if: steps.external_libffi-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_libffi-4.tar.xz android-12.0.0_r1-4

    - name: Restore Cache external_protobuf-4.tar.xz
      id: external_protobuf-4
      uses: actions/cache@v3
      with:
        path: aosp/external_protobuf-4.tar.xz
        key: external_protobuf-4
        restore-keys: external_protobuf-4
    - name: Clone project external_protobuf-4.tar.xz
      if: steps.external_protobuf-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_protobuf-4.tar.xz android-12.0.0_r1-4

    - name: Restore Cache external_scudo-0.tar.xz
      id: external_scudo-0
      uses: actions/cache@v3
      with:
        path: aosp/external_scudo-0.tar.xz
        key: external_scudo-0
        restore-keys: external_scudo-0
    - name: Clone project external_scudo-0.tar.xz
      if: steps.external_scudo-0.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_scudo-0.tar.xz android-12.0.0_r1-0

    - name: Restore Cache external_wayland-4.tar.xz
      id: external_wayland-4
      uses: actions/cache@v3
      with:
        path: aosp/external_wayland-4.tar.xz
        key: external_wayland-4
        restore-keys: external_wayland-4
    - name: Clone project external_wayland-4.tar.xz
      if: steps.external_wayland-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_wayland-4.tar.xz android-12.0.0_r1-4

    - name: Restore Cache external_zlib-2.tar.xz
      id: external_zlib-2
      uses: actions/cache@v3
      with:
        path: aosp/external_zlib-2.tar.xz
        key: external_zlib-2
        restore-keys: external_zlib-2
    - name: Clone project external_zlib-2.tar.xz
      if: steps.external_zlib-2.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release external_zlib-2.tar.xz android-12.0.0_r1-2

    - name: Restore Cache system_logging-4.tar.xz
      id: system_logging-4
      uses: actions/cache@v3
      with:
        path: aosp/system_logging-4.tar.xz
        key: system_logging-4
        restore-keys: system_logging-4
    - name: Clone project system_logging-4.tar.xz
      if: steps.system_logging-4.outputs.cache-hit != 'true'
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        download_release system_logging-4.tar.xz android-12.0.0_r1-4

    - name: Extract Artifacts
      run: |
        cd aosp && source $GITHUB_WORKSPACE/envsetup.sh
        extract_tar bionic-4.tar.xz bionic/
        extract_tar external_arm-optimized-routines-0.tar.xz external/arm-optimized-routines/
        extract_tar external_gwp_asan-4.tar.xz external/gwp_asan/
        extract_tar external_libcxx-3.tar.xz external/libcxx/
        extract_tar external_libcxxabi-2.tar.xz external/libcxxabi/
        extract_tar external_libffi-4.tar.xz external/libffi/
        extract_tar external_protobuf-4.tar.xz external/protobuf/
        extract_tar external_scudo-0.tar.xz external/scudo/
        extract_tar external_wayland-4.tar.xz external/wayland/
        extract_tar external_zlib-2.tar.xz external/zlib/
        extract_tar system_logging-4.tar.xz system/logging/

    - name: Start Soong
      run: |
        pushd aosp
        export TOP=$(pwd)
        cp build/make/core/root.mk Makefile
        ln -sf make/CleanSpec.mk build/ && ln -sf make/core build/
        ln -sf make/target build/ && ln -sf make/tools build/
        ln -sf build/soong/root.bp Android.bp
        mkdir -p prebuilts/jdk && touch prebuilts/jdk/.find-ignore
        mkdir -p prebuilts/jdk/jdk8 && mkdir -p prebuilts/jdk/jdk11
        ln -sf $JAVA_HOME_8_X64 prebuilts/jdk/jdk8/linux-x86
        ln -sf $JAVA_HOME_11_X64 prebuilts/jdk/jdk11/linux-x86
        mkdir -p prebuilts/go && touch prebuilts/go/.find-ignore
        ln -sf $GOROOT_1_19_X64 prebuilts/go/linux-x86
        mkdir -p out/soong/.minibootstrap out/soong/.bootstrap/bin
        ln -sf $GITHUB_WORKSPACE/soong_build out/soong/.bootstrap/bin
        ln -sf $GITHUB_WORKSPACE/bpglob out/soong/.minibootstrap
        cp $GITHUB_WORKSPACE/ckati prebuilts/build-tools/linux-x86/bin
        mkdir -p prebuiltlibs && cp $GITHUB_WORKSPACE/Android.bp prebuiltlibs/
        mkdir -p prebuiltlibs && cp $GITHUB_WORKSPACE/rust_prebuilt.list prebuiltlibs/
        echo "eng.buildbot.$(date '+%Y%m%d.%H%M%S')" > out/soong/build_number.txt
        mkdir -p external/compiler-rt/lib/cfi/ && curl 'https://android.googlesource.com/platform/external/compiler-rt/+/android12-gsi/lib/cfi/cfi_blocklist.txt?format=TEXT' | base64 -d > external/compiler-rt/lib/cfi/cfi_blocklist.txt
        $GITHUB_WORKSPACE/scripts/build5.sh
        df -h

    - uses: softprops/action-gh-release@master
      with:
        name: ${{ env.branch }}-5
        tag_name: ${{ env.branch }}-5
        files: |
          aosp/external_perfetto-5.tar.xz
          aosp/external_wayland-5.tar.xz

    - name: Archive external_perfetto-5.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_perfetto-5.tar.xz
        path: aosp/external_perfetto-5.tar.xz

    - name: Archive external_wayland-5.tar.xz
      uses: actions/upload-artifact@v3
      with:
        name: external_wayland-5.tar.xz
        path: aosp/external_wayland-5.tar.xz

    - name: Restore Cache external_perfetto-5.tar.xz
      id: external_perfetto-5
      uses: actions/cache@v3
      with:
        path: aosp/external_perfetto-5.tar.xz
        key: external_perfetto-5
        restore-keys: external_perfetto-5

    - name: Restore Cache external_wayland-5.tar.xz
      id: external_wayland-5
      uses: actions/cache@v3
      with:
        path: aosp/external_wayland-5.tar.xz
        key: external_wayland-5
        restore-keys: external_wayland-5