
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions: write-all
jobs:
  build_kati:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - uses: actions/cache@v4
      with:
        path: cache/soong_outputs.tar.zst
        key: soong_outputs@${{ env.branch }}
    - run: bash kati/kati_download.sh
