
name: AOSP Build
on:
  push:
    branches: main
env:
  branch: 'android12-gsi'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions: write-all
jobs:
  build_kati:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - uses: actions/cache@v4
      with:
        path: cache/soong_outputs.tar.zst
        key: soong_outputs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/bionic.tar.zst
        key: bionic@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/bootable_recovery.tar.zst
        key: bootable_recovery@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_make.tar.zst
        key: build_make@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/build_soong.tar.zst
        key: build_soong@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_generic_goldfish.tar.zst
        key: device_generic_goldfish@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_generic_goldfish-opengl.tar.zst
        key: device_generic_goldfish-opengl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_google_cuttlefish.tar.zst
        key: device_google_cuttlefish@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_google_cuttlefish_prebuilts.tar.zst
        key: device_google_cuttlefish_prebuilts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/device_sample.tar.zst
        key: device_sample@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_android-clat.tar.zst
        key: external_android-clat@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_avb.tar.zst
        key: external_avb@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_boringssl.tar.zst
        key: external_boringssl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_brotli.tar.zst
        key: external_brotli@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_chromium-webview.tar.zst
        key: external_chromium-webview@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_clang.tar.zst
        key: external_clang@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_compiler-rt.tar.zst
        key: external_compiler-rt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_e2fsprogs.tar.zst
        key: external_e2fsprogs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_expat.tar.zst
        key: external_expat@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_fec.tar.zst
        key: external_fec@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_fmtlib.tar.zst
        key: external_fmtlib@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_hyphenation-patterns.tar.zst
        key: external_hyphenation-patterns@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_icu.tar.zst
        key: external_icu@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_ipsec-tools.tar.zst
        key: external_ipsec-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcap.tar.zst
        key: external_libcap@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxx.tar.zst
        key: external_libcxx@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libcxxabi.tar.zst
        key: external_libcxxabi@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libdrm.tar.zst
        key: external_libdrm@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libjpeg-turbo.tar.zst
        key: external_libjpeg-turbo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libnl.tar.zst
        key: external_libnl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_libyuv.tar.zst
        key: external_libyuv@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_lzma.tar.zst
        key: external_lzma@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_mdnsresponder.tar.zst
        key: external_mdnsresponder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_mesa3d.tar.zst
        key: external_mesa3d@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_minigbm.tar.zst
        key: external_minigbm@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_mtpd.tar.zst
        key: external_mtpd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_nanopb-c.tar.zst
        key: external_nanopb-c@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_pcre.tar.zst
        key: external_pcre@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_perfetto.tar.zst
        key: external_perfetto@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_protobuf.tar.zst
        key: external_protobuf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_selinux.tar.zst
        key: external_selinux@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_skia.tar.zst
        key: external_skia@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_vulkan-headers.tar.zst
        key: external_vulkan-headers@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_wpa_supplicant_8.tar.zst
        key: external_wpa_supplicant_8@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_zlib.tar.zst
        key: external_zlib@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/external_zxing.tar.zst
        key: external_zxing@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_av.tar.zst
        key: frameworks_av@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_base.tar.zst
        key: frameworks_base@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_ex.tar.zst
        key: frameworks_ex@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_minikin.tar.zst
        key: frameworks_minikin@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_native.tar.zst
        key: frameworks_native@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_chips.tar.zst
        key: frameworks_opt_chips@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_colorpicker.tar.zst
        key: frameworks_opt_colorpicker@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_telephony.tar.zst
        key: frameworks_opt_telephony@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_opt_timezonepicker.tar.zst
        key: frameworks_opt_timezonepicker@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/frameworks_rs.tar.zst
        key: frameworks_rs@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_google_camera.tar.zst
        key: hardware_google_camera@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_google_pixel.tar.zst
        key: hardware_google_pixel@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_google_pixel-sepolicy.tar.zst
        key: hardware_google_pixel-sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_interfaces.tar.zst
        key: hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware.tar.zst
        key: hardware_libhardware@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_libhardware_legacy.tar.zst
        key: hardware_libhardware_legacy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/hardware_ril.tar.zst
        key: hardware_ril@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/kernel_prebuilts_5.10_x86_64.tar.zst
        key: kernel_prebuilts_5.10_x86_64@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/kernel_prebuilts_common-modules_virtual-device_5.10_x86-64.tar.zst
        key: kernel_prebuilts_common-modules_virtual-device_5.10_x86-64@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/libnativehelper.tar.zst
        key: libnativehelper@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Browser2.tar.zst
        key: packages_apps_Browser2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Calendar.tar.zst
        key: packages_apps_Calendar@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Camera2.tar.zst
        key: packages_apps_Camera2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_CarrierConfig.tar.zst
        key: packages_apps_CarrierConfig@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Contacts.tar.zst
        key: packages_apps_Contacts@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_DeskClock.tar.zst
        key: packages_apps_DeskClock@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Dialer.tar.zst
        key: packages_apps_Dialer@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_EmergencyInfo.tar.zst
        key: packages_apps_EmergencyInfo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Gallery.tar.zst
        key: packages_apps_Gallery@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Gallery2.tar.zst
        key: packages_apps_Gallery2@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_ImsServiceEntitlement.tar.zst
        key: packages_apps_ImsServiceEntitlement@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Launcher3.tar.zst
        key: packages_apps_Launcher3@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Messaging.tar.zst
        key: packages_apps_Messaging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Music.tar.zst
        key: packages_apps_Music@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_OneTimeInitializer.tar.zst
        key: packages_apps_OneTimeInitializer@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Provision.tar.zst
        key: packages_apps_Provision@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_QuickSearchBox.tar.zst
        key: packages_apps_QuickSearchBox@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_RemoteProvisioner.tar.zst
        key: packages_apps_RemoteProvisioner@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_Settings.tar.zst
        key: packages_apps_Settings@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_SettingsIntelligence.tar.zst
        key: packages_apps_SettingsIntelligence@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_StorageManager.tar.zst
        key: packages_apps_StorageManager@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_TimeZoneUpdater.tar.zst
        key: packages_apps_TimeZoneUpdater@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_TvSettings.tar.zst
        key: packages_apps_TvSettings@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_apps_WallpaperPicker.tar.zst
        key: packages_apps_WallpaperPicker@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_inputmethods_LatinIME.tar.zst
        key: packages_inputmethods_LatinIME@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_ModuleMetadata.tar.zst
        key: packages_modules_ModuleMetadata@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_modules_NeuralNetworks.tar.zst
        key: packages_modules_NeuralNetworks@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_screensavers_PhotoTable.tar.zst
        key: packages_screensavers_PhotoTable@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/packages_services_Car.tar.zst
        key: packages_services_Car@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_build-tools.tar.zst
        key: prebuilts_build-tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_clang_host_linux-x86.tar.zst
        key: prebuilts_clang_host_linux-x86@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9.tar.zst
        key: prebuilts_gcc_linux-x86_x86_x86_64-linux-android-4.9@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk11.tar.zst
        key: prebuilts_jdk_jdk11@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_jdk_jdk8.tar.zst
        key: prebuilts_jdk_jdk8@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_maven_repo_bumptech.tar.zst
        key: prebuilts_maven_repo_bumptech@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_ndk.tar.zst
        key: prebuilts_ndk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_sdk.tar.zst
        key: prebuilts_sdk@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_tools.tar.zst
        key: prebuilts_tools@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_vndk_v28.tar.zst
        key: prebuilts_vndk_v28@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_vndk_v29.tar.zst
        key: prebuilts_vndk_v29@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/prebuilts_vndk_v30.tar.zst
        key: prebuilts_vndk_v30@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_apex.tar.zst
        key: system_apex@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bpf.tar.zst
        key: system_bpf@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_bt.tar.zst
        key: system_bt@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_connectivity_wificond.tar.zst
        key: system_connectivity_wificond@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_core.tar.zst
        key: system_core@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_extras.tar.zst
        key: system_extras@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_gsid.tar.zst
        key: system_gsid@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_hardware_interfaces.tar.zst
        key: system_hardware_interfaces@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_hwservicemanager.tar.zst
        key: system_hwservicemanager@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_incremental_delivery.tar.zst
        key: system_incremental_delivery@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_iorap.tar.zst
        key: system_iorap@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libbase.tar.zst
        key: system_libbase@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libfmq.tar.zst
        key: system_libfmq@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhidl.tar.zst
        key: system_libhidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libhwbinder.tar.zst
        key: system_libhwbinder@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_libprocinfo.tar.zst
        key: system_libprocinfo@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_logging.tar.zst
        key: system_logging@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_media.tar.zst
        key: system_media@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_memory_lmkd.tar.zst
        key: system_memory_lmkd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_netd.tar.zst
        key: system_netd@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_security.tar.zst
        key: system_security@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_sepolicy.tar.zst
        key: system_sepolicy@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_server_configurable_flags.tar.zst
        key: system_server_configurable_flags@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_tools_aidl.tar.zst
        key: system_tools_aidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_tools_hidl.tar.zst
        key: system_tools_hidl@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_unwinding.tar.zst
        key: system_unwinding@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_update_engine.tar.zst
        key: system_update_engine@${{ env.branch }}
    - uses: actions/cache@v4
      with:
        path: cache/system_vold.tar.zst
        key: system_vold@${{ env.branch }}
    - run: sudo apt update && sudo apt install -y ninja-build python2 libncurses5
    - run: bash kati/kati_download.sh
    - run: bash kati/kati_build.sh
    - run: bash kati/kati_upload.sh
