
name: AOSP Build
on:
  push:
    tags:
    - '*'
env:
  branch: 'android-12.0.0_r1'
jobs:

  build_step1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Call Composite Action bootstrap
      uses: ./.github/actions/bootstrap
      id: bootstrap

    - name: Restore Cache external/rust/crates/nom
      id: external_rust_crates_nom
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/nom
        key: external_rust_crates_nom@${{ env.branch }}
        restore-keys: external_rust_crates_nom@${{ env.branch }}
    - name: Clone project external/rust/crates/nom
      if: steps.external_rust_crates_nom.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/nom
    - name: Restore Cache external/rust/crates/protobuf
      id: external_rust_crates_protobuf
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/protobuf
        key: external_rust_crates_protobuf@${{ env.branch }}
        restore-keys: external_rust_crates_protobuf@${{ env.branch }}
    - name: Clone project external/rust/crates/protobuf
      if: steps.external_rust_crates_protobuf.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/protobuf
    - name: Restore Cache external/rust/crates/aho-corasick
      id: external_rust_crates_aho-corasick
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/aho-corasick
        key: external_rust_crates_aho-corasick@${{ env.branch }}
        restore-keys: external_rust_crates_aho-corasick@${{ env.branch }}
    - name: Clone project external/rust/crates/aho-corasick
      if: steps.external_rust_crates_aho-corasick.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/aho-corasick
    - name: Restore Cache external/rust/crates/clap
      id: external_rust_crates_clap
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/clap
        key: external_rust_crates_clap@${{ env.branch }}
        restore-keys: external_rust_crates_clap@${{ env.branch }}
    - name: Clone project external/rust/crates/clap
      if: steps.external_rust_crates_clap.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/clap
    - name: Restore Cache external/rust/crates/codespan-reporting
      id: external_rust_crates_codespan-reporting
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/codespan-reporting
        key: external_rust_crates_codespan-reporting@${{ env.branch }}
        restore-keys: external_rust_crates_codespan-reporting@${{ env.branch }}
    - name: Clone project external/rust/crates/codespan-reporting
      if: steps.external_rust_crates_codespan-reporting.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/codespan-reporting
    - name: Restore Cache external/rust/crates/futures-channel
      id: external_rust_crates_futures-channel
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/futures-channel
        key: external_rust_crates_futures-channel@${{ env.branch }}
        restore-keys: external_rust_crates_futures-channel@${{ env.branch }}
    - name: Clone project external/rust/crates/futures-channel
      if: steps.external_rust_crates_futures-channel.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/futures-channel
    - name: Restore Cache external/rust/crates/lock_api
      id: external_rust_crates_lock_api
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/lock_api
        key: external_rust_crates_lock_api@${{ env.branch }}
        restore-keys: external_rust_crates_lock_api@${{ env.branch }}
    - name: Clone project external/rust/crates/lock_api
      if: steps.external_rust_crates_lock_api.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/lock_api
    - name: Restore Cache external/rust/crates/proc-macro2
      id: external_rust_crates_proc-macro2
      uses: actions/cache@v3
      with:
        path: aosp/external/rust/crates/proc-macro2
        key: external_rust_crates_proc-macro2@${{ env.branch }}
        restore-keys: external_rust_crates_proc-macro2@${{ env.branch }}
    - name: Clone project external/rust/crates/proc-macro2
      if: steps.external_rust_crates_proc-macro2.outputs.cache-hit != 'true'
      run: |
        pushd aosp
        source $GITHUB_WORKSPACE/envsetup.sh
        clone_depth_platform external/rust/crates/proc-macro2

    - name: Download Release
      run: |
        download_release external_arm-optimized-routines-0 external/arm-optimized-routines build_step0
        download_release external_gwp_asan-0 external/gwp_asan build_step0
        download_release external_scudo-0 external/scudo build_step0
        download_release system_core-0 system/core build_step0
        download_release external_rust_crates_memchr-0 external/rust/crates/memchr build_step0
        download_release external_rust_crates_bytes-0 external/rust/crates/bytes build_step0
        download_release external_rust_crates_bitflags-0 external/rust/crates/bitflags build_step0
        download_release external_rust_crates_textwrap-0 external/rust/crates/textwrap build_step0
        download_release external_rust_crates_termcolor-0 external/rust/crates/termcolor build_step0
        download_release external_rust_crates_unicode-width-0 external/rust/crates/unicode-width build_step0
        download_release external_rust_crates_futures-core-0 external/rust/crates/futures-core build_step0
        download_release external_rust_crates_scopeguard-0 external/rust/crates/scopeguard build_step0
        download_release external_rust_crates_unicode-xid-0 external/rust/crates/unicode-xid build_step0

    - name: Build Step-1
      run: |
        pushd aosp
        export TOP=$(pwd)
        $GITHUB_WORKSPACE/steps/build_step1.sh
        df -h

    - uses: ncipollo/release-action@main
      with:
        name: 'build_step1'
        artifacts: "aosp/bionic-0.tar.xz,aosp/external_rust_crates_nom-0.tar.xz,aosp/external_rust_crates_protobuf-0.tar.xz,aosp/external_rust_crates_aho-corasick-0.tar.xz,aosp/external_rust_crates_clap-0.tar.xz,aosp/external_rust_crates_codespan-reporting-0.tar.xz,aosp/external_rust_crates_futures-channel-0.tar.xz,aosp/external_rust_crates_lock_api-0.tar.xz,aosp/external_rust_crates_proc-macro2-0.tar.xz"
        removeArtifacts: true
        allowUpdates: true
